#!/usr/bin/env python3
"""
Check whether files under a target directory exist on other drives,
using Alan's `findphotodates.py` inventory files: ~/*:photo.taken.dates.txt

Supports BOTH inventory formats:

NEW format (tab-separated, generated by newer findphotodates.py):
  filepath<TAB>date_taken<TAB>size_bytes<TAB>mtime_ns<TAB>gps_lat<TAB>gps_lon<TAB>location

OLD format (line-based, generated by older tool versions):
  ./relative/path/to/file.ext: YYYY:MM:DD HH:MM:SS

Matching (best to worst):
- strong: (basename_lower, size_bytes, date_taken)         [needs NEW inventory + target date_taken]
- weak:   (basename_lower, size_bytes)                     [needs NEW inventory]
- medium: (basename_lower, date_taken)                     [works with OLD inventory]
- weakest:name-only (basename_lower)                       [works with OLD inventory; least safe]

Outputs:
- CSV report with found drives and example backup paths
- missing list of target files not found in any inventory
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple

# Optional EXIF reader for JPEGs only (nice-to-have). Script works without it.
try:
    import exifread  # type: ignore
except Exception:
    exifread = None


@dataclass(frozen=True)
class TargetFile:
    path: Path
    basename_lower: str
    size: int
    date_taken: str  # may be ""


def iter_inventory_rows(inv_path: Path) -> Iterable[Tuple[str, str, Optional[int]]]:
    """
    Yields (filepath, date_taken, size_bytes) from either:
      NEW format (tab-separated):
        filepath<TAB>date_taken<TAB>size_bytes<TAB>mtime_ns<TAB>...
      OLD format:
        ./some/path/file.jpg: YYYY:MM:DD HH:MM:SS

    size_bytes will be None for the OLD format.
    Skips comment lines starting with '#'.
    """
    old_re = re.compile(
        r"^(?P<path>.+?):\s+(?P<dt>\d{4}:\d{2}:\d{2}\s+\d{2}:\d{2}:\d{2})\s*$"
    )

    with inv_path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue

            # NEW format: tab-separated, at least 3 columns
            if "\t" in line:
                parts = line.split("\t")
                if len(parts) < 3:
                    continue
                filepath = parts[0]
                date_taken = parts[1]
                try:
                    size_bytes = int(parts[2])
                except ValueError:
                    size_bytes = None
                yield filepath, date_taken, size_bytes
                continue

            # OLD format: "./foo/bar.jpg: 2016:01:03 18:03:43"
            m = old_re.match(line)
            if m:
                yield m.group("path"), m.group("dt"), None
                continue

            # Otherwise: unknown line; ignore


def get_jpeg_date_taken(path: Path) -> str:
    """
    Best-effort DateTimeOriginal for JPEGs.
    Returns "" if unavailable or exifread not installed.
    """
    if exifread is None:
        return ""
    try:
        with path.open("rb") as f:
            tags = exifread.process_file(
                f, details=False, stop_tag="EXIF DateTimeOriginal"
            )
        dt = tags.get("EXIF DateTimeOriginal")
        if not dt:
            dt = tags.get("Image DateTime")
        return str(dt) if dt else ""
    except Exception:
        return ""


def is_photo_like(path: Path, exts: Set[str]) -> bool:
    return path.is_file() and path.suffix.lower().lstrip(".") in exts


def drive_label_from_inventory_filename(inv_path: Path) -> str:
    # e.g. "/home/alan/o:photo.taken.dates.txt" -> "o"
    name = inv_path.name
    if ":" in name:
        return name.split(":", 1)[0]
    return inv_path.stem


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--target",
        required=True,
        help="Folder to verify (e.g. /home/alan/p/L/2023)",
    )
    ap.add_argument(
        "--inventories",
        default="",
        help="Comma-separated inventory files. If omitted, uses ~/*:photo.taken.dates.txt",
    )
    ap.add_argument(
        "--exclude-path-regex",
        default=r"/\$RECYCLE\.BIN/|/\.Trash/|/@eaDir/|/\.DS_Store$",
        help="Regex for inventory filepaths to ignore (trash/recycle bin etc.)",
    )
    ap.add_argument(
        "--exts",
        default="jpg,jpeg,png,tif,tiff,orf,nef,arw,dng,cr2,cr3,raf,heic,mp4,mov",
        help="Comma-separated extensions to consider in target scan",
    )
    ap.add_argument(
        "--out-csv",
        default="backup_check_report.csv",
        help="CSV report path",
    )
    ap.add_argument(
        "--missing-list",
        default="missing_from_backups.txt",
        help="Write missing target file paths here",
    )
    args = ap.parse_args()

    target_dir = Path(args.target).expanduser().resolve()
    if not target_dir.is_dir():
        print(f"ERROR: target is not a directory: {target_dir}", file=sys.stderr)
        return 2

    # Inventory list
    if args.inventories.strip():
        inv_files = [
            Path(p).expanduser()
            for p in args.inventories.split(",")
            if p.strip()
        ]
    else:
        inv_files = sorted(Path.home().glob("*:photo.taken.dates.txt"))

    if not inv_files:
        print(
            "ERROR: no inventory files found. Provide --inventories or create ~/?:photo.taken.dates.txt",
            file=sys.stderr,
        )
        return 2

    exclude_re = re.compile(args.exclude_path_regex)
    exts = {e.strip().lower() for e in args.exts.split(",") if e.strip()}

    # Build backup indexes.
    # Strong (requires size, usually from NEW inventories):
    strong_drives: Dict[Tuple[str, int, str], Set[str]] = {}
    strong_paths: Dict[Tuple[str, int, str], List[str]] = {}

    weak_drives: Dict[Tuple[str, int], Set[str]] = {}
    weak_paths: Dict[Tuple[str, int], List[str]] = {}

    # Medium + weakest (work with OLD inventories too):
    name_date_drives: Dict[Tuple[str, str], Set[str]] = {}
    name_date_paths: Dict[Tuple[str, str], List[str]] = {}

    name_only_drives: Dict[str, Set[str]] = {}
    name_only_paths: Dict[str, List[str]] = {}

    print(f"Loading {len(inv_files)} inventory file(s)...")
    for inv in inv_files:
        inv = inv.expanduser().resolve()
        if not inv.exists():
            print(f"WARNING: inventory missing: {inv}", file=sys.stderr)
            continue

        drive = drive_label_from_inventory_filename(inv)
        row_count = 0
        kept = 0

        for filepath, date_taken, size_bytes in iter_inventory_rows(inv):
            row_count += 1

            # Filter out recycle/trash entries
            if exclude_re.search(filepath):
                continue

            base = os.path.basename(filepath).lower()
            if not base:
                continue

            # Always index name-only (last resort)
            name_only_drives.setdefault(base, set()).add(drive)
            name_only_paths.setdefault(base, [])
            if len(name_only_paths[base]) < 3:
                name_only_paths[base].append(filepath)

            # If date_taken exists, index (name + date_taken)
            if date_taken:
                ndk = (base, date_taken)
                name_date_drives.setdefault(ndk, set()).add(drive)
                name_date_paths.setdefault(ndk, [])
                if len(name_date_paths[ndk]) < 3:
                    name_date_paths[ndk].append(filepath)

            # If size exists (NEW inventories), also index stronger keys
            if size_bytes is not None:
                sk = (base, size_bytes, date_taken)
                strong_drives.setdefault(sk, set()).add(drive)
                strong_paths.setdefault(sk, [])
                if len(strong_paths[sk]) < 3:
                    strong_paths[sk].append(filepath)

                wk = (base, size_bytes)
                weak_drives.setdefault(wk, set()).add(drive)
                weak_paths.setdefault(wk, [])
                if len(weak_paths[wk]) < 3:
                    weak_paths[wk].append(filepath)

            kept += 1

        print(f"  {inv.name}: rows={row_count:,} kept={kept:,} drive={drive}")

    # Scan target directory
    targets: List[TargetFile] = []
    print(f"Scanning target: {target_dir}")

    for p in target_dir.rglob("*"):
        if not is_photo_like(p, exts):
            continue
        try:
            st = p.stat()
        except FileNotFoundError:
            continue

        base = p.name.lower()
        date_taken = ""
        if p.suffix.lower() in (".jpg", ".jpeg"):
            date_taken = get_jpeg_date_taken(p)

        targets.append(
            TargetFile(
                path=p,
                basename_lower=base,
                size=st.st_size,
                date_taken=date_taken,
            )
        )

    print(f"Target files considered: {len(targets):,}")

    # Match
    rows_out: List[dict] = []
    missing: List[Path] = []
    strong_hits = 0
    weak_hits = 0
    name_date_hits = 0
    name_only_hits = 0

    # Per-directory tracking: dir -> {total, found}
    dir_stats: Dict[Path, Dict[str, int]] = {}

    for t in targets:
        match_strength = ""
        drives: Set[str] = set()
        example_paths: List[str] = []

        if t.date_taken:
            # Best: strong match (name + size + date_taken)
            sk = (t.basename_lower, t.size, t.date_taken)
            if sk in strong_drives:
                drives = strong_drives[sk]
                example_paths = strong_paths.get(sk, [])
                match_strength = "strong(basename+size+date_taken)"
                strong_hits += 1
            else:
                # Next: weak (name + size)
                wk = (t.basename_lower, t.size)
                if wk in weak_drives:
                    drives = weak_drives[wk]
                    example_paths = weak_paths.get(wk, [])
                    match_strength = "weak(basename+size)"
                    weak_hits += 1
                else:
                    # Next: medium (name + date_taken) for OLD inventories
                    ndk = (t.basename_lower, t.date_taken)
                    if ndk in name_date_drives:
                        drives = name_date_drives[ndk]
                        example_paths = name_date_paths.get(ndk, [])
                        match_strength = "name+date_taken(old inventories)"
                        name_date_hits += 1
                    else:
                        # Last: name-only
                        if t.basename_lower in name_only_drives:
                            drives = name_only_drives[t.basename_lower]
                            example_paths = name_only_paths.get(
                                t.basename_lower, []
                            )
                            match_strength = "name-only(least safe)"
                            name_only_hits += 1
        else:
            # If we don't have a date_taken for the target file:
            wk = (t.basename_lower, t.size)
            if wk in weak_drives:
                drives = weak_drives[wk]
                example_paths = weak_paths.get(wk, [])
                match_strength = "weak(basename+size)"
                weak_hits += 1
            else:
                if t.basename_lower in name_only_drives:
                    drives = name_only_drives[t.basename_lower]
                    example_paths = name_only_paths.get(t.basename_lower, [])
                    match_strength = "name-only(least safe)"
                    name_only_hits += 1

        found = bool(drives)
        if not found:
            missing.append(t.path)

        # Track per-directory stats
        file_dir = t.path.parent
        if file_dir not in dir_stats:
            dir_stats[file_dir] = {"total": 0, "found": 0}
        dir_stats[file_dir]["total"] += 1
        if found:
            dir_stats[file_dir]["found"] += 1

        rows_out.append(
            {
                "target_path": str(t.path),
                "basename": t.basename_lower,
                "size_bytes": t.size,
                "date_taken": t.date_taken,
                "found": "yes" if found else "no",
                "found_drives": ",".join(sorted(drives)),
                "match_strength": match_strength,
                "example_backup_paths": " | ".join(example_paths),
            }
        )

    # Write CSV
    out_csv = Path(args.out_csv).expanduser().resolve()
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "target_path",
                "basename",
                "size_bytes",
                "date_taken",
                "found",
                "found_drives",
                "match_strength",
                "example_backup_paths",
            ],
        )
        w.writeheader()
        w.writerows(rows_out)

    # Write missing list
    missing_path = Path(args.missing_list).expanduser().resolve()
    with missing_path.open("w", encoding="utf-8") as f:
        for p in missing:
            f.write(str(p) + "\n")

    # Summary
    print()
    print("=== Summary ===")
    print(f"CSV report:    {out_csv}")
    print(f"Missing list:  {missing_path}")
    print(f"Strong matches:    {strong_hits:,}")
    print(f"Weak matches:      {weak_hits:,}")
    print(f"Name+date matches: {name_date_hits:,}")
    print(f"Name-only matches: {name_only_hits:,}")
    print(f"Missing:           {len(missing):,}")

    if missing:
        print("\nFirst 20 missing:")
        for p in missing[:20]:
            print(f"  {p}")

    # Directories safe to delete (all files backed up on other drives)
    safe_dirs = sorted(
        d for d, s in dir_stats.items() if s["total"] == s["found"]
    )
    not_safe_dirs = sorted(
        d for d, s in dir_stats.items() if s["total"] != s["found"]
    )

    if safe_dirs:
        print(f"\n=== Directories safe to delete ({len(safe_dirs)}) ===")
        print("(All files in these directories are backed up on other drives)")
        for d in safe_dirs:
            s = dir_stats[d]
            rel = d.relative_to(target_dir) if d != target_dir else Path(".")
            print(f"  {rel}/  ({s['total']} files, all backed up)")

    if not_safe_dirs:
        print(f"\n=== Directories NOT fully backed up ({len(not_safe_dirs)}) ===")
        for d in not_safe_dirs:
            s = dir_stats[d]
            rel = d.relative_to(target_dir) if d != target_dir else Path(".")
            n_missing = s["total"] - s["found"]
            print(f"  {rel}/  ({n_missing} of {s['total']} files missing from backups)")

    # Exit code: non-zero if missing (useful for scripts)
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())

