#!/usr/bin/env python3
"""
Check whether files under a target directory exist on other drives,
using Alan's `findphotodates.py` inventory files: ~/*:photo.taken.dates.txt

Supports BOTH inventory formats:

NEW format (tab-separated, generated by newer findphotodates.py):
  filepath<TAB>date_taken<TAB>size_bytes<TAB>mtime_ns<TAB>gps_lat<TAB>gps_lon<TAB>location<TAB>content_hash

OLD format (line-based, generated by older tool versions):
  ./relative/path/to/file.ext: YYYY:MM:DD HH:MM:SS

Matching (best to worst):
- verified_hash: (size_bytes, content_hash)              [needs NEW inventory + compatible hash config]
- strong: (basename_lower, size_bytes, date_taken)         [needs NEW inventory + target date_taken]
- weak:   (basename_lower, size_bytes)                     [needs NEW inventory]
- name_date: (basename_lower, date_taken)                  [works with OLD inventory]
- name_only: (basename_lower)                              [works with OLD inventory; least safe]

Outputs:
- CSV report with found drives and example backup paths
- various lists (.txt) for different safety/verification states
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import os
import re
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple

# Optional EXIF reader for JPEGs only (nice-to-have). Script works without it.
try:
    import exifread  # type: ignore
except Exception:
    exifread = None

# Optional blake3 support
try:
    import blake3

    _BLAKE3_AVAILABLE = True
except ImportError:
    blake3 = None
    _BLAKE3_AVAILABLE = False


@dataclass(frozen=True)
class TargetFile:
    path: Path
    basename_lower: str
    size: int
    mtime_ns: int
    date_taken: str = ""  # may be ""
    content_hash: str = ""


def resolve_inventory_display_path(filepath: str, root: Optional[str]) -> str:
    # Handle Windows paths on POSIX
    if re.match(r"^[A-Za-z]:[\\/]", filepath):
        return os.path.normpath(filepath)
    if os.path.isabs(filepath):
        return os.path.normpath(filepath)
    fp = filepath
    if root:
        # strip leading ./ or .\
        if fp.startswith("./") or fp.startswith(".\\"):
            fp = fp[2:]
        fp = os.path.join(root, fp)
    return os.path.normpath(fp)


_HEX_RE = re.compile(r"^[0-9a-fA-F]+$")


def iter_inventory_rows(
    inv_path: Path,
    debug: bool = False,
) -> Iterable[Tuple[str, str, Optional[int], Optional[int], str, Dict[str, str]]]:
    """
    Yields (filepath, date_taken, size_bytes, mtime_ns, content_hash, headers) from either:
      NEW format (tab-separated):
        filepath<TAB>date_taken<TAB>size_bytes<TAB>mtime_ns<TAB>...<TAB>content_hash
      OLD format:
        ./some/path/file.jpg: YYYY:MM:DD HH:MM:SS

    Headers are collected from any leading # key=value lines before the data rows.

    Safety notes:
    - NEW format REQUIRES an explicit header row starting with 'filepath'.
      TSV files without this header are rejected (not guessed) to prevent
      column misalignment from silently producing wrong matches.
    - content_hash values must be hex strings or empty; non-hex values are
      treated as empty to prevent garbage data from matching real hashes.
    - size_bytes must be a non-negative integer; invalid values become None.
    """
    old_re = re.compile(
        r"^(?P<path>.+?):\s+(?P<dt>\d{4}:\d{2}:\d{2}\s+\d{2}:\d{2}:\d{2})\s*$"
    )
    headers: Dict[str, str] = {}
    parsing_comments = True
    fieldnames: Optional[List[str]] = None
    skipped = 0

    with inv_path.open("r", encoding="utf-8", errors="replace") as f:
        reader = csv.reader(f, delimiter="\t")
        for parts in reader:
            if not parts:
                continue

            line = parts[0]
            if parsing_comments and line.startswith("#"):
                clean_line = line.lstrip("# ").strip()

                # Check for special prefixes first (must handle before key=value)
                if clean_line.startswith("samplehash_v1"):
                    headers["samplehash_v1"] = clean_line.split("samplehash_v1", 1)[
                        1
                    ].strip()
                elif clean_line.startswith("fullhash"):
                    headers["fullhash"] = clean_line.split("fullhash", 1)[1].strip()
                elif "=" in clean_line:
                    key_val = clean_line.split("=", 1)
                    if len(key_val) == 2:
                        headers[key_val[0].strip()] = key_val[1].strip()
                continue

            # First non-comment line
            parsing_comments = False

            # NEW format: tab-separated (csv.reader already split it)
            if len(parts) > 1:
                if fieldnames is None:
                    if parts[0] == "filepath":
                        fieldnames = parts
                        continue
                    else:
                        # SAFETY: Reject TSV files without an explicit header row.
                        # Column-count guessing risks misaligning fields, which could
                        # cause size_bytes or content_hash to be read from the wrong
                        # column — potentially marking files as safe to delete incorrectly.
                        print(
                            f"WARNING: Skipping {inv_path.name}: tab-separated data found but no 'filepath' header row. "
                            f"This inventory may be corrupt or from an unsupported version.",
                            file=sys.stderr,
                        )
                        return

                if len(parts) != len(fieldnames):
                    if debug:
                        print(
                            f"DEBUG: Row has {len(parts)} fields, expected {len(fieldnames)}: {parts!r}",
                            file=sys.stderr,
                        )
                    skipped += 1
                    continue
                row = dict(zip(fieldnames, parts))
                filepath = row.get("filepath", "")
                if not filepath:
                    skipped += 1
                    continue
                date_taken = row.get("date_taken", "")
                size_bytes: Optional[int] = None
                mtime_ns: Optional[int] = None

                try:
                    val = int(row.get("size_bytes", ""))
                    if val >= 0:
                        size_bytes = val
                    else:
                        if debug:
                            print(
                                f"DEBUG: Negative size_bytes ({val}) for {filepath}, treating as unknown",
                                file=sys.stderr,
                            )
                except (ValueError, TypeError):
                    pass

                try:
                    mtime_ns = int(row.get("mtime_ns", ""))
                except (ValueError, TypeError):
                    pass

                content_hash = (row.get("content_hash") or "").strip()
                # SAFETY: Only accept hex-encoded hashes. A non-hex string could be
                # a misaligned column value; treating it as a valid hash could cause
                # false verified_hash matches.
                if content_hash and not _HEX_RE.match(content_hash):
                    if debug:
                        print(
                            f"DEBUG: Non-hex content_hash for {filepath}: {content_hash!r}, treating as empty",
                            file=sys.stderr,
                        )
                    content_hash = ""
                else:
                    content_hash = content_hash.lower()

                yield filepath, date_taken, size_bytes, mtime_ns, content_hash, headers
                continue

            # OLD format: "./foo/bar.jpg: 2016:01:03 18:03:43"
            m = old_re.match(line)
            if m:
                yield m.group("path"), m.group("dt"), None, None, "", headers
                continue

    if skipped and debug:
        print(
            f"DEBUG: {inv_path.name}: skipped {skipped} rows with empty filepath",
            file=sys.stderr,
        )


def compute_samplehash_v1(
    path: Path,
    chunk_bytes: int,
    chunks: int = 3,
    algo: str = "blake2b",
) -> str:
    """Compute a fingerprint by hashing 'chunks' pieces of 'chunk_bytes' size.
    Consistent with findphotodates.py samplehash_v1.
    """
    try:
        size = path.stat().st_size
    except OSError:
        return ""

    if algo == "blake3":
        if not blake3:
            return ""
        h = blake3.blake3()
    elif algo == "sha256":
        h = hashlib.sha256()
    else:
        # Standard blake2b fingerprint in this tool uses 128-bit (16 byte) digest
        h = hashlib.blake2b(digest_size=16)

    h.update(str(size).encode("ascii"))
    h.update(b"\0")

    if size <= chunks * chunk_bytes or size == 0:
        try:
            with path.open("rb") as f:
                # Stream the entire file in chunks to avoid memory blow-up
                for data in iter(lambda: f.read(65536), b""):
                    h.update(data)
            return h.hexdigest()
        except OSError:
            return ""

    offsets = []
    end_offset = max(0, size - chunk_bytes)
    for i in range(chunks):
        if i == 0:
            offset = 0
        elif i == chunks - 1:
            offset = end_offset
        else:
            offset = (i * end_offset) // (chunks - 1) if chunks > 1 else 0
        offsets.append(max(0, min(offset, end_offset)))

    try:
        with path.open("rb") as f:
            for off in sorted(list(set(offsets))):
                f.seek(off)
                data = f.read(chunk_bytes)
                if data:
                    h.update(data)
    except OSError:
        return ""
    return h.hexdigest()


def compute_fullhash(path: Path, algo: str = "sha256") -> str:
    """Compute full-file hash."""
    if algo == "blake3" and _BLAKE3_AVAILABLE:
        try:
            with path.open("rb") as f:
                h = blake3.blake3()
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
                return h.hexdigest()
        except OSError:
            return ""
    else:
        try:
            h = hashlib.sha256()
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            return h.hexdigest()
        except OSError:
            return ""


class FingerprintCache:
    def __init__(self, cache_path: Path):
        self.cache_path = cache_path
        self._conn: Optional[sqlite3.Connection] = None
        self._pending_inserts = 0
        if not self.cache_path.parent.exists():
            self.cache_path.parent.mkdir(parents=True, exist_ok=True)

    def _get_conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self._conn = sqlite3.connect(str(self.cache_path))
            self._conn.execute("PRAGMA journal_mode=WAL;")
            self._conn.execute("PRAGMA synchronous=NORMAL;")
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS fingerprints (
                    path TEXT,
                    size INTEGER,
                    mtime_ns INTEGER,
                    mode TEXT,
                    chunks INTEGER,
                    chunk_bytes INTEGER,
                    algo TEXT,
                    hash TEXT,
                    PRIMARY KEY (path, size, mtime_ns, mode, chunks, chunk_bytes, algo)
                )
                """
            )
        return self._conn

    def get(
        self,
        path: Path,
        size: int,
        mtime_ns: int,
        mode: str,
        chunks: int,
        chunk_bytes: int,
        algo: str,
    ) -> Optional[str]:
        conn = self._get_conn()
        cur = conn.execute(
            "SELECT hash FROM fingerprints WHERE path=? AND size=? AND mtime_ns=? AND mode=? AND chunks=? AND chunk_bytes=? AND algo=?",
            (str(path), size, mtime_ns, mode, chunks, chunk_bytes, algo),
        )
        row = cur.fetchone()
        return row[0] if row else None

    def set(
        self,
        path: Path,
        size: int,
        mtime_ns: int,
        mode: str,
        chunks: int,
        chunk_bytes: int,
        algo: str,
        hash_val: str,
    ):
        conn = self._get_conn()
        conn.execute(
            "INSERT OR REPLACE INTO fingerprints (path, size, mtime_ns, mode, chunks, chunk_bytes, algo, hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (str(path), size, mtime_ns, mode, chunks, chunk_bytes, algo, hash_val),
        )
        self._pending_inserts += 1
        if self._pending_inserts >= 1000:
            self.commit()

    def commit(self):
        if self._conn:
            self._conn.commit()
            self._pending_inserts = 0

    def close(self):
        if self._conn:
            self.commit()
            self._conn.close()
            self._conn = None


def get_jpeg_date_taken(path: Path) -> str:
    if exifread is None:
        return ""
    try:
        with path.open("rb") as f:
            tags = exifread.process_file(
                f, details=False, stop_tag="EXIF DateTimeOriginal"
            )
        dt = tags.get("EXIF DateTimeOriginal") or tags.get("Image DateTime")
        return str(dt) if dt else ""
    except Exception:
        return ""


def is_photo_like(path: Path, exts: Set[str]) -> bool:
    return path.is_file() and path.suffix.lower().lstrip(".") in exts


def human_readable_size(size_bytes: int) -> str:
    val = float(size_bytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if abs(val) < 1024 or unit == "TB":
            return f"{val:.1f} {unit}" if unit != "B" else f"{int(val)} B"
        val /= 1024
    return f"{val:.1f} TB"  # Default


def drive_label_from_inventory_filename(inv_path: Path) -> str:
    name = inv_path.name
    # Support 'c:photo...' or 'c_photo...'
    if ":" in name:
        return name.split(":", 1)[0]
    # Only treat underscore as delimiter if it looks like a drive label prefix
    if "_" in name and (
        name.lower().startswith("drive") or len(name.split("_")[0]) <= 2
    ):
        return name.split("_", 1)[0]
    return inv_path.stem


def parse_config_str(config_str: str) -> dict:
    """Parse a config string like 'algo=blake3 chunks=3 chunk_mib=1.0' into a dict."""
    res = {}
    if not config_str:
        return res
    for part in config_str.split(" "):
        if "=" in part:
            k, v = part.split("=", 1)
            res[k.strip()] = v.strip()
    return res


@dataclass(frozen=True)
class InvHashConfig:
    """Hash configuration derived from an inventory's headers.

    Used to compute target hashes with the exact same parameters
    the inventory used, ensuring hash comparisons are valid.
    """

    mode: str  # "sample" or "full"
    algo: str  # "blake3", "blake2b", or "sha256"
    chunks: int  # number of sample chunks (0 for full)
    chunk_bytes: int  # bytes per chunk (0 for full)


# ---------------------------------------------------------------------------
# Safe-to-delete classification — the SOLE gate for deletion decisions.
# ---------------------------------------------------------------------------
# SAFETY_LEVELS that are considered safe to delete.  To mark a file as safe,
# its safety value must appear in this frozenset.  Everything else is NOT safe.
SAFE_SAFETY_VALUES = frozenset(
    {"verified_hash", "strong_nohash_allowed", "weak_nohash_allowed"}
)


def classify_safe_to_delete(safety: str) -> bool:
    """Return True if ``safety`` is one of the values that permits deletion.

    This is the single authoritative check.  All code paths that decide whether
    a file may be deleted MUST call this function rather than inlining the check.

    Safe values:
      - verified_hash:          content hash matched an inventory entry with
                                compatible hash config.
      - strong_nohash_allowed:  name+size+date matched AND the user passed
                                --allow-strong-without-hash.
      - weak_nohash_allowed:    name+size matched AND the user passed
                                --allow-weak-without-hash.

    Everything else (strong, weak, name_date, name_only, missing,
    hash_config_mismatch) is NOT safe.
    """
    return safety in SAFE_SAFETY_VALUES


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", required=True, help="Folder to verify (staging area)")
    ap.add_argument("--inventories", default="", help="Comma-separated inventory files")
    ap.add_argument(
        "--exclude-path-regex",
        default=r"/\$RECYCLE\.BIN/|/\.Trash/|/@eaDir/|/\.DS_Store$",
        help="Regex for filepaths to ignore",
    )
    ap.add_argument(
        "--exts",
        default="jpg,jpeg,png,tif,tiff,orf,nef,arw,dng,cr2,cr3,raf,heic,mp4,mov",
        help="Comma-separated extensions",
    )
    ap.add_argument(
        "--out-csv", default="backup_check_report.csv", help="CSV report path"
    )
    ap.add_argument(
        "--missing-list",
        default="missing_from_backups.txt",
        help="Missing target file paths",
    )
    ap.add_argument(
        "--safe-list", default="safe_to_delete.txt", help="SAFE to delete file paths"
    )
    ap.add_argument(
        "--needs-hash-list",
        default="needs_hash.txt",
        help="Metadata matches lacking hash verification",
    )
    ap.add_argument(
        "--no-verified-match-list",
        default="no_verified_match.txt",
        help="Hashed but not found in any inventory",
    )
    ap.add_argument(
        "--hash-config-mismatch-list",
        default="hash_config_mismatch.txt",
        help="Hashed but rejected due to config mismatch",
    )
    ap.add_argument(
        "--delete-script", default="", help="Write a shell script to delete safe files"
    )
    ap.add_argument("--sort", action="store_true", help="Sort safe directories by size")
    ap.add_argument(
        "--hash-mode",
        choices=["auto", "compute", "off"],
        default="auto",
        help="Target hashing mode (default: auto — compute only when inventories have hashes)",
    )
    ap.add_argument("--sample-chunk-mib", type=float, default=0.0625)
    ap.add_argument("--sample-chunks", type=int, default=3)
    ap.add_argument(
        "--hash-algo", choices=["auto", "blake3", "blake2b", "sha256"], default="auto"
    )
    ap.add_argument(
        "--fingerprint-cache",
        default="~/.cache/check_photo_backups/fingerprints.sqlite",
    )
    ap.add_argument("--no-fingerprint-cache", action="store_true")
    ap.add_argument(
        "--drive-map", default="", help="Mapping of drive labels to roots: c=/mnt/c"
    )
    ap.add_argument("--allow-strong-without-hash", action="store_true")
    ap.add_argument("--allow-weak-without-hash", action="store_true")
    ap.add_argument(
        "--allow-hash-config-mismatch",
        action="store_true",
        help="Deprecated and ignored. Target hashes are now computed per-inventory config.",
    )
    ap.add_argument("-q", "--quiet", action="store_true", help="Suppress normal output")
    ap.add_argument("--debug", action="store_true", help="Enable debug logging")
    args = ap.parse_args()

    # Resolve algorithms
    resolved_sample_algo = args.hash_algo
    if resolved_sample_algo == "auto":
        resolved_sample_algo = "blake3" if _BLAKE3_AVAILABLE else "blake2b"

    resolved_full_algo = args.hash_algo
    if resolved_full_algo in ("auto", "blake2b"):
        resolved_full_algo = "blake3" if _BLAKE3_AVAILABLE else "sha256"

    target_dir = Path(args.target).expanduser().resolve()
    if not target_dir.is_dir():
        print(f"ERROR: target is not a directory: {target_dir}", file=sys.stderr)
        return 2

    if args.inventories.strip():
        inv_files = [
            Path(p).expanduser() for p in args.inventories.split(",") if p.strip()
        ]
    else:
        inv_files = (
            sorted(Path.home().glob("*:photo.taken.dates.txt"))
            + sorted(Path.home().glob("*_photo.taken.dates.txt"))
            + sorted(Path.home().glob("*:photo.taken.dates.tsv"))
            + sorted(Path.home().glob("*_photo.taken.dates.tsv"))
        )

    if not inv_files:
        print("ERROR: no inventory files found.", file=sys.stderr)
        return 2

    exclude_re = re.compile(args.exclude_path_regex)
    exts = {e.strip().lower() for e in args.exts.split(",") if e.strip()}
    drive_map = {
        k.strip(): v.strip()
        for item in args.drive_map.split(",")
        if "=" in item
        for k, v in [item.split("=", 1)]
    }

    # hash_drives is keyed by (InvHashConfig, size_bytes, content_hash) so that
    # verified_hash requires proving the inventory entry came from the same config
    # family as the target hash.  This prevents cross-config collisions (however
    # unlikely) from producing false verified_hash matches.
    hash_drives: Dict[Tuple[InvHashConfig, int, str], Set[str]] = {}
    hash_paths: Dict[Tuple[InvHashConfig, int, str], List[str]] = {}
    strong_drives, weak_drives, name_date_drives, name_only_drives = {}, {}, {}, {}
    strong_paths, weak_paths, name_date_paths, name_only_paths = {}, {}, {}, {}
    inv_hash_configs: Set[InvHashConfig] = set()
    sizes_with_hashes: Set[int] = set()

    def add_example_path(d, k, p):
        lst = d.setdefault(k, [])
        if len(lst) < 3:
            lst.append(p)

    _VALID_HASH_ALGOS = {"blake3", "blake2b", "sha256"}

    def _parse_inv_hash_config(hdrs: Dict[str, str]) -> Optional[InvHashConfig]:
        """Parse an InvHashConfig from inventory comment headers, or None."""
        try:
            if "samplehash_v1" in hdrs:
                cfg = parse_config_str(hdrs["samplehash_v1"])
                algo = cfg.get("algo", resolved_sample_algo)
                if algo not in _VALID_HASH_ALGOS:
                    print(f"WARNING: Unknown hash algo {algo!r} in inventory header, skipping", file=sys.stderr)
                    return None
                chunks = int(cfg.get("chunks", str(args.sample_chunks)))
                chunk_mib = float(cfg.get("chunk_mib", str(args.sample_chunk_mib)))
                if chunks <= 0 or chunk_mib <= 0:
                    print(f"WARNING: Invalid sample hash params (chunks={chunks}, chunk_mib={chunk_mib})", file=sys.stderr)
                    return None
                return InvHashConfig("sample", algo, chunks, int(chunk_mib * 1024 * 1024))
            if "fullhash" in hdrs:
                cfg = parse_config_str(hdrs.get("fullhash", ""))
                algo = cfg.get("algo", resolved_full_algo)
                if algo not in _VALID_HASH_ALGOS:
                    print(f"WARNING: Unknown hash algo {algo!r} in inventory header, skipping", file=sys.stderr)
                    return None
                return InvHashConfig("full", algo, 0, 0)
        except (ValueError, TypeError) as exc:
            print(f"WARNING: Malformed hash config in inventory header: {exc}", file=sys.stderr)
            return None
        return None

    print(f"Loading {len(inv_files)} inventory file(s)...")
    for inv in inv_files:
        inv = inv.expanduser().resolve()
        if not inv.exists():
            continue
        drive = drive_label_from_inventory_filename(inv)
        kept, hashes_found_in_inv, inv_headers = 0, 0, {}
        current_inv_cfg: Optional[InvHashConfig] = None  # resolved once per inventory

        for (
            filepath,
            date_taken,
            size_bytes,
            _mtime_ns,
            content_hash,
            headers,
        ) in iter_inventory_rows(inv, debug=args.debug):
            inv_headers = headers
            # Parse config on first row (headers are stable for the whole file)
            if current_inv_cfg is None:
                current_inv_cfg = _parse_inv_hash_config(headers)

            display_path = resolve_inventory_display_path(
                filepath, headers.get("inventory_root") or drive_map.get(drive)
            )

            # Normalize to forward slashes for cross-platform regex matching
            match_path = display_path.replace(os.sep, "/").replace("\\", "/")
            if exclude_re.search(match_path):
                continue

            # Use forward slashes so os.path.basename works on Windows paths read on POSIX
            base = os.path.basename(filepath.replace("\\", "/")).lower()
            if not base:
                continue
            name_only_drives.setdefault(base, set()).add(drive)
            add_example_path(name_only_paths, base, display_path)
            if date_taken:
                ndk = (base, date_taken)
                name_date_drives.setdefault(ndk, set()).add(drive)
                add_example_path(name_date_paths, ndk, display_path)
            if size_bytes is not None:
                if content_hash and current_inv_cfg is not None:
                    sizes_with_hashes.add(size_bytes)
                    hk = (current_inv_cfg, size_bytes, content_hash)
                    hash_drives.setdefault(hk, set()).add(drive)
                    add_example_path(hash_paths, hk, display_path)
                    hashes_found_in_inv += 1
                sk, wk = (base, size_bytes, date_taken), (base, size_bytes)
                strong_drives.setdefault(sk, set()).add(drive)
                add_example_path(strong_paths, sk, display_path)
                weak_drives.setdefault(wk, set()).add(drive)
                add_example_path(weak_paths, wk, display_path)
            kept += 1

        if current_inv_cfg is not None:
            inv_hash_configs.add(current_inv_cfg)

        if args.debug:
            root = inv_headers.get("inventory_root") or drive_map.get(drive)
            print(
                f"DEBUG: {inv.name}: rows={kept:,} hashes={hashes_found_in_inv:,} drive={drive} root={root} config={current_inv_cfg}"
            )
        else:
            print(
                f"  {inv.name}: rows={kept:,} hashes={hashes_found_in_inv:,} drive={drive}"
            )

    # Warn if any inventory config requires an unavailable algorithm
    for cfg in inv_hash_configs:
        if cfg.algo == "blake3" and not _BLAKE3_AVAILABLE:
            print(
                "WARNING: Inventory uses blake3 but blake3 is not installed locally. "
                "Hash verification will fail for those inventories. Install: pip install blake3",
                file=sys.stderr,
            )
            break

    if not inv_hash_configs and args.hash_mode != "off" and not args.quiet:
        print(
            "Note: No hash-bearing inventories loaded; no verification hashes will be computed."
        )

    if not args.quiet and inv_hash_configs:
        cfgs_desc = ", ".join(
            f"{c.mode}/{c.algo}"
            for c in sorted(inv_hash_configs, key=lambda c: (c.mode, c.algo))
        )
        print(
            f"Will verify against {len(inv_hash_configs)} inventory hash config(s): {cfgs_desc}"
        )

    if args.allow_hash_config_mismatch:
        print(
            "WARNING: --allow-hash-config-mismatch is deprecated and ignored. "
            "Target hashes are now computed per-inventory config, so config mismatches "
            "no longer occur.",
            file=sys.stderr,
        )

    cache = None
    if not args.no_fingerprint_cache:
        cache = FingerprintCache(Path(args.fingerprint_cache).expanduser())

    targets: List[TargetFile] = []
    # Maps target path -> list of (config, hash) for multi-config verification
    target_hashes: Dict[Path, List[Tuple[InvHashConfig, str]]] = {}
    print(f"Scanning target: {target_dir}")

    for p in target_dir.rglob("*"):
        if not is_photo_like(p, exts):
            continue
        try:
            st = p.stat()
        except FileNotFoundError:
            continue
        base, date_taken = p.name.lower(), ""
        if p.suffix.lower() in (".jpg", ".jpeg"):
            date_taken = get_jpeg_date_taken(p)

        hashes: List[Tuple[InvHashConfig, str]] = []
        should_hash = args.hash_mode == "compute" or (
            args.hash_mode == "auto" and st.st_size in sizes_with_hashes
        )

        if should_hash:
            for icfg in inv_hash_configs:
                cached_h: Optional[str] = None
                if cache:
                    cached_h = cache.get(
                        p,
                        st.st_size,
                        st.st_mtime_ns,
                        icfg.mode,
                        icfg.chunks,
                        icfg.chunk_bytes,
                        icfg.algo,
                    )
                if cached_h:
                    hashes.append((icfg, cached_h))
                else:
                    if icfg.mode == "full":
                        h = compute_fullhash(p, icfg.algo)
                    else:
                        h = compute_samplehash_v1(
                            p, icfg.chunk_bytes, icfg.chunks, icfg.algo
                        )
                    if h:
                        hashes.append((icfg, h))
                        if cache:
                            cache.set(
                                p,
                                st.st_size,
                                st.st_mtime_ns,
                                icfg.mode,
                                icfg.chunks,
                                icfg.chunk_bytes,
                                icfg.algo,
                                h,
                            )

        target_hashes[p] = hashes
        display_hash = hashes[0][1] if hashes else ""
        targets.append(
            TargetFile(p, base, st.st_size, st.st_mtime_ns, date_taken, display_hash)
        )

    (
        rows_out,
        missing,
        safe_to_delete,
        needs_hash,
        no_verified_match,
        hash_config_mismatch_list,
    ) = ([], [], [], [], [], [])
    verified_hash_hits = strong_hits = weak_hits = name_date_hits = name_only_hits = (
        metadata_matched_but_not_hashed
    ) = 0
    total_size_safe = total_size_missing = 0
    dir_stats: Dict[Path, Dict[str, int]] = {}

    for t in targets:
        match_type, safety, drives, example_paths = "missing", "missing", set(), []
        # Try all computed hashes (one per inventory hash config).
        # The lookup key includes the InvHashConfig, so a match proves
        # both content identity AND same-config family.
        for icfg, h in target_hashes.get(t.path, []):
            hk = (icfg, t.size, h)
            if hk in hash_drives:
                drives, example_paths = hash_drives[hk], hash_paths.get(hk, [])
                match_type = safety = "verified_hash"
                verified_hash_hits += 1
                break

        if not drives:
            sk, wk = (t.basename_lower, t.size, t.date_taken), (
                t.basename_lower,
                t.size,
            )
            if t.date_taken and sk in strong_drives:
                drives, example_paths, match_type = (
                    strong_drives[sk],
                    strong_paths.get(sk, []),
                    "strong",
                )
                safety = (
                    "strong_nohash_allowed"
                    if args.allow_strong_without_hash
                    else "strong"
                )
                strong_hits += 1
            elif wk in weak_drives:
                drives, example_paths, match_type = (
                    weak_drives[wk],
                    weak_paths.get(wk, []),
                    "weak",
                )
                safety = (
                    "weak_nohash_allowed" if args.allow_weak_without_hash else "weak"
                )
                weak_hits += 1
            elif t.date_taken and (t.basename_lower, t.date_taken) in name_date_drives:
                ndk = (t.basename_lower, t.date_taken)
                drives, example_paths, match_type = (
                    name_date_drives[ndk],
                    name_date_paths.get(ndk, []),
                    "name_date",
                )
                safety = "name_date"
                name_date_hits += 1
            elif t.basename_lower in name_only_drives:
                drives, example_paths, match_type = (
                    name_only_drives[t.basename_lower],
                    name_only_paths.get(t.basename_lower, []),
                    "name_only",
                )
                safety = "name_only"
                name_only_hits += 1

        if not drives:
            missing.append(t.path)
            total_size_missing += t.size

        is_safe = classify_safe_to_delete(safety)
        if is_safe:
            safe_to_delete.append(t.path)
            total_size_safe += t.size

        if not is_safe and sizes_with_hashes:
            if match_type in ("strong", "weak"):
                if not target_hashes.get(t.path):
                    metadata_matched_but_not_hashed += 1
                    needs_hash.append(t.path)
                else:
                    no_verified_match.append(t.path)

        file_dir = t.path.parent
        if file_dir not in dir_stats:
            dir_stats[file_dir] = {
                "total": 0,
                "found": 0,
                "found_safe": 0,
                "size": 0,
                "size_safe": 0,
            }
        dir_stats[file_dir]["total"] += 1
        dir_stats[file_dir]["size"] += t.size
        if drives:
            dir_stats[file_dir]["found"] += 1
        if is_safe:
            dir_stats[file_dir]["found_safe"] += 1
            dir_stats[file_dir]["size_safe"] += t.size

        rows_out.append(
            {
                "target_path": str(t.path),
                "basename": t.basename_lower,
                "size_bytes": t.size,
                "date_taken": t.date_taken,
                "found": "yes" if drives else "no",
                "safe_to_delete": "yes" if is_safe else "no",
                "safety": safety,
                "match_type": match_type,
                "found_drives": ",".join(sorted(drives)),
                "example_backup_paths": " | ".join(example_paths[:3]),
                "target_hash": t.content_hash,
            }
        )

    if cache:
        cache.close()
    out_csv = Path(args.out_csv).expanduser().resolve()
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "target_path",
                "basename",
                "size_bytes",
                "date_taken",
                "found",
                "safe_to_delete",
                "safety",
                "match_type",
                "found_drives",
                "example_backup_paths",
                "target_hash",
            ],
        )
        w.writeheader()
        w.writerows(rows_out)

    for p, items in [
        (args.missing_list, missing),
        (args.safe_list, safe_to_delete),
        (args.needs_hash_list, needs_hash),
        (args.no_verified_match_list, no_verified_match),
        (args.hash_config_mismatch_list, hash_config_mismatch_list),
    ]:
        path = Path(p).expanduser().resolve()
        with path.open("w", encoding="utf-8") as f:
            for item in items:
                f.write(str(item) + "\n")

    if args.delete_script:
        ds_path = Path(args.delete_script).expanduser().resolve()
        with ds_path.open("w", encoding="utf-8") as f:
            f.write(
                "#!/bin/bash\n# Generated file - review carefully before running!\nset -euo pipefail\n\n"
            )
            for p in safe_to_delete:
                if "\n" in str(p) or "\r" in str(p):
                    continue
                escaped = str(p).replace("'", "'\\''")
                f.write(f"rm -i -- '{escaped}'\n")
        ds_path.chmod(0o755)

    if not args.quiet:
        print(
            f"\n=== Summary ===\nCSV report:    {out_csv}\nMissing list:  {args.missing_list} ({len(missing)} files, {human_readable_size(total_size_missing)})\nSafe list:     {args.safe_list} ({len(safe_to_delete)} files, {human_readable_size(total_size_safe)})"
        )
        if needs_hash:
            print(
                f"Needs hash:    {args.needs_hash_list} ({len(needs_hash)} files - rerun with --hash-mode compute)"
            )
        if hash_config_mismatch_list:
            print(
                f"Cfg mismatch:  {args.hash_config_mismatch_list} ({len(hash_config_mismatch_list)} files)"
            )
        if no_verified_match:
            print(
                f"No match:      {args.no_verified_match_list} ({len(no_verified_match)} files)"
            )
        print(
            f"\nVerified by hash:  {verified_hash_hits:,}\nStrong matches:    {strong_hits:,}\nWeak matches:      {weak_hits:,}\nName+date matches: {name_date_hits:,}\nName-only matches: {name_only_hits:,}\nMissing total:     {len(missing):,}"
        )
        if metadata_matched_but_not_hashed > 0:
            print(
                f"Note: {metadata_matched_but_not_hashed} files matched by metadata but weren't hashed (rerun with --hash-mode compute)."
            )

        safe_dirs = [d for d, s in dir_stats.items() if s["total"] == s["found_safe"]]
        if args.sort:
            safe_dirs.sort(key=lambda x: dir_stats[x]["size_safe"], reverse=True)
        else:
            safe_dirs.sort()
        if safe_dirs:
            print(f"\n=== Directories safe to delete ({len(safe_dirs)}) ===")
            for d in safe_dirs:
                rel = d.relative_to(target_dir) if d != target_dir else Path(".")
                print(
                    f"  {rel}/  ({dir_stats[d]['total']} files, {human_readable_size(dir_stats[d]['size_safe'])})"
                )
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
