#!/usr/bin/python3

# findphotodates.py - Version 1.4 (2026-03-24) - By Alan Rockefeller
# Generates inventory TSV with filepath, date_taken, size, mtime, GPS, location, and content_hash
# Hashing is off by default for fast indexing. Use --hash sample to enable, or --add-hashes to fill in later.

from pathlib import Path
import hashlib
import os
import sys
import subprocess
import argparse
import re
import time
from collections import Counter, defaultdict
from datetime import datetime
import tempfile
import csv
import urllib.request
import urllib.error
import json
import platform
import queue
import signal
import string
import threading
import types

# Optional fast hash (prefer over stdlib when available)
try:
    import blake3

    _BLAKE3_AVAILABLE = True
except ImportError:
    blake3 = None
    _BLAKE3_AVAILABLE = False

# Define supported photo file extensions
PHOTO_EXTENSIONS = {"jpg", "jpeg", "nef", "orf"}
# Define common video file extensions
VIDEO_EXTENSIONS = {"mp4", "mov", "avi", "mkv", "wmv", "flv", "webm", "m4v", "3gp"}
# Default extensions (both photos and videos)
DEFAULT_EXTENSIONS = PHOTO_EXTENSIONS.union(VIDEO_EXTENSIONS)

# TSV header identifier
TSV_HEADER = "# Generated by findphotodates.py"
TSV_COLUMNS = [
    "filepath",
    "date_taken",
    "size_bytes",
    "mtime_ns",
    "gps_lat",
    "gps_lon",
    "location",
    "content_hash",
]

# Default hash cache path
DEFAULT_HASH_CACHE_DIR = Path.home() / ".cache" / "findphotodates"
DEFAULT_HASH_CACHE_PATH = DEFAULT_HASH_CACHE_DIR / "hash_cache.sqlite"
HASH_CACHE_BATCH_COMMIT_EVERY = 1000


def parse_hash_args(
    hash_mode="off",
    sample_chunks=3,
    sample_chunk_mib=0.0625,
    hash_algo=None,
    hash_cache_path=None,
    no_hash_cache=False,
    hash_exts_str=None,
    quiet=False,
):
    """Parse and normalize hashing CLI options (unit-testable)."""
    mode = (hash_mode or "off").lower()
    if mode not in ("sample", "full", "off"):
        mode = "off"
    chunks = max(1, int(sample_chunks))
    chunk_mib = max(0.001, float(sample_chunk_mib))
    algo_override = None
    if hash_algo:
        algo_override = hash_algo.lower()
        if algo_override not in ("blake3", "blake2b", "sha256"):
            algo_override = None
    use_cache = not no_hash_cache
    path = hash_cache_path
    if use_cache and path is None:
        path = str(DEFAULT_HASH_CACHE_PATH)
    hash_exts = None
    if hash_exts_str and hash_exts_str.strip():
        hash_exts = frozenset(
            ext.strip().lower().lstrip(".")
            for ext in hash_exts_str.split(",")
            if ext.strip()
        )

    # Resolve algo for sample: prefer blake3, else blake2b (or sha256 if requested)
    if algo_override == "sha256":
        sample_algo = "sha256"
    elif _BLAKE3_AVAILABLE and (algo_override is None or algo_override == "blake3"):
        sample_algo = "blake3"
    elif algo_override == "blake2b":
        sample_algo = "blake2b"
    else:
        sample_algo = "blake2b"  # stdlib fallback

    # Resolve algo for full: blake3 or sha256
    if _BLAKE3_AVAILABLE and (algo_override is None or algo_override == "blake3"):
        full_algo = "blake3"
    elif algo_override == "sha256":
        full_algo = "sha256"
    elif algo_override == "blake2b":
        if not quiet:
            print(
                "Warning: blake2b is not supported for full hashes; using sha256 instead."
            )
        full_algo = "sha256"
    else:
        full_algo = "sha256"

    return types.SimpleNamespace(
        hash_mode=mode,
        sample_chunks=chunks,
        sample_chunk_mib=chunk_mib,
        hash_algo_override=algo_override,
        use_hash_cache=use_cache,
        hash_cache_path=path,
        hash_exts=hash_exts,
        sample_algo=sample_algo,
        full_algo=full_algo,
    )


def compute_samplehash_v1(path, chunk_bytes, num_chunks, algo="blake3"):
    """Compute a fast sample fingerprint from path (size + \0 + chunks).

    For small files (size <= num_chunks * chunk_bytes), hashes the whole file.
    Supports blake3, blake2b(digest_size=16), or sha256.
    Returns hex digest string or None on error.
    """
    try:
        st = os.stat(path)
        size = st.st_size
    except OSError:
        return None

    if algo == "blake3" and _BLAKE3_AVAILABLE:
        h = blake3.blake3()
    elif algo == "sha256":
        h = hashlib.sha256()
    else:
        h = hashlib.blake2b(digest_size=16)

    h.update(str(size).encode("ascii"))
    h.update(b"\0")

    total_sample_bytes = num_chunks * chunk_bytes
    small_file = size <= total_sample_bytes or size == 0

    try:
        with open(path, "rb") as f:
            if small_file:
                # Stream the entire file in chunks to avoid memory blow-up
                for data in iter(lambda: f.read(65536), b""):
                    h.update(data)
            else:
                # Distribute offsets: first 0, last size-chunk_bytes, middle ones spread evenly
                chunks_to_read = []
                end_offset = max(0, size - chunk_bytes)
                for i in range(num_chunks):
                    if i == 0:
                        offset = 0
                    elif i == num_chunks - 1:
                        offset = end_offset
                    else:
                        offset = (
                            (i * end_offset) // (num_chunks - 1)
                            if num_chunks > 1
                            else 0
                        )
                    offset = max(0, min(offset, end_offset))
                    chunks_to_read.append(offset)

                # Deduplicate and sort offsets
                for offset in sorted(set(chunks_to_read)):
                    f.seek(offset)
                    data = f.read(chunk_bytes)
                    if data:
                        h.update(data)
        return h.hexdigest()
    except OSError:
        return None


def compute_fullhash(path, algo="blake3"):
    """Compute full-file hash. algo is 'blake3' or 'sha256'. Returns hex digest or None."""
    if algo == "blake3" and _BLAKE3_AVAILABLE:
        try:
            with open(path, "rb") as f:
                h = blake3.blake3()
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
                return h.hexdigest()
        except OSError:
            return None
    else:
        try:
            h = hashlib.sha256()
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            return h.hexdigest()
        except OSError:
            return None


def open_sqlite_cache(cache_path, debug=False):
    """Create cache dir if needed, open SQLite connection, ensure table exists. Returns connection or None on error."""
    try:
        import sqlite3
    except ImportError:
        if debug:
            print("Debug: sqlite3 module not found.")
        return None
    try:
        Path(cache_path).parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(cache_path)
        conn.execute("PRAGMA journal_mode=WAL;")
        conn.execute("PRAGMA synchronous=NORMAL;")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS hash_cache (
                path TEXT NOT NULL,
                size_bytes INTEGER NOT NULL,
                mtime_ns INTEGER NOT NULL,
                hash_mode TEXT NOT NULL,
                chunk_bytes INTEGER NOT NULL,
                chunks INTEGER NOT NULL,
                algo TEXT NOT NULL,
                digest TEXT NOT NULL,
                PRIMARY KEY (path, size_bytes, mtime_ns, hash_mode, chunk_bytes, chunks, algo)
            )
        """
        )
        conn.commit()
        return conn
    except Exception as e:
        if debug:
            print(f"Debug: Failed to open hash cache at {cache_path}: {e}")
        return None


def get_cached_hash(
    conn, path, size_bytes, mtime_ns, hash_mode, chunk_bytes, chunks, algo
):
    """Return cached digest string if present, else None."""
    if conn is None:
        return None
    try:
        row = conn.execute(
            """SELECT digest FROM hash_cache
               WHERE path = ? AND size_bytes = ? AND mtime_ns = ?
                 AND hash_mode = ? AND chunk_bytes = ? AND chunks = ? AND algo = ?""",
            (path, size_bytes, mtime_ns, hash_mode, chunk_bytes, chunks, algo),
        ).fetchone()
        return row[0] if row else None
    except Exception:
        return None


def put_cached_hash(
    conn,
    path,
    size_bytes,
    mtime_ns,
    hash_mode,
    chunk_bytes,
    chunks,
    algo,
    digest,
    pending_counter=None,
):
    """Store digest in cache. If pending_counter is a list [n], batch-commit every HASH_CACHE_BATCH_COMMIT_EVERY."""
    if conn is None:
        return
    try:
        conn.execute(
            """INSERT OR REPLACE INTO hash_cache
               (path, size_bytes, mtime_ns, hash_mode, chunk_bytes, chunks, algo, digest)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (path, size_bytes, mtime_ns, hash_mode, chunk_bytes, chunks, algo, digest),
        )
        if pending_counter is not None:
            pending_counter[0] += 1
            if pending_counter[0] >= HASH_CACHE_BATCH_COMMIT_EVERY:
                conn.commit()
                pending_counter[0] = 0
        else:
            conn.commit()
    except Exception:
        pass


def get_content_hash(
    key_path, size_bytes, mtime_ns, hash_options, hash_conn, pending_counter=None
):
    """Return content_hash for a file: from cache or compute. Returns '' if hashing off or restricted by ext."""
    if hash_options.hash_mode == "off":
        return ""
    ext = (os.path.splitext(key_path)[1] or "").lstrip(".").lower()
    if hash_options.hash_exts is not None and ext not in hash_options.hash_exts:
        return ""
    chunk_bytes = int(hash_options.sample_chunk_mib * 1024 * 1024)
    chunk_bytes = max(1, chunk_bytes)
    if hash_options.hash_mode == "sample":
        cached = get_cached_hash(
            hash_conn,
            key_path,
            size_bytes,
            mtime_ns,
            "sample",
            chunk_bytes,
            hash_options.sample_chunks,
            hash_options.sample_algo,
        )
        if cached is not None:
            return cached
        digest = compute_samplehash_v1(
            key_path,
            chunk_bytes,
            hash_options.sample_chunks,
            algo=hash_options.sample_algo,
        )
        if digest and hash_conn:
            put_cached_hash(
                hash_conn,
                key_path,
                size_bytes,
                mtime_ns,
                "sample",
                chunk_bytes,
                hash_options.sample_chunks,
                hash_options.sample_algo,
                digest,
                pending_counter=pending_counter,
            )
        return digest or ""
    else:
        cached = get_cached_hash(
            hash_conn,
            key_path,
            size_bytes,
            mtime_ns,
            "full",
            0,
            0,
            hash_options.full_algo,
        )
        if cached is not None:
            return cached
        digest = compute_fullhash(key_path, hash_options.full_algo)
        if digest and hash_conn:
            put_cached_hash(
                hash_conn,
                key_path,
                size_bytes,
                mtime_ns,
                "full",
                0,
                0,
                hash_options.full_algo,
                digest,
                pending_counter=pending_counter,
            )
        return digest or ""


def is_supported_file(filename, extensions):
    """Check if a file has a supported extension."""
    return any(filename.lower().endswith(f".{ext}") for ext in extensions)


def find_files(directory, extensions):
    """Recursively find all files with the specified extensions in the given directory."""
    for root, _, files in os.walk(directory):
        for file in files:
            if is_supported_file(file, extensions):
                yield os.path.join(root, file)


class ExifToolPersistent:
    """Persistent exiftool process using -stay_open for high throughput."""

    _SENTINEL = "{ready}\n"
    _TAGS = [
        "-DateTimeOriginal",
        "-CreateDate",
        "-MediaCreateDate",
        "-GPSLatitude",
        "-GPSLongitude",
    ]
    _DATE_TAG_COUNT = 3  # first 3 are date tags

    def __init__(self):
        self._proc = None

    def start(self):
        if self._proc is not None:
            return
        try:
            self._proc = subprocess.Popen(
                ["exiftool", "-stay_open", "True", "-@", "-"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
            )
        except FileNotFoundError as e:
            raise FileNotFoundError(
                "Exiftool is required but was not found. Please install it."
            ) from e

    def stop(self):
        if self._proc is None:
            return
        try:
            self._proc.stdin.write("-stay_open\nFalse\n")
            self._proc.stdin.flush()
            self._proc.wait(timeout=5)
        except Exception:
            try:
                self._proc.kill()
            except Exception:
                pass
        self._proc = None

    def query(self, filepath):
        """Query a single file. Returns (date, gps_lat, gps_lon)."""
        if self._proc is None:
            self.start()
        proc = self._proc
        try:
            # Write args: one per line, then -execute to signal end of batch
            args = ["-n", "-f", "-s", "-s", "-s"] + self._TAGS + [filepath]
            proc.stdin.write("\n".join(args) + "\n-execute\n")
            proc.stdin.flush()
        except (BrokenPipeError, OSError):
            # Process died — restart and retry once
            self._proc = None
            self.start()
            proc = self._proc
            args = ["-n", "-f", "-s", "-s", "-s"] + self._TAGS + [filepath]
            proc.stdin.write("\n".join(args) + "\n-execute\n")
            proc.stdin.flush()

        # Read lines until we see the sentinel
        lines = []
        while True:
            line = proc.stdout.readline()
            if not line:
                # EOF — process died
                self._proc = None
                return None, None, None
            if line.strip().startswith("{ready"):
                break
            lines.append(line.strip())

        return self._parse_lines(lines)

    def _parse_lines(self, lines):
        date = None
        if len(lines) >= self._DATE_TAG_COUNT:
            for i in range(self._DATE_TAG_COUNT):
                val = lines[i].strip()
                if val and val != "-":
                    if re.match(r"\d{4}:\d{2}:\d{2} \d{2}:\d{2}:\d{2}", val):
                        date = val
                        break
        gps_lat = None
        gps_lon = None
        if len(lines) >= self._DATE_TAG_COUNT + 2:
            lat = lines[self._DATE_TAG_COUNT].strip()
            lon = lines[self._DATE_TAG_COUNT + 1].strip()
            if lat and lat != "-":
                gps_lat = lat
            if lon and lon != "-":
                gps_lon = lon
        return date, gps_lat, gps_lon

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *exc):
        self.stop()


def get_photo_data(filepath, _exiftool=None):
    """Use exiftool to get the date and GPS data of a photo/video.

    If _exiftool (an ExifToolPersistent instance) is provided, uses the
    persistent process. Otherwise falls back to a one-shot subprocess call.
    """
    if _exiftool is not None:
        return _exiftool.query(filepath)

    # Legacy one-shot fallback
    try:
        date_tags = ["-DateTimeOriginal", "-CreateDate", "-MediaCreateDate"]
        tags = date_tags + ["-GPSLatitude", "-GPSLongitude"]

        result = subprocess.run(
            ["exiftool", "-n", "-f", *tags, "-s", "-s", "-s", filepath],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )

        if result.returncode == 0:
            lines = result.stdout.splitlines()
            date = None
            if len(lines) >= len(date_tags):
                for i in range(len(date_tags)):
                    line = lines[i].strip()
                    if line and line != "-":
                        if re.match(r"\d{4}:\d{2}:\d{2} \d{2}:\d{2}:\d{2}", line):
                            date = line
                            break
            gps_lat = None
            gps_lon = None
            if len(lines) >= len(date_tags) + 2:
                gps_lat_str = lines[len(date_tags)].strip()
                gps_lon_str = lines[len(date_tags) + 1].strip()
                if gps_lat_str and gps_lat_str != "-":
                    gps_lat = gps_lat_str
                if gps_lon_str and gps_lon_str != "-":
                    gps_lon = gps_lon_str
            return date, gps_lat, gps_lon
        else:
            return None, None, None
    except FileNotFoundError as e:
        raise FileNotFoundError(
            "Exiftool is required but was not found. Please install it."
        ) from e


# Global variables for geolocation rate limiting and coordinate caching
_last_geolocate_time = 0
_coord_cache = {}  # (round(lat,5), round(lon,5)) -> location


def geolocate(lat, lon):
    """Convert GPS coordinates to a human-readable location using Nominatim API."""
    global _last_geolocate_time, _coord_cache

    if not lat or not lon:
        return None

    try:
        # Convert to float to ensure valid coordinates
        lat_float = float(lat)
        lon_float = float(lon)
    except (ValueError, TypeError):
        return f"{lat}, {lon}"

    # Check coordinate cache (round to 5 decimal places ~1.1m precision)
    cache_key = (round(lat_float, 5), round(lon_float, 5))
    if cache_key in _coord_cache:
        return _coord_cache[cache_key]

    # Rate limiting: wait at least 1 second since last request
    current_time = time.time()
    time_since_last = current_time - _last_geolocate_time
    if time_since_last < 1.0:
        time.sleep(1.0 - time_since_last)

    try:
        # Build Nominatim reverse geocoding URL with addressdetails=1
        url = f"https://nominatim.openstreetmap.org/reverse?format=json&lat={lat_float}&lon={lon_float}&addressdetails=1"

        # Create request with proper User-Agent header (required by Nominatim)
        req = urllib.request.Request(url)
        req.add_header(
            "User-Agent",
            "findphotodates.py/1.4 (https://github.com/alanrockefeller/findphotodates.py)",
        )

        # Make the request
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode())

            # Update last request time
            _last_geolocate_time = time.time()

            # Extract location from response - prefer address components over display_name
            location = None
            if "address" in data:
                addr = data["address"]
                parts = []
                # Build location from address components in order of specificity
                for key in ["city", "town", "village", "county", "state", "country"]:
                    if key in addr:
                        parts.append(addr[key])
                if parts:
                    location = ", ".join(parts)

            # Fallback to display_name if address components didn't work
            if not location and "display_name" in data:
                location = data["display_name"]

            # Fallback to coordinates if no location found
            if not location:
                location = f"{lat_float}, {lon_float}"

            # Cache the result
            _coord_cache[cache_key] = location
            return location

    except urllib.error.HTTPError as e:
        # Handle 429 (rate limit) with longer backoff
        if e.code == 429:
            _last_geolocate_time = time.time() + 5  # Wait 5 seconds before next attempt
        else:
            _last_geolocate_time = time.time()
        # Don't cache fallback coordinates - allow retry on next run
        return f"{lat_float}, {lon_float}"
    except Exception:
        # Don't cache fallback coordinates - allow retry on next run
        _last_geolocate_time = time.time()
        return f"{lat_float}, {lon_float}"


def is_coordinate_string(location):
    """Check if location string looks like raw coordinates (e.g., "37.7, -122.4")."""
    if not location:
        return False
    # Match pattern: optional negative, digits, optional decimal, comma, optional space, optional negative, digits, optional decimal
    return bool(re.match(r"^-?\d+(\.\d+)?,\s*-?\d+(\.\d+)?$", location.strip()))


def load_cache(output_file, debug=False):
    """Load existing TSV cache if it exists and has the expected header.

    Accepts both current columns (with content_hash) and legacy 7-column TSV.
    Skips all leading # lines, then uses the first non-# line as the header row.
    """
    cache = {}
    if not os.path.exists(output_file):
        return cache

    try:
        with open(output_file, "r", encoding="utf-8", newline="") as f:
            # Consume all leading # lines
            first_non_comment = None
            while True:
                line = f.readline()
                if not line:
                    break
                line = line.rstrip("\n\r")
                if not line:
                    continue
                if line.startswith("#"):
                    continue

                # First non-# line
                first_non_comment = line
                break

            if not first_non_comment:
                return cache

            # Parse column header with csv so quoted tabs are handled
            fieldnames = next(csv.reader([first_non_comment], delimiter="\t"))
            if not fieldnames:
                return cache

            # Sanity check: require at least 'filepath' and 'date_taken'
            if "filepath" not in fieldnames or "date_taken" not in fieldnames:
                if debug:
                    print(
                        f"Debug: Cache file {output_file} missing required columns. Found: {fieldnames}"
                    )
                return cache

            expected = list(TSV_COLUMNS)
            legacy = expected[:-1]
            if fieldnames != expected and fieldnames != legacy:
                if debug:
                    print(
                        f"Debug: Cache file {output_file} header mismatch. Found: {fieldnames}"
                    )
                return cache

            for row in csv.DictReader(
                f, fieldnames=fieldnames, delimiter="\t", restval=""
            ):
                filepath = row.get("filepath", "")
                if filepath:
                    try:
                        # Normalize to real path (follows symlinks) for cache key consistency
                        abs_filepath = os.path.realpath(filepath)
                        size_bytes = int(row.get("size_bytes", "0"))
                        mtime_ns = int(row.get("mtime_ns", "0"))
                        date_taken = row.get("date_taken", "") or None
                        gps_lat = row.get("gps_lat", "") or None
                        gps_lon = row.get("gps_lon", "") or None
                        location = row.get("location", "") or None

                        # Treat coordinate strings as missing location (allows retry)
                        if location and is_coordinate_string(location):
                            location = None

                        cache[abs_filepath] = {
                            "size_bytes": size_bytes,
                            "mtime_ns": mtime_ns,
                            "date_taken": date_taken,
                            "gps_lat": gps_lat,
                            "gps_lon": gps_lon,
                            "location": location,
                        }
                    except (ValueError, KeyError):
                        continue
    except (IOError, UnicodeDecodeError) as e:
        if debug:
            print(f"Debug: Error reading cache file {output_file}: {e}")
        return cache

    return cache


def write_dates_to_file_atomic(
    output_file, photo_data, inventory_root=None, hash_options=None, old_format=False
):
    """Write photo data to file atomically.

    If old_format is True, writes legacy line-based format: ./relative/path: YYYY:MM:DD HH:MM:SS
    (no hashes). Otherwise writes NEW TSV format with optional header comments and content_hash column.
    photo_data: list of 8-tuples (filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location, content_hash)
    for NEW format; for OLD format the 8th element is ignored.
    """
    output_dir = os.path.dirname(os.path.abspath(output_file))
    if not output_dir:
        output_dir = "."
    suffix = ".txt" if old_format else ".tsv"
    fd, temp_file = tempfile.mkstemp(
        dir=output_dir, suffix=suffix, prefix=".findphotodates_"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            sorted_data = sorted(photo_data, key=lambda r: r[0])
            if old_format:
                # OLD format: ./relative/path: YYYY:MM:DD HH:MM:SS (no hashes)
                root = (
                    (os.path.abspath(inventory_root) + os.sep) if inventory_root else ""
                )
                for row in sorted_data:
                    filepath = row[0]
                    date_taken = (row[1] or "").strip()
                    if not date_taken:
                        continue
                    if root and filepath.startswith(root):
                        rel = "./" + filepath[len(root) :].replace(os.sep, "/")
                    else:
                        rel = filepath
                    f.write(f"{rel}: {date_taken}\n")
            else:
                # NEW format: comment block, then TSV with content_hash column
                if inventory_root is not None:
                    f.write(f"# inventory_root={os.path.abspath(inventory_root)}\n")
                if hash_options is not None:
                    f.write(f"# hash_mode={hash_options.hash_mode}\n")
                    if hash_options.hash_mode == "sample":
                        f.write("# content_hash_format=samplehash_v1\n")
                        f.write(
                            f"# samplehash_v1 algo={hash_options.sample_algo} chunks={hash_options.sample_chunks} chunk_mib={hash_options.sample_chunk_mib:g}\n"
                        )
                    elif hash_options.hash_mode == "full":
                        # full_algo is blake3 or sha256 (no blake2b for full)
                        f.write("# content_hash_format=fullhash_v1\n")
                        f.write(f"# fullhash algo={hash_options.full_algo}\n")
                f.write(TSV_HEADER + "\n")
                writer = csv.writer(f, delimiter="\t", quoting=csv.QUOTE_MINIMAL)
                writer.writerow(TSV_COLUMNS)
                for row in sorted_data:
                    filepath = row[0]
                    date_taken = row[1] if len(row) > 1 else ""
                    size_bytes = row[2] if len(row) > 2 else 0
                    mtime_ns = row[3] if len(row) > 3 else 0
                    gps_lat = row[4] if len(row) > 4 else ""
                    gps_lon = row[5] if len(row) > 5 else ""
                    location = row[6] if len(row) > 6 else ""
                    content_hash = row[7] if len(row) > 7 else ""
                    writer.writerow(
                        [
                            filepath,
                            date_taken or "",
                            str(size_bytes),
                            str(mtime_ns),
                            gps_lat or "",
                            gps_lon or "",
                            location or "",
                            content_hash or "",
                        ]
                    )
        os.replace(temp_file, output_file)
    except Exception:
        try:
            os.unlink(temp_file)
        except Exception:
            pass
        raise


def summarize_results(photo_data, file_counts, quiet, debug=False):
    """Print a summary of results."""
    if quiet:
        return

    print("\nSummary of Results:\n")

    # Print counts by file type
    print("Files found:")
    for ext, count in sorted(file_counts.items()):
        print(f"  {ext.upper()}: {count}")

    # Calculate date summaries
    date_counter = Counter()
    for entry in photo_data:
        # Entry is a tuple: (filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location, content_hash)
        date_str = entry[1] if len(entry) > 1 else None

        # Skip None or empty dates
        if not date_str:
            continue

        try:
            # Parse exiftool date format: YYYY:MM:DD HH:MM:SS
            dt = datetime.strptime(date_str, "%Y:%m:%d %H:%M:%S")
            day_key = dt.strftime("%Y-%m-%d")
            date_counter[day_key] += 1
        except (ValueError, AttributeError, TypeError) as e:
            # Gracefully skip invalid dates
            if debug:
                print(f"Warning: Could not parse date '{date_str}': {str(e)}")
            continue

    # Determine file type label for summary
    file_type_label = "Media"
    if all(ext in VIDEO_EXTENSIONS for ext in file_counts):
        file_type_label = "Videos"
    elif all(ext in PHOTO_EXTENSIONS for ext in file_counts):
        file_type_label = "Photos"

    if len(date_counter) <= 20:
        print(f"\n{file_type_label} Taken per day:")
        for day, count in sorted(date_counter.items()):
            print(f"  {day}: {count}")
    else:
        month_counter = defaultdict(int)
        for day_key in date_counter:
            try:
                # Parse the day_key (YYYY-MM-DD) to get year-month
                dt = datetime.strptime(day_key, "%Y-%m-%d")
                year_month_key = dt.strftime("%Y-%m")
                month_counter[year_month_key] += date_counter[day_key]
            except (ValueError, AttributeError) as e:
                # Gracefully skip invalid day keys
                if debug:
                    print(
                        f"Warning: Could not extract year-month from '{day_key}': {str(e)}"
                    )
                continue
        print(f"\n{file_type_label} Taken per Month:")
        for year_month, count in sorted(month_counter.items()):
            print(f"  {year_month}: {count}")


# Path expansion helper
def _expand_path(p: str) -> str:
    """Expand user home directory and convert to absolute path."""
    return os.path.abspath(os.path.expanduser(p))


# Config file handling
CONFIG_FILE = Path.home() / ".findphotodates.config.json"


def load_config():
    """Load configuration from JSON file."""
    if not CONFIG_FILE.exists():
        return {
            "_comment": "Saved scan configurations for findphotodates.py. Edit cautiously; JSON comments are stored here.",
            "saved_scans": [],
        }

    try:
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)
        # Ensure required structure
        if "saved_scans" not in config:
            config["saved_scans"] = []
        return config
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in config file {CONFIG_FILE}: {e}")
        print("Please fix or remove the config file and try again.")
        exit(1)
    except Exception as e:
        print(f"Error: Failed to read config file {CONFIG_FILE}: {e}")
        exit(1)


def save_config(config):
    """Save configuration to JSON file atomically."""
    try:
        # Ensure directory exists
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)

        # Create temp file in same directory
        fd, temp_file = tempfile.mkstemp(
            dir=CONFIG_FILE.parent, suffix=".json", prefix=".findphotodates_"
        )

        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                json.dump(config, f, indent=2, ensure_ascii=False, sort_keys=True)

            # Atomically replace
            os.replace(temp_file, CONFIG_FILE)
        except Exception:
            try:
                os.unlink(temp_file)
            except Exception:
                pass
            raise
    except Exception as e:
        print(f"Error: Failed to write config file {CONFIG_FILE}: {e}")
        exit(1)


def detect_drive_root(directory_abs):
    """Detect the drive root for a given absolute directory path."""
    directory_abs = os.path.abspath(directory_abs)
    system = platform.system()

    # Try to find mount points
    if system == "Darwin":  # macOS
        # Check if under /Volumes
        if directory_abs.startswith("/Volumes/"):
            parts = directory_abs.split("/")
            if len(parts) >= 3:
                drive_root = "/" + "/".join(parts[1:3])  # /Volumes/VolumeName
                path_relative = "/".join(parts[3:]) if len(parts) > 3 else ""
                return drive_root, path_relative

    elif system == "Linux":
        # Check /media (typically /media/<user>/<drive> - two levels deep)
        if directory_abs.startswith("/media/"):
            parts = directory_abs.split("/")
            # /media/<user>/<drive> - drive is at index 3
            if len(parts) >= 4:
                drive_root = "/" + "/".join(parts[1:4])  # /media/user/drive
                path_relative = "/".join(parts[4:]) if len(parts) > 4 else ""
                return drive_root, path_relative

        # Check /run/media (typically /run/media/<user>/<drive> - two levels deep)
        if directory_abs.startswith("/run/media/"):
            parts = directory_abs.split("/")
            # /run/media/<user>/<drive> - drive is at index 4
            if len(parts) >= 5:
                drive_root = "/" + "/".join(parts[1:5])  # /run/media/user/drive
                path_relative = "/".join(parts[5:]) if len(parts) > 5 else ""
                return drive_root, path_relative

        # Check /mnt (typically /mnt/<drive> - one level deep)
        if directory_abs.startswith("/mnt/"):
            parts = directory_abs.split("/")
            # /mnt/<drive> - drive is at index 2
            if len(parts) >= 3:
                drive_root = "/" + "/".join(parts[1:3])  # /mnt/drive
                path_relative = "/".join(parts[3:]) if len(parts) > 3 else ""
                return drive_root, path_relative

    elif system == "Windows":
        # On Windows, drive root is typically C:\, D:\, etc.
        if len(directory_abs) >= 2 and directory_abs[1] == ":":
            drive_root = directory_abs[:2] + "\\"
            path_relative = (
                directory_abs[3:].replace("\\", "/") if len(directory_abs) > 2 else ""
            )
            return drive_root, path_relative

    # Fallback: use directory itself as root
    return directory_abs, ""


def get_drive_hint(drive_root):
    """Extract a hint value from drive root (e.g., volume name)."""
    if not drive_root:
        return ""

    # Special case for Windows drive roots (C:\, D:\, etc.)
    if platform.system() == "Windows" and len(drive_root) >= 2 and drive_root[1] == ":":
        # Use os.path.splitdrive to get just the letter
        drive, _ = os.path.splitdrive(drive_root)
        return drive.rstrip(":")  # Return just "C", "D", etc.

    # Extract last component
    if os.path.sep in drive_root:
        parts = drive_root.rstrip(os.path.sep).split(os.path.sep)
        return parts[-1] if parts else ""
    elif ":" in drive_root:
        # Windows drive letter (fallback)
        return drive_root.rstrip(":\\")
    return drive_root


def resolve_saved_directory(entry):
    """Resolve a saved scan entry to a current directory path."""
    # Try directory_abs first
    if entry.get("directory_abs") and os.path.exists(entry["directory_abs"]):
        return entry["directory_abs"]

    # Try to reconstruct using path_relative + drive root detection
    path_relative = entry.get("path_relative", "")
    drive_hint = entry.get("drive_hint", {}).get("value", "")

    system = platform.system()
    candidate_roots = []

    if system == "Darwin":  # macOS
        volumes_dir = Path("/Volumes")
        if volumes_dir.exists():
            for vol in volumes_dir.iterdir():
                if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                    candidate_roots.append(str(vol))

    elif system == "Linux":
        # Handle /media/<user>/<drive> (two levels deep)
        media_path = Path("/media")
        if media_path.exists():
            for user_dir in media_path.iterdir():
                if user_dir.is_dir():
                    for vol in user_dir.iterdir():
                        if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                            candidate_roots.append(str(vol))

        # Handle /run/media/<user>/<drive> (two levels deep)
        run_media_path = Path("/run/media")
        if run_media_path.exists():
            for user_dir in run_media_path.iterdir():
                if user_dir.is_dir():
                    for vol in user_dir.iterdir():
                        if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                            candidate_roots.append(str(vol))

        # Handle /mnt/<drive> (one level deep)
        mnt_path = Path("/mnt")
        if mnt_path.exists():
            for vol in mnt_path.iterdir():
                if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                    candidate_roots.append(str(vol))

    elif system == "Windows":
        # Check all drive letters
        for letter in string.ascii_uppercase:
            drive = f"{letter}:\\"
            if os.path.exists(drive):
                if not drive_hint or drive_hint.upper() == letter:
                    candidate_roots.append(drive)

    # Try each candidate root
    for root in candidate_roots:
        if path_relative:
            # Normalize path separators for current platform
            normalized_relative = path_relative.replace("/", os.path.sep).replace(
                "\\", os.path.sep
            )
            candidate = os.path.join(root, normalized_relative)
        else:
            candidate = root

        if os.path.exists(candidate) and os.path.isdir(candidate):
            return candidate

    # Fallback: try directory_abs even if it doesn't exist (might be temporarily unmounted)
    return entry.get("directory_abs")


def _format_duration(seconds):
    """Format seconds into a human-readable duration string."""
    if seconds > 3600:
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        return f"{hours}h {minutes}m"
    elif seconds > 60:
        minutes = int(seconds // 60)
        secs = int(seconds % 60)
        return f"{minutes}m {secs}s"
    else:
        return f"{seconds:.1f}s"


def _check_drive_disconnect(
    error, output, photo_data, inventory_root, hash_options, old_format, cleanup_fn
):
    """Check for drive disconnect errors and save progress. Returns True if disconnect detected."""
    if any(
        err in str(error).lower()
        for err in ["no such file", "input/output error", "stale file handle"]
    ):
        print("\n\nWARNING: Drive may be disconnected! Saving progress...")
        write_dates_to_file_atomic(
            output,
            photo_data,
            inventory_root=inventory_root,
            hash_options=hash_options,
            old_format=old_format,
        )
        print(f"Saved {len(photo_data)} files to '{output}'")
        print("Reconnect drive and run again to resume.")
        cleanup_fn()
        return True
    return False


# ---------------------------------------------------------------------------
# Background file discovery producer
# ---------------------------------------------------------------------------

_DISCOVERY_QUEUE_SIZE = 10_000  # bounded queue: ~1 MB of path strings max


class _DiscoveryState:
    """Shared state between discovery producer thread and consumer."""

    __slots__ = ("discovered", "total", "done", "error")

    def __init__(self):
        self.discovered = (
            0  # files found so far (written by producer, read by consumer)
        )
        self.total = 0  # final count (valid only after done is set)
        self.done = threading.Event()
        self.error = None  # exception from producer, if any


def _discovery_producer(file_queue, directory, extensions, state):
    """Producer thread: walk directory, enqueue matching paths, signal done."""
    try:
        count = 0
        for filepath in find_files(directory, extensions):
            file_queue.put(filepath)  # blocks if queue full — backpressure
            count += 1
            state.discovered = count  # atomic on CPython (int store)
        state.total = count
    except Exception as e:
        state.error = e
    finally:
        state.done.set()
        # Push sentinel so consumer doesn't block forever on get()
        try:
            file_queue.put(None, timeout=5)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Rolling-rate tracker for ETA
# ---------------------------------------------------------------------------


class _RateTracker:
    """Tracks processing rate over a rolling window for smooth ETA."""

    def __init__(self, window_seconds=30.0):
        self._window = window_seconds
        self._samples = []  # list of (timestamp, cumulative_count)

    def record(self, timestamp, count):
        self._samples.append((timestamp, count))
        # Trim samples older than window (keep one before window for interpolation)
        cutoff = timestamp - self._window
        first_in_window = 0
        for i, (t, _) in enumerate(self._samples):
            if t >= cutoff:
                first_in_window = max(0, i - 1)
                break
        if first_in_window > 0:
            self._samples = self._samples[first_in_window:]

    def rate(self):
        """Return files/sec over the rolling window, or None if insufficient data."""
        if len(self._samples) < 2:
            return None
        t0, c0 = self._samples[0]
        t1, c1 = self._samples[-1]
        dt = t1 - t0
        if dt < 1.0:
            return None
        return (c1 - c0) / dt


def _format_eta(remaining_files, rate):
    """Format ETA string from remaining files and rate. Returns None if not computable."""
    if rate is None or rate <= 0 or remaining_files <= 0:
        return None
    secs = remaining_files / rate
    if secs > 86400:
        days = int(secs // 86400)
        hours = int((secs % 86400) // 3600)
        return f"{days}d {hours}h"
    elif secs > 3600:
        hours = int(secs // 3600)
        minutes = int((secs % 3600) // 60)
        return f"{hours}h {minutes}m"
    elif secs > 60:
        minutes = int(secs // 60)
        s = int(secs % 60)
        return f"{minutes}m {s}s"
    else:
        return f"{int(secs)}s"


# ---------------------------------------------------------------------------
# Main scan loop
# ---------------------------------------------------------------------------


def run_scan(
    directory,
    output,
    extensions,
    locate=False,
    quiet=False,
    debug=False,
    hash_options=None,
    old_format=False,
):
    """Run a scan on the specified directory."""
    if hash_options is None:
        hash_options = parse_hash_args(quiet=quiet)

    if old_format:
        # Force hashing off for old format
        hash_options.hash_mode = "off"

    hash_conn = (
        open_sqlite_cache(hash_options.hash_cache_path, debug=debug)
        if (hash_options.use_hash_cache and hash_options.hash_mode != "off")
        else None
    )
    hash_cache_pending = [0] if hash_conn else None

    if not quiet and hash_options.hash_mode != "off":
        msg = f"Hashing enabled ({hash_options.hash_mode})"
        if hash_options.hash_mode == "sample":
            msg += f": {hash_options.sample_chunks}x{hash_options.sample_chunk_mib:g} MiB {hash_options.sample_algo}"
        else:
            msg += f": {hash_options.full_algo}"
        msg += ". First run may be slower; results cached in SQLite."
        print(msg)

    inventory_root = os.path.abspath(directory)
    # Ensure the directory exists
    if not os.path.exists(directory):
        if not quiet:
            print(f"Error: Directory '{directory}' does not exist.")
        return False

    if not quiet:
        print(
            f"Searching for files in '{directory}' with extensions: {', '.join(extensions)}..."
        )

    if not quiet and old_format and output.lower().endswith(".tsv"):
        print(
            "Warning: Using .tsv extension for legacy line-based format. Recommended: .txt"
        )

    # Load existing cache
    cache = load_cache(output, debug=debug)
    if not quiet and cache:
        print(f"Loaded {len(cache)} entries from cache.")

    # Redirect warnings to a unique log file per run
    error_log_path = os.path.join(
        tempfile.gettempdir(),
        f"findphotodates.error.{os.getpid()}.{int(time.time())}.log",
    )
    photo_data = []
    file_counts = Counter()
    cached_count = 0
    processed_count = 0

    def cleanup_all():
        if hash_conn is not None:
            try:
                if hash_cache_pending is not None and hash_cache_pending[0] > 0:
                    hash_conn.commit()
                hash_conn.close()
            except Exception:
                pass

    exiftool = ExifToolPersistent()

    # --- Start background file discovery ---
    file_queue = queue.Queue(maxsize=_DISCOVERY_QUEUE_SIZE)
    discovery = _DiscoveryState()
    producer = threading.Thread(
        target=_discovery_producer,
        args=(file_queue, directory, extensions, discovery),
        daemon=True,
    )
    producer.start()

    interrupted = False

    with open(error_log_path, "w") as error_log:
        try:
            exiftool.start()
        except FileNotFoundError:
            print("Error: ExifTool is required but was not found.")
            discovery.done.wait(timeout=2)
            return False

        start_time = time.time()
        last_save_time = start_time
        last_progress_time = start_time
        rate_tracker = _RateTracker(window_seconds=30.0)
        discovery_complete = (
            False  # local flag: have we printed the discovery-done message?
        )
        total_files = 0  # set once discovery finishes

        try:
            while True:
                # --- Get next file from queue ---
                try:
                    file = file_queue.get(timeout=1.0)
                except queue.Empty:
                    # No file ready yet.
                    if not quiet:
                        current_time = time.time()
                        if current_time - last_progress_time >= 2.0:
                            elapsed = current_time - start_time
                            total_seen = cached_count + processed_count
                            rate = rate_tracker.rate()
                            rate_str = f"{rate:.0f} files/sec" if rate else "..."
                            print(
                                f"Discovering... {discovery.discovered:,} found | "
                                f"Processed {total_seen:,} ({cached_count:,} cached) — "
                                f"{rate_str} [{_format_duration(elapsed)}]",
                                end="\r",
                            )
                            last_progress_time = current_time
                    if discovery.done.is_set() and file_queue.empty():
                        # Producer finished and queue is drained
                        if discovery.error is not None:
                            print(f"\nError during file discovery: {discovery.error}")
                        break
                    continue

                if file is None:
                    # Sentinel: discovery finished
                    break

                ext = file.rsplit(".", 1)[-1].lower() if "." in file else ""
                file_counts[ext] += 1

                # Check if discovery just completed (for progress phase transition)
                if not discovery_complete and discovery.done.is_set():
                    discovery_complete = True
                    total_files = discovery.total
                    if not quiet:
                        print(
                            f"\nDiscovery complete: {total_files:,} files found.                              "
                        )

                try:
                    out_path = os.path.abspath(file)
                    key_path = os.path.realpath(out_path)
                    stat_info = os.stat(key_path)
                    size_bytes = stat_info.st_size
                    mtime_ns = stat_info.st_mtime_ns

                    # Check TSV cache
                    cached_entry = cache.get(key_path)
                    if (
                        cached_entry
                        and cached_entry["size_bytes"] == size_bytes
                        and cached_entry["mtime_ns"] == mtime_ns
                    ):
                        date_taken = cached_entry["date_taken"]
                        gps_lat = cached_entry.get("gps_lat")
                        gps_lon = cached_entry.get("gps_lon")
                        location = cached_entry.get("location")

                        if locate and gps_lat and gps_lon:
                            if not location or is_coordinate_string(location):
                                location = geolocate(gps_lat, gps_lon)
                                cached_entry["location"] = location

                        if date_taken:
                            content_hash = get_content_hash(
                                key_path,
                                size_bytes,
                                mtime_ns,
                                hash_options,
                                hash_conn,
                                hash_cache_pending,
                            )
                            photo_data.append(
                                (
                                    out_path,
                                    date_taken,
                                    size_bytes,
                                    mtime_ns,
                                    gps_lat,
                                    gps_lon,
                                    location,
                                    content_hash,
                                )
                            )
                            cached_count += 1
                        else:
                            error_log.write(
                                f"Warning: Cached entry for '{out_path}' has no date.\n"
                            )
                        # fall through to progress/checkpoint below

                    else:
                        # Not cached — query exiftool
                        date_taken, gps_lat, gps_lon = get_photo_data(
                            key_path, _exiftool=exiftool
                        )
                        location = None
                        if locate and gps_lat and gps_lon:
                            location = geolocate(gps_lat, gps_lon)
                            if location and is_coordinate_string(location):
                                location = None
                        if date_taken:
                            content_hash = get_content_hash(
                                key_path,
                                size_bytes,
                                mtime_ns,
                                hash_options,
                                hash_conn,
                                hash_cache_pending,
                            )
                            photo_data.append(
                                (
                                    out_path,
                                    date_taken,
                                    size_bytes,
                                    mtime_ns,
                                    gps_lat,
                                    gps_lon,
                                    location,
                                    content_hash,
                                )
                            )
                        else:
                            error_log.write(
                                f"Warning: Could not extract date for '{out_path}'.\n"
                            )
                        processed_count += 1

                except OSError as e:
                    error_log.write(f"Warning: Could not access '{file}': {str(e)}\n")
                    if _check_drive_disconnect(
                        e,
                        output,
                        photo_data,
                        inventory_root,
                        hash_options,
                        old_format,
                        cleanup_all,
                    ):
                        exiftool.stop()
                        return False
                    continue

                # --- Progress and checkpointing ---
                total_seen = cached_count + processed_count
                current_time = time.time()

                # Record rate sample
                rate_tracker.record(current_time, total_seen)

                # Checkpoint every 500 files or 5 minutes
                if total_seen % 500 == 0 or (current_time - last_save_time) > 300:
                    write_dates_to_file_atomic(
                        output,
                        photo_data,
                        inventory_root=inventory_root,
                        hash_options=hash_options,
                        old_format=old_format,
                    )
                    last_save_time = current_time
                    if not quiet:
                        print(
                            f"\n[Checkpoint: {len(photo_data):,} files saved]", end=""
                        )

                # Progress line every 2 seconds
                if not quiet and (current_time - last_progress_time) >= 2.0:
                    elapsed = current_time - start_time
                    rate = rate_tracker.rate()
                    rate_str = f"{rate:.0f} files/sec" if rate else "..."

                    if discovery_complete and total_files > 0:
                        # Phase 2: show percent and ETA
                        pct = total_seen / total_files * 100
                        eta_str = _format_eta(total_files - total_seen, rate)
                        eta_part = f" — ETA: {eta_str}" if eta_str else ""
                        print(
                            f"Processed {total_seen:,} / {total_files:,} ({pct:.1f}%) — "
                            f"{rate_str}{eta_part} [{_format_duration(elapsed)}]",
                            end="\r",
                        )
                    else:
                        # Phase 1: discovery still running
                        print(
                            f"Discovering... {discovery.discovered:,} found | "
                            f"Processed {total_seen:,} ({cached_count:,} cached) — "
                            f"{rate_str} [{_format_duration(elapsed)}]",
                            end="\r",
                        )
                    last_progress_time = current_time

        except KeyboardInterrupt:
            interrupted = True
            print(
                f"\n\nInterrupted! Saving progress ({len(photo_data):,} files processed so far)..."
            )
            try:
                write_dates_to_file_atomic(
                    output,
                    photo_data,
                    inventory_root=inventory_root,
                    hash_options=hash_options,
                    old_format=old_format,
                )
                print(f"Progress saved to '{output}'.")
            except Exception as save_err:
                print(f"WARNING: Could not save progress: {save_err}")
            print(f"\nTo resume, run the same command again:")
            print(f'  findphotodates.py --directory "{directory}" -o "{output}"')
            print(
                f"The scan will pick up where it left off using the saved inventory as cache."
            )

        exiftool.stop()

    # Wait for producer thread to finish (should already be done)
    producer.join(timeout=5)

    if interrupted:
        cleanup_all()
        return False

    total_seen = cached_count + processed_count
    if total_seen == 0:
        if not quiet:
            print("No files found with the specified extensions.")
        return True

    if not quiet:
        elapsed = time.time() - start_time
        print(
            f"\nProcessing complete: {total_seen:,} files in {_format_duration(elapsed)}.                              "
        )

    write_dates_to_file_atomic(
        output,
        photo_data,
        inventory_root=inventory_root,
        hash_options=hash_options,
        old_format=old_format,
    )

    if not quiet:
        print(f"Dates written to '{output}' ({len(photo_data):,} files listed).")
        if cached_count > 0:
            print(
                f"  ({cached_count:,} from cache, {processed_count:,} newly processed)"
            )

    summarize_results(photo_data, file_counts, quiet, debug)
    cleanup_all()
    return True


def add_hashes_to_inventory(tsv_path, hash_options, quiet=False, debug=False):
    """Fill in missing content hashes for an existing inventory TSV.

    Reads the TSV, computes hashes for rows with blank content_hash
    (where the file still exists and matches size/mtime), writes back.
    Uses the SQLite hash cache to avoid recomputing known hashes.
    """
    if not os.path.exists(tsv_path):
        print(f"Error: Inventory file '{tsv_path}' not found.")
        return False

    if hash_options.hash_mode == "off":
        print(
            "Error: --add-hashes requires hashing to be enabled. Use --hash sample or --hash full."
        )
        return False

    # Read existing TSV data
    # We use load_cache-style parsing but need the full rows including content_hash
    rows = []  # list of dicts with all TSV columns
    comment_lines = []  # preserve header comments
    header_line = None

    try:
        with open(tsv_path, "r", encoding="utf-8", newline="") as f:
            for line in f:
                line = line.rstrip("\n\r")
                if not line:
                    continue
                if line.startswith("#"):
                    comment_lines.append(line)
                    continue
                if header_line is None:
                    header_line = line
                    # Validate that this looks like the expected TSV header
                    header_fields = header_line.split("\t")
                    if header_fields[0] != "filepath":
                        print(
                            f"Error: Expected TSV header starting with 'filepath', got: {header_fields[0]!r}"
                        )
                        print(
                            f"  File '{tsv_path}' does not appear to be a valid findphotodates inventory."
                        )
                        return False
                    continue
                # Data row — use csv.reader to handle quoted fields containing
                # tabs (the writer uses csv.writer with QUOTE_MINIMAL).
                # Pad with empty strings if row has fewer fields than
                # TSV_COLUMNS (e.g. older inventories without content_hash).
                parts = next(csv.reader([line], delimiter="\t"))
                if len(parts) > len(TSV_COLUMNS):
                    if not quiet:
                        print(
                            f"WARNING: Row has {len(parts)} fields, expected {len(TSV_COLUMNS)}; "
                            f"extra fields will be dropped: {parts[0]!r}"
                        )
                row = dict(
                    zip(
                        TSV_COLUMNS,
                        parts + [""] * (len(TSV_COLUMNS) - len(parts)),
                        strict=False,
                    )
                )
                rows.append(row)
    except (IOError, UnicodeDecodeError) as e:
        print(f"Error reading '{tsv_path}': {e}")
        return False

    if not rows:
        if not quiet:
            print(f"No data rows found in '{tsv_path}'.")
        return True

    # Count how many need hashes
    need_hash = [r for r in rows if not r.get("content_hash", "").strip()]
    if not need_hash:
        if not quiet:
            print(f"All {len(rows)} rows already have content hashes.")
        return True

    if not quiet:
        print(
            f"Loaded {len(rows)} rows from '{tsv_path}'. {len(need_hash)} missing hashes."
        )
        msg = f"Hashing mode: {hash_options.hash_mode}"
        if hash_options.hash_mode == "sample":
            msg += f" ({hash_options.sample_chunks}x{hash_options.sample_chunk_mib:g} MiB {hash_options.sample_algo})"
        print(msg)

    # Open hash cache
    hash_conn = (
        open_sqlite_cache(hash_options.hash_cache_path, debug=debug)
        if (hash_options.use_hash_cache and hash_options.hash_mode != "off")
        else None
    )
    hash_cache_pending = [0] if hash_conn else None

    filled = 0
    skipped = 0
    errors = 0
    interrupted = False
    start_time = time.time()
    last_progress_time = start_time

    try:
        for row in rows:
            if row.get("content_hash", "").strip():
                continue  # already has hash

            filepath = row.get("filepath", "")
            if not filepath:
                continue

            try:
                key_path = os.path.realpath(filepath)
                stat_info = os.stat(key_path)
                size_bytes = stat_info.st_size
                mtime_ns = stat_info.st_mtime_ns

                # Verify file hasn't changed since indexing
                row_size = int(row.get("size_bytes", 0))
                row_mtime = int(row.get("mtime_ns", 0))
                if row_size != size_bytes or row_mtime != mtime_ns:
                    if debug:
                        print(f"  Skipping (changed): {filepath}")
                    skipped += 1
                    continue

                content_hash = get_content_hash(
                    key_path,
                    size_bytes,
                    mtime_ns,
                    hash_options,
                    hash_conn,
                    hash_cache_pending,
                )
                if content_hash:
                    row["content_hash"] = content_hash
                    filled += 1
                else:
                    errors += 1

            except OSError:
                skipped += 1
                continue

            # Progress every 2 seconds
            if not quiet:
                current_time = time.time()
                if current_time - last_progress_time >= 2.0:
                    elapsed = current_time - start_time
                    total_done = filled + skipped + errors
                    print(
                        f"  Hashed {filled:,} / {len(need_hash):,} — {skipped} skipped, {errors} errors [{_format_duration(elapsed)}]",
                        end="\r",
                    )
                    last_progress_time = current_time

    except KeyboardInterrupt:
        interrupted = True
        print(f"\n\nInterrupted! {filled:,} hashes computed so far.")
        if filled > 0:
            print("Saving partial progress...")
        else:
            print("No hashes were added. File unchanged.")

    # Commit any pending hash cache writes
    if hash_conn:
        try:
            if hash_cache_pending and hash_cache_pending[0] > 0:
                hash_conn.commit()
            hash_conn.close()
        except Exception:
            pass

    if not interrupted and not quiet:
        elapsed = time.time() - start_time
        print(
            f"\n  Done: {filled:,} hashes added, {skipped} skipped, {errors} errors [{_format_duration(elapsed)}]"
        )

    if filled == 0:
        if not interrupted and not quiet:
            print("No hashes were added. File unchanged.")
        return not interrupted

    # Reconstruct the hash_options comment lines to reflect current settings
    # Update or add hash_mode/content_hash_format headers
    new_comments = []
    has_hash_mode = False
    has_hash_format = False
    for line in comment_lines:
        if line.startswith("# hash_mode="):
            new_comments.append(f"# hash_mode={hash_options.hash_mode}")
            has_hash_mode = True
        elif line.startswith("# content_hash_format="):
            if hash_options.hash_mode == "sample":
                new_comments.append("# content_hash_format=samplehash_v1")
            elif hash_options.hash_mode == "full":
                new_comments.append("# content_hash_format=fullhash_v1")
            has_hash_format = True
        elif line.startswith("# samplehash_v1 ") and hash_options.hash_mode == "sample":
            new_comments.append(
                f"# samplehash_v1 algo={hash_options.sample_algo} chunks={hash_options.sample_chunks} chunk_mib={hash_options.sample_chunk_mib:g}"
            )
        elif line.startswith("# fullhash ") and hash_options.hash_mode == "full":
            new_comments.append(f"# fullhash algo={hash_options.full_algo}")
        else:
            new_comments.append(line)

    # Add headers if they didn't exist
    insert_pos = len(new_comments)
    for i, line in enumerate(new_comments):
        if line == TSV_HEADER:
            insert_pos = i
            break
    if not has_hash_mode:
        new_comments.insert(insert_pos, f"# hash_mode={hash_options.hash_mode}")
        insert_pos += 1
    if not has_hash_format:
        if hash_options.hash_mode == "sample":
            new_comments.insert(insert_pos, "# content_hash_format=samplehash_v1")
            insert_pos += 1
            new_comments.insert(
                insert_pos,
                f"# samplehash_v1 algo={hash_options.sample_algo} chunks={hash_options.sample_chunks} chunk_mib={hash_options.sample_chunk_mib:g}",
            )
        elif hash_options.hash_mode == "full":
            new_comments.insert(insert_pos, "# content_hash_format=fullhash_v1")
            insert_pos += 1
            new_comments.insert(insert_pos, f"# fullhash algo={hash_options.full_algo}")

    # Write back atomically
    output_dir = os.path.dirname(os.path.abspath(tsv_path))
    fd, temp_file = tempfile.mkstemp(
        dir=output_dir, suffix=".tsv", prefix=".findphotodates_"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            for line in new_comments:
                f.write(line + "\n")
            writer = csv.writer(f, delimiter="\t", quoting=csv.QUOTE_MINIMAL)
            writer.writerow(TSV_COLUMNS)
            sorted_rows = sorted(rows, key=lambda r: r.get("filepath", ""))
            for row in sorted_rows:
                writer.writerow(
                    [
                        row.get("filepath", ""),
                        row.get("date_taken", ""),
                        row.get("size_bytes", ""),
                        row.get("mtime_ns", ""),
                        row.get("gps_lat", ""),
                        row.get("gps_lon", ""),
                        row.get("location", ""),
                        row.get("content_hash", ""),
                    ]
                )
        os.replace(temp_file, tsv_path)
    except Exception:
        try:
            os.unlink(temp_file)
        except Exception:
            pass
        raise

    if interrupted:
        remaining = len(need_hash) - filled - skipped - errors
        print(
            f"Saved {filled:,} hashes to '{tsv_path}'. {remaining:,} rows still need hashes."
        )
        print(f"\nTo resume, run the same command again:")
        print(f'  findphotodates.py -o "{tsv_path}" --add-hashes')
        print(f"Already-hashed rows will be skipped automatically.")
        return False

    if not quiet:
        print(f"Updated '{tsv_path}' with {filled:,} new hashes.")
    return True


def _sigterm_handler(signum, frame):
    """Convert SIGTERM into KeyboardInterrupt so graceful shutdown paths are used."""
    raise KeyboardInterrupt


def main():
    # Install SIGTERM handler so 'kill' triggers the same graceful shutdown as Ctrl-C.
    signal.signal(signal.SIGTERM, _sigterm_handler)

    if len(sys.argv) == 1:
        print(
            """
Find Photo Dates - A tool to index and geolocate your media collection.

This tool recursively scans directories for photos and videos, extracting their
creation dates using ExifTool. It allows you to organize your media by date
and location.

Key Features:
  - Extracts 'Date Taken' from EXIF metadata.
  - Supports common photo (JPG, NEF, ORF) and video (MP4, MOV, AVI, etc.) formats.
  - Caches results in a TSV file to speed up subsequent runs.
  - Optional content hashing (--hash sample) for backup/deduplication safety.
  - Can reverse geolocate files using GPS coordinates (--locate).
  - Can save and manage multiple scan configurations (--save, --scan).

Usage: findphotodates.py [options]

Options:
  --directory DIR    The directory to search (default: current directory).
  --output FILE      The output TSV file to save results (default: photo.dates.tsv).
  --locate           Attempt to reverse geolocate files using GPS coordinates.
  --hash {sample,full,off}  Hashing mode (default: off). Use --hash sample to enable.
  --add-hashes             Fill in missing hashes for an existing inventory file.
  --old-format       Write legacy line-based output (./path: YYYY:MM:DD HH:MM:SS) without hashes.
  --video            Search for video files only.
  --only-photos      Search for photo files only.
  --extension EXT    Search for a specific file extension (e.g., --extension jpg).
  --save             Save the current scan configuration for later use.
  --scan             Run all saved scan configurations.
  --quiet            Run quietly (suppress normal output).
  --debug            Enable verbose debug output.
  --test             Run internal tests.

For more details on a specific option, you can also use:
  findphotodates.py --help
"""
        )
        return

    try:
        result = subprocess.run(["exiftool", "-ver"], capture_output=True, timeout=5)
        if result.returncode != 0:
            print("Error: ExifTool is required but the 'exiftool' command failed.")
            return
    except FileNotFoundError:
        print("Error: ExifTool is required but was not found.")
        return
    except subprocess.TimeoutExpired:
        print("Error: ExifTool check timed out.")
        return

    parser = argparse.ArgumentParser(
        description="Recursively find files with specified extensions and extract the date each file was created using exiftool."
    )
    parser.add_argument(
        "--directory",
        default=".",
        help="The directory to search (default: current directory).",
    )
    parser.add_argument(
        "-o", "--output", "--out", default=None, help="The output file path."
    )
    parser.add_argument("-q", "--quiet", action="store_true", help="Run quietly.")
    parser.add_argument("--debug", action="store_true", help="Run in debug mode.")
    parser.add_argument(
        "--video", action="store_true", help="Search for video files only."
    )
    parser.add_argument(
        "--only-photos", action="store_true", help="Search for photo files only."
    )
    parser.add_argument("--extension", help="Specify a custom file extension.")
    parser.add_argument(
        "--locate",
        action="store_true",
        help="Attempt to locate files using GPS coordinates.",
    )
    parser.add_argument(
        "--test", action="store_true", help="Run date parsing tests and exit."
    )
    parser.add_argument(
        "--save", action="store_true", help="Save current scan configuration."
    )
    parser.add_argument(
        "--scan", action="store_true", help="Run all saved scan configurations."
    )
    parser.add_argument(
        "--hash",
        choices=["sample", "full", "off"],
        default="off",
        help="Hashing mode (default: off). Use --hash sample to enable.",
    )
    parser.add_argument(
        "--sample-chunks",
        type=int,
        default=3,
        help="Number of sample chunks (default: 3).",
    )
    parser.add_argument(
        "--sample-chunk-mib",
        type=float,
        default=0.0625,
        help="Size of each chunk in MiB (default: 0.0625 = 64 KiB).",
    )
    parser.add_argument(
        "--hash-algo",
        choices=["blake3", "blake2b", "sha256"],
        help="Override hash algorithm. (Delete cache file to reclaim space if needed).",
    )
    parser.add_argument(
        "--hash-cache", metavar="PATH", default=None, help="Path to SQLite hash cache."
    )
    parser.add_argument(
        "--no-hash-cache", action="store_true", help="Disable hash cache."
    )
    parser.add_argument(
        "--hash-exts",
        metavar="LIST",
        default=None,
        help="Comma-separated extensions to hash.",
    )
    parser.add_argument(
        "--old-format", action="store_true", help="Write legacy line-based output."
    )
    parser.add_argument(
        "--add-hashes",
        action="store_true",
        help="Fill in missing content hashes for an existing inventory TSV. Reads the TSV, computes hashes for rows with blank content_hash, writes back. Uses --hash to set mode (default: sample for --add-hashes).",
    )

    args = parser.parse_args()
    output = args.output
    if output is None:
        output = "photo.dates.txt" if args.old_format else "photo.dates.tsv"

    # For --add-hashes, default hash mode to sample (not off) unless user explicitly set it
    effective_hash_mode = args.hash
    if args.add_hashes and args.hash == "off":
        effective_hash_mode = "sample"

    hash_options = parse_hash_args(
        hash_mode=effective_hash_mode,
        sample_chunks=args.sample_chunks,
        sample_chunk_mib=args.sample_chunk_mib,
        hash_algo=args.hash_algo,
        hash_cache_path=args.hash_cache,
        no_hash_cache=args.no_hash_cache,
        hash_exts_str=args.hash_exts,
        quiet=args.quiet,
    )

    if args.test:
        test_date_parsing()
        return

    if args.add_hashes:
        output_abs = _expand_path(output)
        add_hashes_to_inventory(
            output_abs, hash_options, quiet=args.quiet, debug=args.debug
        )
        return

    if args.save:
        directory_abs = _expand_path(args.directory)
        output_abs = _expand_path(output)
        if not os.path.exists(directory_abs):
            print(f"Error: Directory '{directory_abs}' does not exist.")
            return

        drive_root, path_relative = detect_drive_root(directory_abs)
        drive_hint_value = get_drive_hint(drive_root)

        if args.extension:
            extensions_list = [args.extension.lower()]
        elif args.video:
            extensions_list = sorted(list(VIDEO_EXTENSIONS))
        elif args.only_photos:
            extensions_list = sorted(list(PHOTO_EXTENSIONS))
        else:
            extensions_list = sorted(list(DEFAULT_EXTENSIONS))

        flags = {
            "video": args.video,
            "only_photos": args.only_photos,
            "locate": args.locate,
            "quiet": args.quiet,
            "debug": args.debug,
            "extensions": extensions_list,
            "hash": args.hash,
            "sample_chunks": args.sample_chunks,
            "sample_chunk_mib": args.sample_chunk_mib,
            "hash_algo": args.hash_algo,
            "hash_cache": args.hash_cache,
            "no_hash_cache": args.no_hash_cache,
            "hash_exts": args.hash_exts,
            "old_format": args.old_format,
        }

        config = load_config()
        updated = False
        for entry in config["saved_scans"]:
            if path_relative and entry.get("path_relative") == path_relative:
                if (
                    entry.get("drive_hint", {}).get("value") == drive_hint_value
                    and entry.get("output_abs") == output_abs
                ):
                    entry["directory_abs"] = directory_abs
                    entry["flags"] = flags
                    updated = True
                    break
            elif entry.get("directory_abs") == directory_abs:
                entry["path_relative"] = path_relative
                entry["output_abs"] = output_abs
                entry["flags"] = flags
                entry["drive_hint"] = {
                    "kind": "volume_label_or_root",
                    "value": drive_hint_value,
                }
                updated = True
                break

        if not updated:
            new_entry = {
                "id": "",
                "drive_hint": {
                    "kind": "volume_label_or_root",
                    "value": drive_hint_value,
                },
                "directory_abs": directory_abs,
                "path_relative": path_relative,
                "output_abs": output_abs,
                "flags": flags,
            }
            config["saved_scans"].append(new_entry)

        save_config(config)
        if not args.quiet:
            print(
                f"{'Updated' if updated else 'Saved'} scan configuration for: {directory_abs}"
            )

        if args.scan:
            pass
        else:
            extensions = (
                {args.extension.lower()}
                if args.extension
                else (
                    VIDEO_EXTENSIONS
                    if args.video
                    else (PHOTO_EXTENSIONS if args.only_photos else DEFAULT_EXTENSIONS)
                )
            )
            run_scan(
                directory_abs,
                output_abs,
                extensions,
                args.locate,
                args.quiet,
                args.debug,
                hash_options=hash_options,
                old_format=args.old_format,
            )
            return

    if args.scan:
        config = load_config()
        if not config.get("saved_scans"):
            print("No saved scan configurations found.")
            return

        print(f"Running {len(config['saved_scans'])} saved scan(s)...")
        for idx, entry in enumerate(config["saved_scans"], 1):
            resolved_dir = resolve_saved_directory(entry)
            if not resolved_dir or not os.path.exists(resolved_dir):
                print(
                    f"\n[{idx}] Skipping {entry.get('directory_abs', 'unknown')}: not found"
                )
                continue

            print(f"\n[{idx}] Scanning: {resolved_dir}")
            flags = entry.get("flags", {})
            scan_hash_options = parse_hash_args(
                hash_mode=flags.get("hash", "off"),
                sample_chunks=flags.get("sample_chunks", 3),
                sample_chunk_mib=flags.get("sample_chunk_mib", 0.0625),
                hash_algo=flags.get("hash_algo"),
                hash_cache_path=flags.get("hash_cache"),
                no_hash_cache=flags.get("no_hash_cache", False),
                hash_exts_str=flags.get("hash_exts"),
                quiet=args.quiet,
            )
            extensions = set(flags.get("extensions", DEFAULT_EXTENSIONS))
            try:
                run_scan(
                    resolved_dir,
                    entry.get("output_abs", "photo.dates.tsv"),
                    extensions,
                    flags.get("locate", False),
                    flags.get("quiet", False),
                    flags.get("debug", False),
                    hash_options=scan_hash_options,
                    old_format=flags.get("old_format", False),
                )
            except Exception as e:
                print(f"  Error: {e}")
        return

    directory_abs = _expand_path(args.directory)
    output_abs = _expand_path(output)
    extensions = (
        {args.extension.lower()}
        if args.extension
        else (
            VIDEO_EXTENSIONS
            if args.video
            else (PHOTO_EXTENSIONS if args.only_photos else DEFAULT_EXTENSIONS)
        )
    )
    run_scan(
        directory_abs,
        output_abs,
        extensions,
        args.locate,
        args.quiet,
        args.debug,
        hash_options=hash_options,
        old_format=args.old_format,
    )


def test_date_parsing():
    from collections import Counter, defaultdict

    test_photo_data = [
        (
            "/path/to/file1.jpg",
            "2025:12:31 23:59:59",
            1000,
            1234567890,
            "37.7749",
            "-122.4194",
            None,
            "hash1",
        ),
        (
            "/path/to/file2.jpg",
            "2025:12:31 12:00:00",
            2000,
            1234567891,
            "34.0522",
            "-118.2437",
            None,
            "hash2",
        ),
        (
            "/path/to/file3.jpg",
            "2025:12:30 10:30:00",
            3000,
            1234567892,
            None,
            None,
            None,
            "hash3",
        ),
    ]
    date_counter = Counter()
    for entry in test_photo_data:
        date_str = entry[1]
        if date_str:
            dt = datetime.strptime(date_str, "%Y:%m:%d %H:%M:%S")
            date_counter[dt.strftime("%Y-%m-%d")] += 1
    assert date_counter["2025-12-31"] == 2
    assert date_counter["2025-12-30"] == 1
    print("✓ All date parsing tests passed!")


if __name__ == "__main__":
    main()
