#!/usr/bin/python3

# Find photo / video dates version 1.2 - By Alan Rockefeller January 6, 2026

import os
import sys
import subprocess
import argparse
import re
import time
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from pathlib import Path
import tempfile
import csv
import urllib.request
import urllib.error
import json
import platform
import string

# Define supported photo file extensions
PHOTO_EXTENSIONS = {"jpg", "jpeg", "nef", "orf"}
# Define common video file extensions
VIDEO_EXTENSIONS = {"mp4", "mov", "avi", "mkv", "wmv", "flv", "webm", "m4v", "3gp"}
# Default extensions (both photos and videos)
DEFAULT_EXTENSIONS = PHOTO_EXTENSIONS.union(VIDEO_EXTENSIONS)

# TSV header identifier
TSV_HEADER = "# Generated by findphotodates.py"
TSV_COLUMNS = ["filepath", "date_taken", "size_bytes", "mtime_ns", "gps_lat", "gps_lon", "location"]

def is_supported_file(filename, extensions):
    """Check if a file has a supported extension."""
    return any(filename.lower().endswith(f".{ext}") for ext in extensions)

def find_files(directory, extensions):
    """Recursively find all files with the specified extensions in the given directory."""
    for root, _, files in os.walk(directory):
        for file in files:
            if is_supported_file(file, extensions):
                yield os.path.join(root, file)

def get_photo_data(filepath):
    """Use exiftool to get the date and GPS data of a photo/video.
    
    Always extracts GPS data so it can be cached and used later
    without re-reading EXIF.
    """
    try:
        # Call exiftool to extract the Date/Time Original tag, fall back to other date fields
        # Always extract GPS data so we can cache it for later --locate runs
        date_tags = ["-DateTimeOriginal", "-CreateDate", "-MediaCreateDate"]
        tags = date_tags.copy()
        tags.extend(["-GPSLatitude", "-GPSLongitude"])

        result = subprocess.run(
            ["exiftool", "-n", "-f", *tags, "-s", "-s", "-s", filepath],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        if result.returncode == 0:
            lines = result.stdout.splitlines()
            # With -f, we typically get 5 lines: 3 date tags + 2 GPS tags
            # date fields are lines[0:3]; GPS are lines[3], lines[4]
            # But exiftool can emit extra lines in edge cases, so be defensive
            
            # Process date - try each possible date field
            date = None
            if len(lines) >= len(date_tags):
                for i in range(len(date_tags)):
                    line = lines[i].strip()
                    if line and line != "-":
                        # Basic validation that this looks like a date
                        if re.match(r'\d{4}:\d{2}:\d{2} \d{2}:\d{2}:\d{2}', line):
                            date = line
                            break
            
            # Always extract GPS data (for caching) - parse by position
            gps_lat = None
            gps_lon = None
            if len(lines) >= len(date_tags) + 2:
                gps_lat_str = lines[len(date_tags)].strip()
                gps_lon_str = lines[len(date_tags) + 1].strip()
                if gps_lat_str and gps_lat_str != "-":
                    gps_lat = gps_lat_str
                if gps_lon_str and gps_lon_str != "-":
                    gps_lon = gps_lon_str
                            
            return date, gps_lat, gps_lon
        else:
            return None, None, None
    except FileNotFoundError as e:
        raise FileNotFoundError("Exiftool is required but was not found. Please install it.") from e

# Global variables for geolocation rate limiting and coordinate caching
_last_geolocate_time = 0
_coord_cache = {}  # (round(lat,5), round(lon,5)) -> location

def geolocate(lat, lon):
    """Convert GPS coordinates to a human-readable location using Nominatim API.
    
    Implements rate limiting (1 second between requests) and in-memory coordinate caching
    to avoid duplicate API calls for the same location within a single run.
    Falls back to coordinates if the request fails.
    
    Note: The coordinate cache is in-memory only and does not persist between runs.
    However, location data in the TSV output file serves as a persistent cache - once
    a location is computed and saved, it will be reused from the TSV cache on subsequent runs.
    """
    global _last_geolocate_time, _coord_cache
    
    if not lat or not lon:
        return None
    
    try:
        # Convert to float to ensure valid coordinates
        lat_float = float(lat)
        lon_float = float(lon)
    except (ValueError, TypeError):
        return f"{lat}, {lon}"
    
    # Check coordinate cache (round to 5 decimal places ~1.1m precision)
    cache_key = (round(lat_float, 5), round(lon_float, 5))
    if cache_key in _coord_cache:
        return _coord_cache[cache_key]
    
    # Rate limiting: wait at least 1 second since last request
    current_time = time.time()
    time_since_last = current_time - _last_geolocate_time
    if time_since_last < 1.0:
        time.sleep(1.0 - time_since_last)
    
    try:
        # Build Nominatim reverse geocoding URL with addressdetails=1
        url = f"https://nominatim.openstreetmap.org/reverse?format=json&lat={lat_float}&lon={lon_float}&addressdetails=1"
        
        # Create request with proper User-Agent header (required by Nominatim)
        req = urllib.request.Request(url)
        req.add_header('User-Agent', 'findphotodates.py/1.1 (https://github.com/alanrockefeller/findphotodates.py)')
        
        # Make the request
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode())
            
            # Update last request time
            _last_geolocate_time = time.time()
            
            # Extract location from response - prefer address components over display_name
            location = None
            if 'address' in data:
                addr = data['address']
                parts = []
                # Build location from address components in order of specificity
                for key in ['city', 'town', 'village', 'county', 'state', 'country']:
                    if key in addr:
                        parts.append(addr[key])
                if parts:
                    location = ', '.join(parts)
            
            # Fallback to display_name if address components didn't work
            if not location and 'display_name' in data:
                location = data['display_name']
            
            # Fallback to coordinates if no location found
            if not location:
                location = f"{lat_float}, {lon_float}"
            
            # Cache the result
            _coord_cache[cache_key] = location
            return location
            
    except urllib.error.HTTPError as e:
        # Handle 429 (rate limit) with longer backoff
        if e.code == 429:
            _last_geolocate_time = time.time() + 5  # Wait 5 seconds before next attempt
        else:
            _last_geolocate_time = time.time()
        # Don't cache fallback coordinates - allow retry on next run
        return f"{lat_float}, {lon_float}"
    except Exception:
        # Don't cache fallback coordinates - allow retry on next run
        _last_geolocate_time = time.time()
        return f"{lat_float}, {lon_float}"

def is_coordinate_string(location):
    """Check if location string looks like raw coordinates (e.g., "37.7, -122.4")."""
    if not location:
        return False
    # Match pattern: optional negative, digits, optional decimal, comma, optional space, optional negative, digits, optional decimal
    return bool(re.match(r'^-?\d+(\.\d+)?,\s*-?\d+(\.\d+)?$', location.strip()))

def load_cache(output_file):
    """Load existing TSV cache if it exists and has the expected header."""
    cache = {}
    if not os.path.exists(output_file):
        return cache
    
    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            first_line = f.readline().strip()
            if first_line != TSV_HEADER:
                return cache
            
            # Let DictReader read the header automatically
            reader = csv.DictReader(f, delimiter='\t')
            
            # Verify header matches expected columns
            if reader.fieldnames != TSV_COLUMNS:
                return cache
            
            for row in reader:
                filepath = row.get('filepath', '')
                if filepath:
                    try:
                        # Normalize to real path (follows symlinks) for cache key consistency
                        abs_filepath = os.path.realpath(filepath)
                        size_bytes = int(row.get('size_bytes', '0'))
                        mtime_ns = int(row.get('mtime_ns', '0'))
                        date_taken = row.get('date_taken', '') or None
                        gps_lat = row.get('gps_lat', '') or None
                        gps_lon = row.get('gps_lon', '') or None
                        location = row.get('location', '') or None
                        
                        # Treat coordinate strings as missing location (allows retry)
                        if location and is_coordinate_string(location):
                            location = None
                        
                        cache[abs_filepath] = {
                            'size_bytes': size_bytes,
                            'mtime_ns': mtime_ns,
                            'date_taken': date_taken,
                            'gps_lat': gps_lat,
                            'gps_lon': gps_lon,
                            'location': location
                        }
                    except (ValueError, KeyError):
                        continue
    except (IOError, UnicodeDecodeError):
        return cache
    
    return cache

def write_dates_to_file_atomic(output_file, photo_data):
    """Write photo data to TSV file atomically (temp file then replace) using csv.writer."""
    # Create a temporary file in the same directory as the output file
    output_dir = os.path.dirname(os.path.abspath(output_file))
    if not output_dir:
        output_dir = '.'
    
    fd, temp_file = tempfile.mkstemp(dir=output_dir, suffix='.tsv', prefix='.findphotodates_')
    
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='') as f:
            # Write header identifier
            f.write(TSV_HEADER + '\n')
            
            # Use csv.writer for proper TSV escaping
            writer = csv.writer(f, delimiter='\t', quoting=csv.QUOTE_MINIMAL)
            
            # Write column headers
            writer.writerow(TSV_COLUMNS)
            
            # Sort by filepath for consistent output ordering
            sorted_data = sorted(photo_data, key=lambda r: r[0])
            
            # Write data rows
            for filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location in sorted_data:
                writer.writerow([
                    filepath,
                    date_taken or '',
                    str(size_bytes),
                    str(mtime_ns),
                    gps_lat or '',
                    gps_lon or '',
                    location or ''
                ])
        
        # Atomically replace the output file using os.replace()
        os.replace(temp_file, output_file)
    except Exception:
        # Clean up temp file on error
        try:
            os.unlink(temp_file)
        except Exception:
            pass
        raise

def summarize_results(photo_data, file_counts, quiet, debug=False):
    """Print a summary of results."""
    if quiet:
        return

    print("\nSummary of Results:\n")

    # Print counts by file type
    print("Files found:")
    for ext, count in sorted(file_counts.items()):
        print(f"  {ext.upper()}: {count}")

    # Calculate date summaries
    date_counter = Counter()
    for entry in photo_data:
        # Entry is a tuple: (filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location)
        date_str = entry[1] if len(entry) > 1 else None
        
        # Skip None or empty dates
        if not date_str:
            continue
        
        try:
            # Parse exiftool date format: YYYY:MM:DD HH:MM:SS
            dt = datetime.strptime(date_str, "%Y:%m:%d %H:%M:%S")
            day_key = dt.strftime("%Y-%m-%d")
            date_counter[day_key] += 1
        except (ValueError, AttributeError, TypeError) as e:
            # Gracefully skip invalid dates
            if debug:
                print(f"Warning: Could not parse date '{date_str}': {str(e)}")
            continue

    # Determine file type label for summary
    file_type_label = "Media" 
    if all(ext in VIDEO_EXTENSIONS for ext in file_counts):
        file_type_label = "Videos"
    elif all(ext in PHOTO_EXTENSIONS for ext in file_counts):
        file_type_label = "Photos"
            
    if len(date_counter) <= 20:
        print(f"\n{file_type_label} Taken per day:")
        for day, count in sorted(date_counter.items()):
            print(f"  {day}: {count}")
    else:
        month_counter = defaultdict(int)
        for day_key in date_counter:
            try:
                # Parse the day_key (YYYY-MM-DD) to get year-month
                dt = datetime.strptime(day_key, "%Y-%m-%d")
                year_month_key = dt.strftime("%Y-%m")
                month_counter[year_month_key] += date_counter[day_key]
            except (ValueError, AttributeError) as e:
                # Gracefully skip invalid day keys
                if debug:
                    print(f"Warning: Could not extract year-month from '{day_key}': {str(e)}")
                continue
        print(f"\n{file_type_label} Taken per Month:")
        for year_month, count in sorted(month_counter.items()):
            print(f"  {year_month}: {count}")

# Path expansion helper
def _expand_path(p: str) -> str:
    """Expand user home directory and convert to absolute path."""
    return os.path.abspath(os.path.expanduser(p))

# Config file handling
CONFIG_FILE = Path.home() / ".findphotodates.config.json"

def load_config():
    """Load configuration from JSON file."""
    if not CONFIG_FILE.exists():
        return {"_comment": "Saved scan configurations for findphotodates.py. Edit cautiously; JSON comments are stored here.", "saved_scans": []}
    
    try:
        with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
            config = json.load(f)
        # Ensure required structure
        if "saved_scans" not in config:
            config["saved_scans"] = []
        return config
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in config file {CONFIG_FILE}: {e}")
        print("Please fix or remove the config file and try again.")
        exit(1)
    except Exception as e:
        print(f"Error: Failed to read config file {CONFIG_FILE}: {e}")
        exit(1)

def save_config(config):
    """Save configuration to JSON file atomically."""
    try:
        # Ensure directory exists
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
        
        # Create temp file in same directory
        fd, temp_file = tempfile.mkstemp(dir=CONFIG_FILE.parent, suffix='.json', prefix='.findphotodates_')
        
        try:
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                json.dump(config, f, indent=2, ensure_ascii=False, sort_keys=True)
            
            # Atomically replace
            os.replace(temp_file, CONFIG_FILE)
        except Exception:
            try:
                os.unlink(temp_file)
            except Exception:
                pass
            raise
    except Exception as e:
        print(f"Error: Failed to write config file {CONFIG_FILE}: {e}")
        exit(1)

def detect_drive_root(directory_abs):
    """Detect the drive root for a given absolute directory path.
    
    Returns (drive_root, path_relative) where:
    - drive_root is the mount point (e.g., /Volumes/MyPassport, C:\\, /media/user/drive)
    - path_relative is the path relative to drive_root (e.g., "Photos", "DCIM/100CANON")
    
    Best-effort detection using heuristics.
    """
    directory_abs = os.path.abspath(directory_abs)
    system = platform.system()
    
    # Try to find mount points
    if system == "Darwin":  # macOS
        # Check if under /Volumes
        if directory_abs.startswith("/Volumes/"):
            parts = directory_abs.split("/")
            if len(parts) >= 3:
                drive_root = "/" + "/".join(parts[1:3])  # /Volumes/VolumeName
                path_relative = "/".join(parts[3:]) if len(parts) > 3 else ""
                return drive_root, path_relative
    
    elif system == "Linux":
        # Check /media (typically /media/<user>/<drive> - two levels deep)
        if directory_abs.startswith("/media/"):
            parts = directory_abs.split("/")
            # /media/<user>/<drive> - drive is at index 3
            if len(parts) >= 4:
                drive_root = "/" + "/".join(parts[1:4])  # /media/user/drive
                path_relative = "/".join(parts[4:]) if len(parts) > 4 else ""
                return drive_root, path_relative
        
        # Check /run/media (typically /run/media/<user>/<drive> - two levels deep)
        if directory_abs.startswith("/run/media/"):
            parts = directory_abs.split("/")
            # /run/media/<user>/<drive> - drive is at index 4
            if len(parts) >= 5:
                drive_root = "/" + "/".join(parts[1:5])  # /run/media/user/drive
                path_relative = "/".join(parts[5:]) if len(parts) > 5 else ""
                return drive_root, path_relative
        
        # Check /mnt (typically /mnt/<drive> - one level deep)
        if directory_abs.startswith("/mnt/"):
            parts = directory_abs.split("/")
            # /mnt/<drive> - drive is at index 2
            if len(parts) >= 3:
                drive_root = "/" + "/".join(parts[1:3])  # /mnt/drive
                path_relative = "/".join(parts[3:]) if len(parts) > 3 else ""
                return drive_root, path_relative
    
    elif system == "Windows":
        # On Windows, drive root is typically C:\, D:\, etc.
        if len(directory_abs) >= 2 and directory_abs[1] == ":":
            drive_root = directory_abs[:2] + "\\"
            path_relative = directory_abs[3:].replace("\\", "/") if len(directory_abs) > 2 else ""
            return drive_root, path_relative
    
    # Fallback: use directory itself as root
    return directory_abs, ""

def get_drive_hint(drive_root):
    """Extract a hint value from drive root (e.g., volume name)."""
    if not drive_root:
        return ""
    
    # Special case for Windows drive roots (C:\, D:\, etc.)
    if platform.system() == "Windows" and len(drive_root) >= 2 and drive_root[1] == ":":
        # Use os.path.splitdrive to get just the letter
        drive, _ = os.path.splitdrive(drive_root)
        return drive.rstrip(":")  # Return just "C", "D", etc.
    
    # Extract last component
    if os.path.sep in drive_root:
        parts = drive_root.rstrip(os.path.sep).split(os.path.sep)
        return parts[-1] if parts else ""
    elif ":" in drive_root:
        # Windows drive letter (fallback)
        return drive_root.rstrip(":\\")
    return drive_root

def resolve_saved_directory(entry):
    """Resolve a saved scan entry to a current directory path.
    
    Returns the resolved directory path, or None if not found.
    """
    # Try directory_abs first
    if entry.get("directory_abs") and os.path.exists(entry["directory_abs"]):
        return entry["directory_abs"]
    
    # Try to reconstruct using path_relative + drive root detection
    path_relative = entry.get("path_relative", "")
    drive_hint = entry.get("drive_hint", {}).get("value", "")
    
    system = platform.system()
    candidate_roots = []
    
    if system == "Darwin":  # macOS
        volumes_dir = Path("/Volumes")
        if volumes_dir.exists():
            for vol in volumes_dir.iterdir():
                if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                    candidate_roots.append(str(vol))
    
    elif system == "Linux":
        # Handle /media/<user>/<drive> (two levels deep)
        media_path = Path("/media")
        if media_path.exists():
            for user_dir in media_path.iterdir():
                if user_dir.is_dir():
                    for vol in user_dir.iterdir():
                        if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                            candidate_roots.append(str(vol))
        
        # Handle /run/media/<user>/<drive> (two levels deep)
        run_media_path = Path("/run/media")
        if run_media_path.exists():
            for user_dir in run_media_path.iterdir():
                if user_dir.is_dir():
                    for vol in user_dir.iterdir():
                        if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                            candidate_roots.append(str(vol))
        
        # Handle /mnt/<drive> (one level deep)
        mnt_path = Path("/mnt")
        if mnt_path.exists():
            for vol in mnt_path.iterdir():
                if vol.is_dir() and (not drive_hint or vol.name == drive_hint):
                    candidate_roots.append(str(vol))
    
    elif system == "Windows":
        # Check all drive letters
        for letter in string.ascii_uppercase:
            drive = f"{letter}:\\"
            if os.path.exists(drive):
                if not drive_hint or drive_hint.upper() == letter:
                    candidate_roots.append(drive)
    
    # Try each candidate root
    for root in candidate_roots:
        if path_relative:
            # Normalize path separators for current platform
            normalized_relative = path_relative.replace("/", os.path.sep).replace("\\", os.path.sep)
            candidate = os.path.join(root, normalized_relative)
        else:
            candidate = root
        
        if os.path.exists(candidate) and os.path.isdir(candidate):
            return candidate
    
    # Fallback: try directory_abs even if it doesn't exist (might be temporarily unmounted)
    return entry.get("directory_abs")

def run_scan(directory, output, extensions, locate=False, quiet=False, debug=False):
    """Run a scan on the specified directory.
    
    Args:
        directory: Directory to scan
        output: Output TSV file path
        extensions: Set of file extensions to scan
        locate: Whether to geolocate files
        quiet: Whether to suppress output
        debug: Whether to enable debug mode
    
    Returns:
        True if successful, False otherwise
    """
    # Ensure the directory exists
    if not os.path.exists(directory):
        if not quiet:
            print(f"Error: Directory '{directory}' does not exist.")
        return False

    if not quiet:
        print(f"Searching for files in '{directory}' with extensions: {', '.join(extensions)}...")

    files = list(find_files(directory, extensions))

    if not files:
        if not quiet:
            print("No files found with the specified extensions.")
        return True  # Not an error, just no files

    if not quiet:
        print(f"Found {len(files)} files.")

    file_counts = Counter(file.split(".")[-1].lower() for file in files)

    # Load existing cache
    cache = load_cache(output)
    if not quiet and cache:
        print(f"Loaded {len(cache)} entries from cache.")

    # Redirect warnings to a unique log file per run
    error_log_path = os.path.join(
        tempfile.gettempdir(),
        f"findphotodates.error.{os.getpid()}.{int(time.time())}.log"
    )
    photo_data = []
    files_to_process = []
    cached_count = 0
    
    with open(error_log_path, "w") as error_log:
        
        for idx, file in enumerate(files):
            try:
                # Preserve what user sees in output (abspath)
                out_path = os.path.abspath(file)
                # Use canonical path for cache key (realpath) to dedupe symlinks
                key_path = os.path.realpath(out_path)
                
                # Get filesystem metadata using canonical path
                stat_info = os.stat(key_path)
                size_bytes = stat_info.st_size
                mtime_ns = stat_info.st_mtime_ns
                
                # Check cache using canonical path
                cached_entry = cache.get(key_path)
                if cached_entry and cached_entry['size_bytes'] == size_bytes and cached_entry['mtime_ns'] == mtime_ns:
                    # Use cached data
                    date_taken = cached_entry['date_taken']
                    gps_lat = cached_entry.get('gps_lat')
                    gps_lon = cached_entry.get('gps_lon')
                    location = cached_entry.get('location')
                    
                    # If --locate is requested but location is missing, try to geolocate from cached GPS
                    # Note: This location will be persisted when we write photo_data to the TSV
                    # Also retry if location looks like raw coordinates (treat as missing)
                    if locate and gps_lat and gps_lon:
                        if not location or is_coordinate_string(location):
                            location = geolocate(gps_lat, gps_lon)
                            # Update cached location for this entry (will be written back via photo_data)
                            cached_entry['location'] = location
                    
                    if date_taken:
                        # Always preserve location if it exists (don't delete on non--locate runs)
                        # Use out_path (abspath) for output to preserve what user sees
                        photo_data.append((out_path, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location))
                        cached_count += 1
                    else:
                        error_log.write(f"Warning: Cached entry for '{out_path}' has no date.\n")
                else:
                    # File is new or changed, needs processing
                    # Store both paths: out_path for output, key_path for cache lookup
                    files_to_process.append((out_path, key_path, size_bytes, mtime_ns))
            except OSError as e:
                error_log.write(f"Warning: Could not stat '{file}': {str(e)}\n")
                # Check for drive disconnect
                if any(err in str(e).lower() for err in ['no such file', 'input/output error', 'stale file handle']):
                    print("\n\nWARNING: Drive may be disconnected! Saving progress...")
                    write_dates_to_file_atomic(output, photo_data)
                    print(f"Saved {len(photo_data)} files to '{output}'")
                    print("Reconnect drive and run again to resume.")
                    return False
                continue

        if not quiet:
            print(f"Found {cached_count} files in cache, {len(files_to_process)} files need processing.")

        # Estimate runtime and save results from first files
        start_time = time.time()
        last_save_time = start_time
        estimated_finish_time = None
        timing_results = []  # Save results from timing test files
        start_idx = 0
        
        if len(files_to_process) > 10 and not quiet:
            test_files = min(5, len(files_to_process))
            for out_path, key_path, size_bytes, mtime_ns in files_to_process[:test_files]:
                try:
                    # Always extract GPS data (even if locate=False) for caching
                    # Use key_path (canonical) for exiftool, but out_path for output
                    date_taken, gps_lat, gps_lon = get_photo_data(key_path)
                    location = None
                    if locate and gps_lat and gps_lon:
                        location = geolocate(gps_lat, gps_lon)
                        # Don't save coordinate strings as location (treat as None to allow retry)
                        if location and is_coordinate_string(location):
                            location = None
                    if date_taken:
                        # Save result for reuse - use out_path for output
                        timing_results.append((out_path, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location))
                    else:
                        error_log.write(f"Warning: Could not extract date for '{out_path}'.\n")
                except OSError as e:
                    error_log.write(f"Error: Could not access '{out_path}': {e}\n")
                    # Check for drive disconnect
                    if any(err in str(e).lower() for err in ['no such file', 'input/output error', 'stale file handle']):
                        print("\n\nWARNING: Drive may be disconnected! Saving progress...")
                        write_dates_to_file_atomic(output, photo_data)
                        print(f"Saved {len(photo_data)} files to '{output}'")
                        print("Reconnect drive and run again to resume.")
                        return False
                    continue
            
            elapsed_time = time.time() - start_time
            avg_time_per_file = elapsed_time / test_files
            estimated_total_time = avg_time_per_file * len(files_to_process)
            estimated_finish_time = datetime.now() + timedelta(seconds=estimated_total_time)

            if debug:
                print(f"Timing the processing of the first {test_files} files to estimate total runtime...")
            if estimated_total_time > 3600:
                hours = int(estimated_total_time // 3600)
                minutes = int((estimated_total_time % 3600) // 60)
                print(f"Estimated total runtime: {hours} hours and {minutes} minutes.")
            elif estimated_total_time > 180:
                minutes = int(estimated_total_time // 60)
                seconds = int(estimated_total_time % 60)
                print(f"Estimated total runtime: {minutes} minutes and {seconds} seconds.")
            else:
                print(f"Estimated total runtime: {estimated_total_time:.2f} seconds.")
            print(f"Expected to finish by: {estimated_finish_time.strftime('%Y-%m-%d %H:%M:%S')}.")
            
            # Start main processing from index test_files (skip files we already processed)
            start_idx = test_files
            # Prepend saved results to photo_data
            photo_data.extend(timing_results)

        # Process remaining files that need exiftool
        for idx, (out_path, key_path, size_bytes, mtime_ns) in enumerate(files_to_process[start_idx:], start=start_idx):
            try:
                # Always extract GPS data (even if locate=False) for caching
                # Use key_path (canonical) for exiftool, but out_path for output
                date_taken, gps_lat, gps_lon = get_photo_data(key_path)
                location = None
                if locate and gps_lat and gps_lon:
                    location = geolocate(gps_lat, gps_lon)
                    # Don't save coordinate strings as location (treat as None to allow retry)
                    if location and is_coordinate_string(location):
                        location = None
                if date_taken:
                    # Always preserve location if computed (for future --locate runs)
                    # Use out_path (abspath) for output to preserve what user sees
                    photo_data.append((out_path, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location))
                else:
                    error_log.write(f"Warning: Could not extract date for '{out_path}'.\n")
            except OSError as e:
                error_log.write(f"Error: Could not access '{out_path}': {e}\n")
                # Check for drive disconnect
                if any(err in str(e).lower() for err in ['no such file', 'input/output error', 'stale file handle']):
                    print("\n\nWARNING: Drive may be disconnected! Saving progress...")
                    write_dates_to_file_atomic(output, photo_data)
                    print(f"Saved {len(photo_data)} files to '{output}'")
                    print("Reconnect drive and run again to resume.")
                    return False
                continue

            # Save checkpoint every 100 files or 5 minutes
            current_time = time.time()
            if (idx + 1) % 100 == 0 or (current_time - last_save_time) > 300:
                write_dates_to_file_atomic(output, photo_data)
                last_save_time = current_time
                if not quiet:
                    print(f"\n[Checkpoint: {len(photo_data)} files saved]", end="")

            # Update progress bar after processing (display after, not before)
            if not quiet and idx % 10 == 0:  # Update less frequently for better performance
                # Use idx + 1 since we display after processing (idx is 0-based, we've processed idx+1 files)
                progress_percentage = (idx + 1) / len(files_to_process) * 100
                progress_bar = '[' + '#' * int(progress_percentage // 5) + ' ' * (20 - int(progress_percentage // 5)) + ']'
                print(f"Progress: {progress_percentage:.2f}% {progress_bar}", end="\r")

    if not quiet:
        print("\nProcessing complete.                                        ")  # Extra spaces to clear progress bar

    # Write results to the output file atomically
    write_dates_to_file_atomic(output, photo_data)

    if not quiet:
        print(f"Dates written to '{output}' ({len(photo_data)} files listed).")
        if cached_count > 0:
            print(f"  ({cached_count} from cache, {len(photo_data) - cached_count} newly processed)")

    # Print summary of results
    summarize_results(photo_data, file_counts, quiet, debug)
    
    return True

def main():
    # If no arguments are provided, print helpful help
    if len(sys.argv) == 1:
        print("""
Find Photo Dates - A tool to index and geolocate your media collection.

This tool recursively scans directories for photos and videos, extracting their
creation dates using ExifTool. It allows you to organize your media by date
and location.

Key Features:
  - Extracts 'Date Taken' from EXIF metadata.
  - Supports common photo (JPG, NEF, ORF) and video (MP4, MOV, AVI, etc.) formats.
  - Caches results in a TSV file to speed up subsequent runs.
  - Can reverse geolocate files using GPS coordinates (--locate).
  - Can save and manage multiple scan configurations (--save, --scan).

Usage: findphotodates.py [options]

Options:
  --directory DIR    The directory to search (default: current directory).
  --output FILE      The output TSV file to save results (default: photo.dates.tsv).
  --locate           Attempt to reverse geolocate files using GPS coordinates.
  --video            Search for video files only.
  --only-photos      Search for photo files only.
  --extension EXT    Search for a specific file extension (e.g., --extension jpg).
  --save             Save the current scan configuration for later use.
  --scan             Run all saved scan configurations.
  --quiet            Run quietly (suppress normal output).
  --debug            Enable verbose debug output.
  --test             Run internal tests.

Examples:
  # Scan a specific folder and save to default output
  findphotodates.py --directory /home/user/Photos

  # Scan for videos only in the current directory
  findphotodates.py --video

  # Scan a backup drive and geolocate photos
  findphotodates.py --directory /Volumes/Backup --locate

  # Save this configuration to run later
  findphotodates.py --directory /Volumes/Backup --save

  # Run all previously saved scan configurations
  findphotodates.py --scan

For more details on a specific option, you can also use:
  findphotodates.py --help
""")
        return

    # Check exiftool availability at the very start
    try:
        result = subprocess.run(
            ["exiftool", "-ver"],
            capture_output=True,
            timeout=5
        )
        if result.returncode != 0:
            print("Error: ExifTool is required but the 'exiftool' command failed.")
            print("Please install ExifTool and ensure it's in your PATH.")
            return
    except FileNotFoundError:
        print("Error: ExifTool is required but was not found.")
        print("Please install ExifTool and ensure it's in your PATH.")
        print("  - macOS: brew install exiftool")
        print("  - Ubuntu/Debian: sudo apt-get install libimage-exiftool-perl")
        print("  - Windows: Download from https://exiftool.org/")
        return
    except subprocess.TimeoutExpired:
        print("Error: ExifTool check timed out. Please ensure exiftool is working correctly.")
        return
    except Exception as e:
        print(f"Error: Failed to check ExifTool availability: {e}")
        return
    
    # Set up argument parsing
    parser = argparse.ArgumentParser(
        description="Recursively find files with specified extensions and extract the date each file was created using exiftool."
    )
    parser.add_argument(
        "--directory",
        default=".",
        help="The directory to search (default: current directory)."
    )
    parser.add_argument(
        "-o", "--output", "--out",
        default="photo.dates.tsv",
        help="The output TSV file to save the results (default: photo.dates.tsv)."
    )
    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Run the script quietly without printing output unless there is an error."
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Run the script in debug mode, providing verbose output."
    )
    parser.add_argument(
        "--video",
        action="store_true",
        help="Search for video files (mp4, mov, avi, etc.) only."
    )
    parser.add_argument(
        "--only-photos",
        action="store_true",
        help="Search for photo files (jpg, jpeg, nef, orf) only."
    )
    parser.add_argument(
        "--extension",
        help="Specify a custom file extension to search for (overrides other extensions)."
    )
    parser.add_argument(
        "--locate",
        action="store_true",
        help="Attempt to locate files using GPS coordinates."
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run date parsing tests and exit."
    )
    parser.add_argument(
        "--save",
        action="store_true",
        help="Save current scan configuration for later use with --scan."
    )
    parser.add_argument(
        "--scan",
        action="store_true",
        help="Run all saved scan configurations."
    )

    args = parser.parse_args()
    
    # Handle --test early
    if args.test:
        test_date_parsing()
        return
    
    # Handle --save
    if args.save:
        # Expand user paths
        directory_abs = _expand_path(args.directory)
        output_abs = _expand_path(args.output)
        
        # Validate directory exists before saving
        if not os.path.exists(directory_abs):
            print(f"Error: Directory '{directory_abs}' does not exist.")
            print("Cannot save configuration for a non-existent directory.")
            return
        
        # Detect drive root and relative path
        drive_root, path_relative = detect_drive_root(directory_abs)
        drive_hint_value = get_drive_hint(drive_root)
        
        # Determine extensions
        if args.extension:
            extensions_list = [args.extension.lower()]
        elif args.video:
            extensions_list = sorted(list(VIDEO_EXTENSIONS))
        elif args.only_photos:
            extensions_list = sorted(list(PHOTO_EXTENSIONS))
        else:
            extensions_list = sorted(list(DEFAULT_EXTENSIONS))
        
        # Build flags dict
        flags = {
            "video": args.video,
            "only_photos": args.only_photos,
            "locate": args.locate,
            "quiet": args.quiet,
            "debug": args.debug,
            "extensions": extensions_list
        }
        
        # Load config
        config = load_config()
        
        # Check if entry exists - de-dupe by (drive_hint, path_relative, output_abs) if path_relative is non-empty
        # Otherwise fall back to directory_abs matching
        updated = False
        for entry in config["saved_scans"]:
            # Try de-duping by drive hint + relative path + output (better for remounts)
            if path_relative and entry.get("path_relative") == path_relative:
                if (entry.get("drive_hint", {}).get("value") == drive_hint_value and 
                    entry.get("output_abs") == output_abs):
                    # Update existing entry
                    entry["directory_abs"] = directory_abs  # Update to current path
                    entry["flags"] = flags
                    updated = True
                    break
            # Fallback to directory_abs matching
            elif entry.get("directory_abs") == directory_abs:
                # Update existing entry
                entry["path_relative"] = path_relative
                entry["output_abs"] = output_abs
                entry["flags"] = flags
                entry["drive_hint"] = {"kind": "volume_label_or_root", "value": drive_hint_value}
                updated = True
                break
        
        if not updated:
            # Add new entry
            new_entry = {
                "id": "",  # Optional, can be set later
                "drive_hint": {"kind": "volume_label_or_root", "value": drive_hint_value},
                "directory_abs": directory_abs,
                "path_relative": path_relative,
                "output_abs": output_abs,
                "flags": flags
            }
            config["saved_scans"].append(new_entry)
        
        # Save config
        save_config(config)
        
        if not args.quiet:
            action = "Updated" if updated else "Saved"
            print(f"{action} scan configuration:")
            print(f"  Directory: {directory_abs}")
            print(f"  Output: {output_abs}")
            print(f"  Config file: {CONFIG_FILE}")
        
        # If --scan is also set, skip single scan and go to --scan block
        if args.scan:
            # Will be handled below
            pass
        else:
            # Continue to run the scan (don't return early)
            # Determine the extensions to use
            if args.extension:
                extensions = {args.extension.lower()}
            elif args.video:
                extensions = VIDEO_EXTENSIONS
            elif args.only_photos:
                extensions = PHOTO_EXTENSIONS
            else:
                extensions = DEFAULT_EXTENSIONS
            
            # Run the scan
            run_scan(directory_abs, output_abs, extensions, args.locate, args.quiet, args.debug)
            return
    
    # Handle --scan
    if args.scan:
        config = load_config()
        
        if not config.get("saved_scans"):
            print("No saved scan configurations found.")
            print(f"Use --save to save a scan configuration. Config file: {CONFIG_FILE}")
            return
        
        print(f"Running {len(config['saved_scans'])} saved scan(s)...")
        
        for idx, entry in enumerate(config["saved_scans"], 1):
            resolved_dir = resolve_saved_directory(entry)
            
            if not resolved_dir or not os.path.exists(resolved_dir):
                entry_id = entry.get("id") or entry.get("directory_abs", "unknown")
                print(f"\n[{idx}/{len(config['saved_scans'])}] Skipping {entry_id}: directory not found")
                continue
            
            print(f"\n[{idx}/{len(config['saved_scans'])}] Scanning: {resolved_dir}")
            
            # Extract flags
            flags = entry.get("flags", {})
            locate = flags.get("locate", False)
            quiet = flags.get("quiet", False)
            debug = flags.get("debug", False)
            
            # Determine extensions
            if flags.get("extensions") and len(flags["extensions"]) > 0:
                extensions = set(flags["extensions"])
            elif flags.get("video"):
                extensions = VIDEO_EXTENSIONS
            elif flags.get("only_photos"):
                extensions = PHOTO_EXTENSIONS
            else:
                extensions = DEFAULT_EXTENSIONS
            
            # Run scan
            try:
                output = entry.get("output_abs", "photo.dates.tsv")
                success = run_scan(resolved_dir, output, extensions, locate, quiet, debug)
                if not success:
                    print(f"  Error: Scan failed for {resolved_dir}")
            except Exception as e:
                print(f"  Error: {e}")
                if debug:
                    import traceback
                    traceback.print_exc()
        
        print("\nAll scans complete.")
        return

    # Normal operation: run a single scan
    # Expand user paths
    directory_abs = _expand_path(args.directory)
    output_abs = _expand_path(args.output)
    
    # Determine the extensions to use
    if args.extension:
        extensions = {args.extension.lower()}
    elif args.video:
        extensions = VIDEO_EXTENSIONS
    elif args.only_photos:
        extensions = PHOTO_EXTENSIONS
    else:
        extensions = DEFAULT_EXTENSIONS
    
    # Run the scan
    run_scan(directory_abs, output_abs, extensions, args.locate, args.quiet, args.debug)

def test_date_parsing():
    """Test function to verify date parsing and aggregation works correctly."""
    from collections import Counter, defaultdict
    
    # Test data with exiftool date format - using 7-tuples matching main code structure
    # (filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location)
    test_photo_data = [
        ("/path/to/file1.jpg", "2025:12:31 23:59:59", 1000, 1234567890, "37.7749", "-122.4194", None),
        ("/path/to/file2.jpg", "2025:12:31 12:00:00", 2000, 1234567891, "34.0522", "-118.2437", None),
        ("/path/to/file3.jpg", "2025:12:30 10:30:00", 3000, 1234567892, None, None, None),
        ("/path/to/file4.jpg", "2025:11:15 08:15:00", 4000, 1234567893, "40.7128", "-74.0060", None),
        ("/path/to/file5.jpg", "2025:11:15 20:45:00", 5000, 1234567894, None, None, None),
        ("/path/to/file6.jpg", None, 6000, 1234567895, None, None, None),  # No date
        ("/path/to/file7.jpg", "invalid-date", 7000, 1234567896, None, None, None),  # Invalid date
    ]
    
    file_counts = Counter({"jpg": 7})
    
    # Test date parsing
    date_counter = Counter()
    for entry in test_photo_data:
        # Entry is a tuple: (filepath, date_taken, size_bytes, mtime_ns, gps_lat, gps_lon, location)
        date_str = entry[1] if len(entry) > 1 else None
        if not date_str:
            continue
        try:
            dt = datetime.strptime(date_str, "%Y:%m:%d %H:%M:%S")
            day_key = dt.strftime("%Y-%m-%d")
            date_counter[day_key] += 1
        except (ValueError, AttributeError, TypeError):
            continue
    
    # Verify day aggregation
    assert date_counter["2025-12-31"] == 2, f"Expected 2 files on 2025-12-31, got {date_counter.get('2025-12-31', 0)}"
    assert date_counter["2025-12-30"] == 1, f"Expected 1 file on 2025-12-30, got {date_counter.get('2025-12-30', 0)}"
    assert date_counter["2025-11-15"] == 2, f"Expected 2 files on 2025-11-15, got {date_counter.get('2025-11-15', 0)}"
    
    # Test month aggregation
    month_counter = defaultdict(int)
    for day_key in date_counter:
        try:
            dt = datetime.strptime(day_key, "%Y-%m-%d")
            year_month_key = dt.strftime("%Y-%m")
            month_counter[year_month_key] += date_counter[day_key]
        except (ValueError, AttributeError):
            continue
    
    assert month_counter["2025-12"] == 3, f"Expected 3 files in 2025-12, got {month_counter.get('2025-12', 0)}"
    assert month_counter["2025-11"] == 2, f"Expected 2 files in 2025-11, got {month_counter.get('2025-11', 0)}"
    
    print("✓ All date parsing tests passed!")
    print(f"  Day aggregation: {dict(date_counter)}")
    print(f"  Month aggregation: {dict(month_counter)}")

if __name__ == "__main__":
    main()
