#!/usr/bin/env python3
"""
Comprehensive safety tests for check_photo_backups.py and findphotodates.py.

Covers:
- Inventory parsing (iter_inventory_rows): valid TSV, missing header, OLD format,
  corrupt data, non-hex hashes, negative sizes
- Safe-to-delete classification (classify_safe_to_delete): every safety value
- Hash config comparison (parse_config_str)
- add_hashes_to_inventory header validation
- Path normalization (resolve_inventory_display_path)

Run with: python3 test_safety.py
Or with:  python3 -m pytest test_safety.py -v
"""

import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

# Ensure the project root is importable
sys.path.insert(0, str(Path(__file__).parent))

from check_photo_backups import (
    SAFE_SAFETY_VALUES,
    classify_safe_to_delete,
    iter_inventory_rows,
    parse_config_str,
    resolve_inventory_display_path,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_tsv(tmp_dir, lines, name="inv.tsv"):
    """Write lines (joined by newline) to a file and return its Path."""
    p = Path(tmp_dir) / name
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


def _make_tsv_rows(rows, headers=None):
    """Build a complete TSV file as a list of lines with comment headers and column header."""
    lines = []
    if headers:
        for k, v in headers.items():
            if k in ("samplehash_v1", "fullhash"):
                lines.append(f"# {k} {v}")
            else:
                lines.append(f"# {k}={v}")
    lines.append("# Generated by findphotodates.py")
    lines.append("\t".join(["filepath", "date_taken", "size_bytes", "mtime_ns",
                            "gps_lat", "gps_lon", "location", "content_hash"]))
    for row in rows:
        lines.append("\t".join(row))
    return lines


# ===========================================================================
# iter_inventory_rows
# ===========================================================================

class TestIterInventoryRows(unittest.TestCase):
    """Tests for the inventory parser."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_valid_tsv(self):
        """Standard 8-column TSV with header — should parse correctly."""
        lines = _make_tsv_rows([
            ["/photos/a.jpg", "2024:01:01 12:00:00", "1234", "1700000000000000000",
             "37.7", "-122.4", "", "abcdef01"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        filepath, date, size, mtime, chash, hdrs = results[0]
        self.assertEqual(filepath, "/photos/a.jpg")
        self.assertEqual(date, "2024:01:01 12:00:00")
        self.assertEqual(size, 1234)
        self.assertEqual(mtime, 1700000000000000000)
        self.assertEqual(chash, "abcdef01")

    def test_valid_tsv_blank_hash(self):
        """Rows with blank content_hash should yield empty string, not None."""
        lines = _make_tsv_rows([
            ["/photos/b.jpg", "2024:02:01 08:00:00", "5678", "1700000000000000001",
             "", "", "", ""],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][4], "")

    def test_rejects_tsv_without_header(self):
        """TSV data without a 'filepath' header row must be rejected entirely."""
        lines = [
            "# inventory_root=/photos",
            "# Generated by findphotodates.py",
            "/photos/a.jpg\t2024:01:01\t1234\t170000\t\t\t\tabcdef",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results, [], "Should yield nothing when TSV header is missing")

    def test_non_hex_hash_treated_as_empty(self):
        """Non-hex content_hash values must be treated as empty (not matched)."""
        lines = _make_tsv_rows([
            ["/photos/c.jpg", "2024:01:01 12:00:00", "1000", "1700000000000000000",
             "", "", "", "NOT_A_HEX_HASH"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][4], "", "Non-hex hash should be treated as empty")

    def test_negative_size_treated_as_none(self):
        """Negative size_bytes should be treated as None (unknown)."""
        lines = _make_tsv_rows([
            ["/photos/d.jpg", "2024:01:01 12:00:00", "-5", "1700000000000000000",
             "", "", "", "aabb"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv, debug=True))
        self.assertEqual(len(results), 1)
        self.assertIsNone(results[0][2], "Negative size should become None")

    def test_non_numeric_size_treated_as_none(self):
        """Non-numeric size_bytes should become None."""
        lines = _make_tsv_rows([
            ["/photos/e.jpg", "2024:01:01 12:00:00", "notanumber", "1700000000000000000",
             "", "", "", ""],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertIsNone(results[0][2])

    def test_old_format(self):
        """OLD format lines (./path: YYYY:MM:DD HH:MM:SS) should parse."""
        lines = [
            "./photos/old.jpg: 2020:06:15 09:30:00",
            "./photos/old2.jpg: 2021:12:25 18:00:00",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 2)
        self.assertEqual(results[0][0], "./photos/old.jpg")
        self.assertEqual(results[0][1], "2020:06:15 09:30:00")
        self.assertIsNone(results[0][2])
        self.assertEqual(results[0][4], "")

    def test_headers_parsed(self):
        """Comment headers (# key=value) should be available in yielded tuples."""
        lines = _make_tsv_rows(
            [["/a.jpg", "", "100", "1000", "", "", "", ""]],
            headers={"inventory_root": "/mnt/drive1", "hash_mode": "sample"},
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        hdrs = results[0][5]
        self.assertEqual(hdrs["inventory_root"], "/mnt/drive1")
        self.assertEqual(hdrs["hash_mode"], "sample")

    def test_samplehash_config_header(self):
        """samplehash_v1 config line should be parsed into headers."""
        lines = [
            "# content_hash_format=samplehash_v1",
            "# samplehash_v1 algo=blake3 chunks=3 chunk_mib=0.0625",
            "# Generated by findphotodates.py",
            "filepath\tdate_taken\tsize_bytes\tmtime_ns\tgps_lat\tgps_lon\tlocation\tcontent_hash",
            "/a.jpg\t\t100\t1000\t\t\t\taabb",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        hdrs = results[0][5]
        self.assertIn("samplehash_v1", hdrs)
        self.assertIn("algo=blake3", hdrs["samplehash_v1"])

    def test_empty_filepath_rows_skipped(self):
        """Rows with empty filepath should be silently skipped."""
        lines = _make_tsv_rows([
            ["", "2024:01:01 12:00:00", "100", "1000", "", "", "", "aabb"],
            ["/valid.jpg", "2024:01:01 12:00:00", "200", "2000", "", "", "", "ccdd"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][0], "/valid.jpg")

    def test_zero_size_is_valid(self):
        """Size 0 is a valid file size (e.g., empty file)."""
        lines = _make_tsv_rows([
            ["/empty.jpg", "", "0", "1000", "", "", "", ""],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results[0][2], 0)

    def test_uppercase_hex_hash_accepted(self):
        """Uppercase hex hashes should be accepted."""
        lines = _make_tsv_rows([
            ["/a.jpg", "", "100", "1000", "", "", "", "AABBCCDD"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results[0][4], "AABBCCDD")

    def test_hash_with_spaces_treated_as_empty(self):
        """Hash containing spaces (likely corrupt) should be treated as empty."""
        lines = _make_tsv_rows([
            ["/a.jpg", "", "100", "1000", "", "", "", "aabb ccdd"],
        ])
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results[0][4], "", "Hash with spaces should be treated as empty")


# ===========================================================================
# classify_safe_to_delete
# ===========================================================================

class TestClassifySafeToDelete(unittest.TestCase):
    """Every safety value must be explicitly tested."""

    def test_verified_hash_is_safe(self):
        self.assertTrue(classify_safe_to_delete("verified_hash"))

    def test_strong_nohash_allowed_is_safe(self):
        self.assertTrue(classify_safe_to_delete("strong_nohash_allowed"))

    def test_weak_nohash_allowed_is_safe(self):
        self.assertTrue(classify_safe_to_delete("weak_nohash_allowed"))

    def test_strong_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("strong"))

    def test_weak_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("weak"))

    def test_name_date_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("name_date"))

    def test_name_only_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("name_only"))

    def test_missing_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("missing"))

    def test_hash_config_mismatch_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("hash_config_mismatch"))

    def test_empty_string_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete(""))

    def test_unknown_value_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("something_new"))

    def test_safe_values_frozenset_matches(self):
        """Ensure the constant and the function agree."""
        for v in SAFE_SAFETY_VALUES:
            self.assertTrue(classify_safe_to_delete(v), f"{v} should be safe")


# ===========================================================================
# parse_config_str
# ===========================================================================

class TestParseConfigStr(unittest.TestCase):
    def test_basic(self):
        self.assertEqual(
            parse_config_str("algo=blake3 chunks=3 chunk_mib=0.0625"),
            {"algo": "blake3", "chunks": "3", "chunk_mib": "0.0625"},
        )

    def test_empty(self):
        self.assertEqual(parse_config_str(""), {})

    def test_single_pair(self):
        self.assertEqual(parse_config_str("algo=sha256"), {"algo": "sha256"})


# ===========================================================================
# resolve_inventory_display_path
# ===========================================================================

class TestResolveInventoryDisplayPath(unittest.TestCase):
    def test_absolute_path_unchanged(self):
        result = resolve_inventory_display_path("/mnt/drive/photo.jpg", None)
        self.assertEqual(result, os.path.normpath("/mnt/drive/photo.jpg"))

    def test_relative_with_root(self):
        result = resolve_inventory_display_path("./subdir/photo.jpg", "/mnt/drive")
        self.assertEqual(result, os.path.normpath("/mnt/drive/subdir/photo.jpg"))

    def test_relative_no_root(self):
        result = resolve_inventory_display_path("./photo.jpg", None)
        self.assertEqual(result, os.path.normpath("./photo.jpg"))

    def test_windows_path_on_posix(self):
        result = resolve_inventory_display_path("C:\\Users\\alan\\photo.jpg", None)
        self.assertIn("photo.jpg", result)


# ===========================================================================
# add_hashes_to_inventory header validation
# ===========================================================================

class TestAddHashesHeaderValidation(unittest.TestCase):
    """Test that add_hashes_to_inventory rejects files without proper header."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_rejects_non_tsv_header(self):
        """A file whose first non-comment line doesn't start with 'filepath' should be rejected."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "bad.tsv"
        inv.write_text(
            "# Generated by findphotodates.py\n"
            "not_filepath\tdate\tsize\n"
            "/a.jpg\t2024:01:01\t100\n",
            encoding="utf-8",
        )

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertFalse(result, "Should reject TSV with wrong header")

    def test_accepts_valid_header(self):
        """A file with a proper 'filepath' header and no data rows should return True."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "good.tsv"
        inv.write_text(
            "# Generated by findphotodates.py\n"
            "filepath\tdate_taken\tsize_bytes\tmtime_ns\tgps_lat\tgps_lon\tlocation\tcontent_hash\n",
            encoding="utf-8",
        )

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertTrue(result, "Should accept TSV with valid header and no data")

    def test_rejects_empty_file(self):
        """An empty file has no data rows — should return True (nothing to do)."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "empty.tsv"
        inv.write_text("", encoding="utf-8")

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertTrue(result)


# ===========================================================================
# Integration: end-to-end safe-to-delete decisions
# ===========================================================================

class TestSafeToDeleteIntegration(unittest.TestCase):
    """Verify that the full matching logic produces correct safety values.

    These tests exercise the matching pipeline by building in-memory lookup dicts
    (the same structures main() builds) and simulating the classification.
    """

    def _classify(self, target_hash, target_size, target_name, target_date,
                  hash_drives, strong_drives, weak_drives,
                  hash_configs_per_key=None,
                  allow_strong=False, allow_weak=False,
                  allow_hash_config_mismatch=False,
                  sample_chunk_mib=0.0625, sample_chunks=3, sample_algo="blake2b"):
        """Simulate the matching logic from main()."""
        match_type, safety, drives = "missing", "missing", set()

        if target_hash:
            hk = (target_size, target_hash)
            if hk in hash_drives:
                inv_cfgs = (hash_configs_per_key or {}).get(hk, set())
                config_match = False
                if not inv_cfgs:
                    if allow_hash_config_mismatch:
                        config_match = True
                else:
                    for inv_cfg in inv_cfgs:
                        if inv_cfg.startswith("mode=full"):
                            config_match = True
                            break
                        inv_s = parse_config_str(inv_cfg)
                        m = True
                        for k in ["algo", "chunks", "chunk_mib"]:
                            if k in inv_s and k == "chunk_mib":
                                try:
                                    if abs(float(inv_s[k]) - sample_chunk_mib) > 0.001:
                                        m = False
                                        break
                                except ValueError:
                                    m = False
                                    break
                            elif k in inv_s and inv_s[k] != (sample_algo if k == "algo" else str(sample_chunks)):
                                m = False
                                break
                        if m:
                            config_match = True
                            break

                if config_match or allow_hash_config_mismatch:
                    drives = hash_drives[hk]
                    match_type = safety = "verified_hash"
                else:
                    safety = "hash_config_mismatch"

        if not drives:
            sk = (target_name, target_size, target_date)
            wk = (target_name, target_size)
            if target_date and sk in strong_drives:
                drives = strong_drives[sk]
                match_type = "strong"
                if safety in ("missing", "hash_config_mismatch"):
                    safety = "strong_nohash_allowed" if allow_strong else "strong"
            elif wk in weak_drives:
                drives = weak_drives[wk]
                match_type = "weak"
                if safety in ("missing", "hash_config_mismatch"):
                    safety = "weak_nohash_allowed" if allow_weak else "weak"

        return safety, match_type, classify_safe_to_delete(safety)

    def test_verified_hash_match(self):
        """File with matching hash in inventory -> verified_hash -> safe."""
        safety, _, safe = self._classify(
            target_hash="aabb", target_size=1000, target_name="a.jpg", target_date="",
            hash_drives={(1000, "aabb"): {"drive1"}},
            strong_drives={}, weak_drives={},
            hash_configs_per_key={(1000, "aabb"): {"algo=blake2b chunks=3 chunk_mib=0.0625"}},
        )
        self.assertEqual(safety, "verified_hash")
        self.assertTrue(safe)

    def test_hash_config_mismatch_not_safe(self):
        """Hash matches but config differs -> hash_config_mismatch -> NOT safe."""
        safety, _, safe = self._classify(
            target_hash="aabb", target_size=1000, target_name="a.jpg", target_date="",
            hash_drives={(1000, "aabb"): {"drive1"}},
            strong_drives={}, weak_drives={},
            hash_configs_per_key={(1000, "aabb"): {"algo=sha256 chunks=3 chunk_mib=1.0"}},
        )
        self.assertEqual(safety, "hash_config_mismatch")
        self.assertFalse(safe)

    def test_strong_match_not_safe_by_default(self):
        """Strong match (name+size+date) without --allow-strong -> NOT safe."""
        safety, _, safe = self._classify(
            target_hash="", target_size=1000, target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
        )
        self.assertEqual(safety, "strong")
        self.assertFalse(safe)

    def test_strong_match_safe_with_flag(self):
        """Strong match + --allow-strong-without-hash -> safe."""
        safety, _, safe = self._classify(
            target_hash="", target_size=1000, target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
            allow_strong=True,
        )
        self.assertEqual(safety, "strong_nohash_allowed")
        self.assertTrue(safe)

    def test_weak_match_not_safe_by_default(self):
        """Weak match (name+size) -> NOT safe without flag."""
        safety, _, safe = self._classify(
            target_hash="", target_size=1000, target_name="a.jpg", target_date="",
            hash_drives={},
            strong_drives={},
            weak_drives={("a.jpg", 1000): {"drive1"}},
        )
        self.assertEqual(safety, "weak")
        self.assertFalse(safe)

    def test_weak_match_safe_with_flag(self):
        """Weak match + --allow-weak-without-hash -> safe."""
        safety, _, safe = self._classify(
            target_hash="", target_size=1000, target_name="a.jpg", target_date="",
            hash_drives={},
            strong_drives={},
            weak_drives={("a.jpg", 1000): {"drive1"}},
            allow_weak=True,
        )
        self.assertEqual(safety, "weak_nohash_allowed")
        self.assertTrue(safe)

    def test_no_match_is_missing(self):
        """File not found in any inventory -> missing -> NOT safe."""
        safety, _, safe = self._classify(
            target_hash="", target_size=1000, target_name="unknown.jpg", target_date="",
            hash_drives={}, strong_drives={}, weak_drives={},
        )
        self.assertEqual(safety, "missing")
        self.assertFalse(safe)

    def test_full_hash_config_always_matches(self):
        """Inventory with mode=full config should always be considered a config match."""
        safety, _, safe = self._classify(
            target_hash="aabb", target_size=1000, target_name="a.jpg", target_date="",
            hash_drives={(1000, "aabb"): {"drive1"}},
            strong_drives={}, weak_drives={},
            hash_configs_per_key={(1000, "aabb"): {"mode=full algo=sha256"}},
        )
        self.assertEqual(safety, "verified_hash")
        self.assertTrue(safe)

    def test_hash_mismatch_falls_through_to_strong(self):
        """Hash config mismatch should still fall through to strong match if available."""
        safety, mt, safe = self._classify(
            target_hash="aabb", target_size=1000, target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={(1000, "aabb"): {"drive1"}},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
            hash_configs_per_key={(1000, "aabb"): {"algo=sha256 chunks=3 chunk_mib=1.0"}},
        )
        # Should fall through: hash_config_mismatch -> try strong -> strong (not safe)
        self.assertEqual(safety, "strong")
        self.assertEqual(mt, "strong")
        self.assertFalse(safe)

    def test_hash_mismatch_with_allow_strong(self):
        """Hash config mismatch + --allow-strong -> strong_nohash_allowed -> safe."""
        safety, _, safe = self._classify(
            target_hash="aabb", target_size=1000, target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={(1000, "aabb"): {"drive1"}},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
            hash_configs_per_key={(1000, "aabb"): {"algo=sha256 chunks=3 chunk_mib=1.0"}},
            allow_strong=True,
        )
        self.assertEqual(safety, "strong_nohash_allowed")
        self.assertTrue(safe)


if __name__ == "__main__":
    unittest.main()
