#!/usr/bin/env python3
"""
Comprehensive safety tests for check_photo_backups.py and findphotodates.py.

Covers:
- Inventory parsing (iter_inventory_rows): valid TSV, missing header, OLD format,
  corrupt data, non-hex hashes, negative sizes
- Safe-to-delete classification (classify_safe_to_delete): every safety value
- Hash config comparison (parse_config_str)
- add_hashes_to_inventory header validation
- Path normalization (resolve_inventory_display_path)

Run with: python3 test_safety.py
Or with:  python3 -m pytest test_safety.py -v
"""

import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

# Ensure the project root is importable
sys.path.insert(0, str(Path(__file__).parent))

from check_photo_backups import (
    InvHashConfig,
    SAFE_SAFETY_VALUES,
    classify_safe_to_delete,
    iter_inventory_rows,
    parse_config_str,
    resolve_inventory_display_path,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write_tsv(tmp_dir, lines, name="inv.tsv"):
    """Write lines (joined by newline) to a file and return its Path."""
    p = Path(tmp_dir) / name
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


def _make_tsv_rows(rows, headers=None):
    """Build a complete TSV file as a list of lines with comment headers and column header."""
    lines = []
    if headers:
        for k, v in headers.items():
            if k in ("samplehash_v1", "fullhash"):
                lines.append(f"# {k} {v}")
            else:
                lines.append(f"# {k}={v}")
    lines.append("# Generated by findphotodates.py")
    lines.append(
        "\t".join(
            [
                "filepath",
                "date_taken",
                "size_bytes",
                "mtime_ns",
                "gps_lat",
                "gps_lon",
                "location",
                "content_hash",
            ]
        )
    )
    for row in rows:
        lines.append("\t".join(row))
    return lines


# ===========================================================================
# iter_inventory_rows
# ===========================================================================


class TestIterInventoryRows(unittest.TestCase):
    """Tests for the inventory parser."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_valid_tsv(self):
        """Standard 8-column TSV with header — should parse correctly."""
        lines = _make_tsv_rows(
            [
                [
                    "/photos/a.jpg",
                    "2024:01:01 12:00:00",
                    "1234",
                    "1700000000000000000",
                    "37.7",
                    "-122.4",
                    "",
                    "abcdef01",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        filepath, date, size, mtime, chash, _hdrs = results[0]
        self.assertEqual(filepath, "/photos/a.jpg")
        self.assertEqual(date, "2024:01:01 12:00:00")
        self.assertEqual(size, 1234)
        self.assertEqual(mtime, 1700000000000000000)
        self.assertEqual(chash, "abcdef01")

    def test_valid_tsv_blank_hash(self):
        """Rows with blank content_hash should yield empty string, not None."""
        lines = _make_tsv_rows(
            [
                [
                    "/photos/b.jpg",
                    "2024:02:01 08:00:00",
                    "5678",
                    "1700000000000000001",
                    "",
                    "",
                    "",
                    "",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][4], "")

    def test_rejects_tsv_without_header(self):
        """TSV data without a 'filepath' header row must be rejected entirely."""
        lines = [
            "# inventory_root=/photos",
            "# Generated by findphotodates.py",
            "/photos/a.jpg\t2024:01:01\t1234\t170000\t\t\t\tabcdef",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results, [], "Should yield nothing when TSV header is missing")

    def test_non_hex_hash_treated_as_empty(self):
        """Non-hex content_hash values must be treated as empty (not matched)."""
        lines = _make_tsv_rows(
            [
                [
                    "/photos/c.jpg",
                    "2024:01:01 12:00:00",
                    "1000",
                    "1700000000000000000",
                    "",
                    "",
                    "",
                    "NOT_A_HEX_HASH",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][4], "", "Non-hex hash should be treated as empty")

    def test_negative_size_treated_as_none(self):
        """Negative size_bytes should be treated as None (unknown)."""
        lines = _make_tsv_rows(
            [
                [
                    "/photos/d.jpg",
                    "2024:01:01 12:00:00",
                    "-5",
                    "1700000000000000000",
                    "",
                    "",
                    "",
                    "aabb",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv, debug=True))
        self.assertEqual(len(results), 1)
        self.assertIsNone(results[0][2], "Negative size should become None")

    def test_non_numeric_size_treated_as_none(self):
        """Non-numeric size_bytes should become None."""
        lines = _make_tsv_rows(
            [
                [
                    "/photos/e.jpg",
                    "2024:01:01 12:00:00",
                    "notanumber",
                    "1700000000000000000",
                    "",
                    "",
                    "",
                    "",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertIsNone(results[0][2])

    def test_old_format(self):
        """OLD format lines (./path: YYYY:MM:DD HH:MM:SS) should parse."""
        lines = [
            "./photos/old.jpg: 2020:06:15 09:30:00",
            "./photos/old2.jpg: 2021:12:25 18:00:00",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 2)
        self.assertEqual(results[0][0], "./photos/old.jpg")
        self.assertEqual(results[0][1], "2020:06:15 09:30:00")
        self.assertIsNone(results[0][2])
        self.assertEqual(results[0][4], "")

    def test_headers_parsed(self):
        """Comment headers (# key=value) should be available in yielded tuples."""
        lines = _make_tsv_rows(
            [["/a.jpg", "", "100", "1000", "", "", "", ""]],
            headers={"inventory_root": "/mnt/drive1", "hash_mode": "sample"},
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        hdrs = results[0][5]
        self.assertEqual(hdrs["inventory_root"], "/mnt/drive1")
        self.assertEqual(hdrs["hash_mode"], "sample")

    def test_samplehash_config_header(self):
        """samplehash_v1 config line should be parsed into headers."""
        lines = [
            "# content_hash_format=samplehash_v1",
            "# samplehash_v1 algo=blake3 chunks=3 chunk_mib=0.0625",
            "# Generated by findphotodates.py",
            "filepath\tdate_taken\tsize_bytes\tmtime_ns\tgps_lat\tgps_lon\tlocation\tcontent_hash",
            "/a.jpg\t\t100\t1000\t\t\t\taabb",
        ]
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        hdrs = results[0][5]
        self.assertIn("samplehash_v1", hdrs)
        self.assertIn("algo=blake3", hdrs["samplehash_v1"])

    def test_empty_filepath_rows_skipped(self):
        """Rows with empty filepath should be silently skipped."""
        lines = _make_tsv_rows(
            [
                ["", "2024:01:01 12:00:00", "100", "1000", "", "", "", "aabb"],
                [
                    "/valid.jpg",
                    "2024:01:01 12:00:00",
                    "200",
                    "2000",
                    "",
                    "",
                    "",
                    "ccdd",
                ],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0][0], "/valid.jpg")

    def test_zero_size_is_valid(self):
        """Size 0 is a valid file size (e.g., empty file)."""
        lines = _make_tsv_rows(
            [
                ["/empty.jpg", "", "0", "1000", "", "", "", ""],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results[0][2], 0)

    def test_column_count_mismatch_skipped(self):
        """Rows with wrong number of columns should be skipped."""
        lines = _make_tsv_rows(
            [
                # Valid row (8 columns)
                [
                    "/photos/a.jpg",
                    "2024:01:01 12:00:00",
                    "1234",
                    "1700000000000000000",
                    "37.7",
                    "-122.4",
                    "",
                    "abcdef01",
                ],
            ]
        )
        # Append a malformed row with only 3 columns
        lines.append("/photos/bad.jpg\t2024:01:01\t999")
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv, debug=True))
        self.assertEqual(len(results), 1, "Malformed row should be skipped")
        self.assertEqual(results[0][0], "/photos/a.jpg")

    def test_uppercase_hex_hash_accepted(self):
        """Uppercase hex hashes should be accepted."""
        lines = _make_tsv_rows(
            [
                ["/a.jpg", "", "100", "1000", "", "", "", "AABBCCDD"],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(results[0][4], "AABBCCDD")

    def test_hash_with_spaces_treated_as_empty(self):
        """Hash containing spaces (likely corrupt) should be treated as empty."""
        lines = _make_tsv_rows(
            [
                ["/a.jpg", "", "100", "1000", "", "", "", "aabb ccdd"],
            ]
        )
        inv = _write_tsv(self.tmp, lines)
        results = list(iter_inventory_rows(inv))
        self.assertEqual(
            results[0][4], "", "Hash with spaces should be treated as empty"
        )


# ===========================================================================
# classify_safe_to_delete
# ===========================================================================


class TestClassifySafeToDelete(unittest.TestCase):
    """Every safety value must be explicitly tested."""

    def test_verified_hash_is_safe(self):
        self.assertTrue(classify_safe_to_delete("verified_hash"))

    def test_strong_nohash_allowed_is_safe(self):
        self.assertTrue(classify_safe_to_delete("strong_nohash_allowed"))

    def test_weak_nohash_allowed_is_safe(self):
        self.assertTrue(classify_safe_to_delete("weak_nohash_allowed"))

    def test_strong_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("strong"))

    def test_weak_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("weak"))

    def test_name_date_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("name_date"))

    def test_name_only_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("name_only"))

    def test_missing_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("missing"))

    def test_hash_config_mismatch_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("hash_config_mismatch"))

    def test_empty_string_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete(""))

    def test_unknown_value_is_not_safe(self):
        self.assertFalse(classify_safe_to_delete("something_new"))

    def test_safe_values_frozenset_matches(self):
        """Ensure the constant and the function agree."""
        for v in SAFE_SAFETY_VALUES:
            self.assertTrue(classify_safe_to_delete(v), f"{v} should be safe")


# ===========================================================================
# parse_config_str
# ===========================================================================


class TestParseConfigStr(unittest.TestCase):
    def test_basic(self):
        self.assertEqual(
            parse_config_str("algo=blake3 chunks=3 chunk_mib=0.0625"),
            {"algo": "blake3", "chunks": "3", "chunk_mib": "0.0625"},
        )

    def test_empty(self):
        self.assertEqual(parse_config_str(""), {})

    def test_single_pair(self):
        self.assertEqual(parse_config_str("algo=sha256"), {"algo": "sha256"})


# ===========================================================================
# resolve_inventory_display_path
# ===========================================================================


class TestResolveInventoryDisplayPath(unittest.TestCase):
    def test_absolute_path_unchanged(self):
        result = resolve_inventory_display_path("/mnt/drive/photo.jpg", None)
        self.assertEqual(result, os.path.normpath("/mnt/drive/photo.jpg"))

    def test_relative_with_root(self):
        result = resolve_inventory_display_path("./subdir/photo.jpg", "/mnt/drive")
        self.assertEqual(result, os.path.normpath("/mnt/drive/subdir/photo.jpg"))

    def test_relative_no_root(self):
        result = resolve_inventory_display_path("./photo.jpg", None)
        self.assertEqual(result, os.path.normpath("./photo.jpg"))

    def test_windows_path_on_posix(self):
        result = resolve_inventory_display_path("C:\\Users\\alan\\photo.jpg", None)
        self.assertIn("photo.jpg", result)


# ===========================================================================
# add_hashes_to_inventory header validation
# ===========================================================================


class TestAddHashesHeaderValidation(unittest.TestCase):
    """Test that add_hashes_to_inventory rejects files without proper header."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_rejects_non_tsv_header(self):
        """A file whose first non-comment line doesn't start with 'filepath' should be rejected."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "bad.tsv"
        inv.write_text(
            "# Generated by findphotodates.py\n"
            "not_filepath\tdate\tsize\n"
            "/a.jpg\t2024:01:01\t100\n",
            encoding="utf-8",
        )

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertFalse(result, "Should reject TSV with wrong header")

    def test_accepts_valid_header(self):
        """A file with a proper 'filepath' header and no data rows should return True."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "good.tsv"
        inv.write_text(
            "# Generated by findphotodates.py\n"
            "filepath\tdate_taken\tsize_bytes\tmtime_ns\tgps_lat\tgps_lon\tlocation\tcontent_hash\n",
            encoding="utf-8",
        )

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertTrue(result, "Should accept TSV with valid header and no data")

    def test_rejects_empty_file(self):
        """An empty file has no data rows — should return True (nothing to do)."""
        from findphotodates import add_hashes_to_inventory, parse_hash_args

        inv = Path(self.tmp) / "empty.tsv"
        inv.write_text("", encoding="utf-8")

        hash_opts = parse_hash_args(hash_mode="sample")
        result = add_hashes_to_inventory(str(inv), hash_opts, quiet=True)
        self.assertTrue(result)


# ===========================================================================
# Integration: end-to-end safe-to-delete decisions
# ===========================================================================


class TestSafeToDeleteIntegration(unittest.TestCase):
    """Verify that the matching logic produces correct safety values.

    These tests use config-keyed hash_drives — the same structure main() builds —
    so they exercise the real proof chain: a verified_hash requires that both the
    InvHashConfig and digest match.
    """

    # Two distinct configs used throughout the tests.
    CFG_SAMPLE_B2 = InvHashConfig("sample", "blake2b", 3, 65536)
    CFG_SAMPLE_S256 = InvHashConfig("sample", "sha256", 3, 65536)
    CFG_FULL_S256 = InvHashConfig("full", "sha256", 0, 0)

    # NOTE: This is an intentional test-only reimplementation of the matching
    # logic from check_photo_backups.py::main().  It avoids importing heavy
    # production dependencies (argparse, file I/O, caching) while exercising
    # the same classification decisions.  If the production matching logic in
    # main() changes, this helper MUST be updated to stay in sync.
    #
    # hash_drives is keyed by (InvHashConfig, size, hash) — same as production.
    # target_hashes is a list of (InvHashConfig, hash) pairs — same as production.
    def _classify(
        self,
        target_hashes,
        target_size,
        target_name,
        target_date,
        hash_drives,
        strong_drives,
        weak_drives,
        allow_strong=False,
        allow_weak=False,
    ):
        """Simulate the matching logic from main().

        target_hashes: list of (InvHashConfig, hash_str) pairs.
        hash_drives:   dict keyed by (InvHashConfig, size, hash) -> set of drives.
        """
        match_type, safety, drives = "missing", "missing", set()

        for icfg, h in target_hashes:
            hk = (icfg, target_size, h)
            if hk in hash_drives:
                drives = hash_drives[hk]
                match_type = safety = "verified_hash"
                break

        if not drives:
            sk = (target_name, target_size, target_date)
            wk = (target_name, target_size)
            if target_date and sk in strong_drives:
                drives = strong_drives[sk]
                match_type = "strong"
                safety = "strong_nohash_allowed" if allow_strong else "strong"
            elif wk in weak_drives:
                drives = weak_drives[wk]
                match_type = "weak"
                safety = "weak_nohash_allowed" if allow_weak else "weak"

        return safety, match_type, classify_safe_to_delete(safety)

    def test_verified_hash_same_config(self):
        """Hash + same config -> verified_hash -> safe."""
        cfg = self.CFG_SAMPLE_B2
        safety, _, safe = self._classify(
            target_hashes=[(cfg, "aabb")],
            target_size=1000,
            target_name="a.jpg",
            target_date="",
            hash_drives={(cfg, 1000, "aabb"): {"drive1"}},
            strong_drives={},
            weak_drives={},
        )
        self.assertEqual(safety, "verified_hash")
        self.assertTrue(safe)

    def test_cross_config_same_digest_rejected(self):
        """Same digest but different config -> NOT verified_hash.

        This is the critical safety test: even if two configs produce the same
        digest string for the same file size (astronomically unlikely in practice,
        but must be handled correctly), the config-keyed lookup must reject it.
        """
        inv_cfg = self.CFG_SAMPLE_B2
        target_cfg = self.CFG_SAMPLE_S256  # different algo
        safety, mt, safe = self._classify(
            target_hashes=[(target_cfg, "aabb")],  # computed with sha256
            target_size=1000,
            target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={(inv_cfg, 1000, "aabb"): {"drive1"}},  # stored as blake2b
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
        )
        # Must NOT be verified_hash — different config families
        self.assertNotEqual(safety, "verified_hash")
        # Falls through to strong (not safe without flag)
        self.assertEqual(safety, "strong")
        self.assertEqual(mt, "strong")
        self.assertFalse(safe)

    def test_multi_config_correct_one_matches(self):
        """Multiple target hashes from different configs — only same-config match."""
        cfg_a = self.CFG_SAMPLE_B2
        cfg_b = self.CFG_SAMPLE_S256
        safety, _, safe = self._classify(
            target_hashes=[(cfg_a, "xxxx"), (cfg_b, "aabb")],
            target_size=1000,
            target_name="a.jpg",
            target_date="",
            hash_drives={(cfg_b, 1000, "aabb"): {"drive1"}},  # only cfg_b matches
            strong_drives={},
            weak_drives={},
        )
        self.assertEqual(safety, "verified_hash")
        self.assertTrue(safe)

    def test_hash_no_match_falls_through(self):
        """Target hash computed but not found in hash_drives -> falls to metadata."""
        cfg = self.CFG_SAMPLE_B2
        safety, _, safe = self._classify(
            target_hashes=[(cfg, "ccdd")],
            target_size=1000,
            target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={(cfg, 1000, "aabb"): {"drive1"}},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
        )
        self.assertEqual(safety, "strong")
        self.assertFalse(safe)

    def test_strong_match_not_safe_by_default(self):
        """Strong match (name+size+date) without --allow-strong -> NOT safe."""
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
        )
        self.assertEqual(safety, "strong")
        self.assertFalse(safe)

    def test_strong_match_safe_with_flag(self):
        """Strong match + --allow-strong-without-hash -> safe."""
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
            allow_strong=True,
        )
        self.assertEqual(safety, "strong_nohash_allowed")
        self.assertTrue(safe)

    def test_weak_match_not_safe_by_default(self):
        """Weak match (name+size) -> NOT safe without flag."""
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="a.jpg",
            target_date="",
            hash_drives={},
            strong_drives={},
            weak_drives={("a.jpg", 1000): {"drive1"}},
        )
        self.assertEqual(safety, "weak")
        self.assertFalse(safe)

    def test_weak_match_safe_with_flag(self):
        """Weak match + --allow-weak-without-hash -> safe."""
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="a.jpg",
            target_date="",
            hash_drives={},
            strong_drives={},
            weak_drives={("a.jpg", 1000): {"drive1"}},
            allow_weak=True,
        )
        self.assertEqual(safety, "weak_nohash_allowed")
        self.assertTrue(safe)

    def test_no_match_is_missing(self):
        """File not found in any inventory -> missing -> NOT safe."""
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="unknown.jpg",
            target_date="",
            hash_drives={},
            strong_drives={},
            weak_drives={},
        )
        self.assertEqual(safety, "missing")
        self.assertFalse(safe)

    def test_full_hash_same_config(self):
        """Full hash match with same config -> verified_hash -> safe."""
        cfg = self.CFG_FULL_S256
        safety, _, safe = self._classify(
            target_hashes=[(cfg, "aabb")],
            target_size=1000,
            target_name="a.jpg",
            target_date="",
            hash_drives={(cfg, 1000, "aabb"): {"drive1"}},
            strong_drives={},
            weak_drives={},
        )
        self.assertEqual(safety, "verified_hash")
        self.assertTrue(safe)

    def test_no_hashes_falls_through_to_strong_with_flag(self):
        """No target hashes + --allow-strong -> strong_nohash_allowed -> safe."""
        cfg = self.CFG_SAMPLE_B2
        safety, _, safe = self._classify(
            target_hashes=[],
            target_size=1000,
            target_name="a.jpg",
            target_date="2024:01:01 12:00:00",
            hash_drives={(cfg, 1000, "aabb"): {"drive1"}},
            strong_drives={("a.jpg", 1000, "2024:01:01 12:00:00"): {"drive1"}},
            weak_drives={},
            allow_strong=True,
        )
        self.assertEqual(safety, "strong_nohash_allowed")
        self.assertTrue(safe)


# ===========================================================================
# End-to-end test using real on-disk inventories and production code paths
# ===========================================================================


class TestEndToEndInventoryMatching(unittest.TestCase):
    """Build real inventory TSVs on disk and run the production loading +
    matching flow to verify same-config verification end-to-end."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _build_inventory(
        self,
        name,
        rows,
        hash_mode="sample",
        algo="blake2b",
        chunks=3,
        chunk_mib=0.0625,
        inventory_root="/inv",
    ):
        """Write a complete inventory TSV with proper headers."""
        lines = []
        lines.append(f"# inventory_root={inventory_root}")
        lines.append(f"# hash_mode={hash_mode}")
        if hash_mode == "sample":
            lines.append("# content_hash_format=samplehash_v1")
            lines.append(
                f"# samplehash_v1 algo={algo} chunks={chunks} chunk_mib={chunk_mib}"
            )
        elif hash_mode == "full":
            lines.append("# content_hash_format=fullhash_v1")
            lines.append(f"# fullhash algo={algo}")
        lines.append("# Generated by findphotodates.py")
        lines.append(
            "\t".join(
                [
                    "filepath",
                    "date_taken",
                    "size_bytes",
                    "mtime_ns",
                    "gps_lat",
                    "gps_lon",
                    "location",
                    "content_hash",
                ]
            )
        )
        for row in rows:
            lines.append("\t".join(str(x) for x in row))
        p = Path(self.tmp) / name
        p.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return p

    def _load_inventory_into_dicts(
        self,
        inv_path,
        resolved_sample_algo="blake2b",
        resolved_full_algo="sha256",
        sample_chunks=3,
        sample_chunk_mib=0.0625,
    ):
        """Run the production inventory-loading code path and return the
        resulting data structures."""
        from check_photo_backups import drive_label_from_inventory_filename

        hash_drives = {}
        strong_drives = {}
        weak_drives = {}
        inv_hash_configs = set()
        sizes_with_hashes = set()

        def _parse_inv_hash_config(hdrs):
            if "samplehash_v1" in hdrs:
                cfg = parse_config_str(hdrs["samplehash_v1"])
                a = cfg.get("algo", resolved_sample_algo)
                c = int(cfg.get("chunks", str(sample_chunks)))
                cm = float(cfg.get("chunk_mib", str(sample_chunk_mib)))
                return InvHashConfig("sample", a, c, int(cm * 1024 * 1024))
            if "fullhash" in hdrs:
                cfg = parse_config_str(hdrs.get("fullhash", ""))
                a = cfg.get("algo", resolved_full_algo)
                return InvHashConfig("full", a, 0, 0)
            return None

        drive = drive_label_from_inventory_filename(inv_path)
        current_inv_cfg = None

        for (
            filepath,
            date_taken,
            size_bytes,
            _mtime_ns,
            content_hash,
            headers,
        ) in iter_inventory_rows(inv_path):
            if current_inv_cfg is None:
                current_inv_cfg = _parse_inv_hash_config(headers)

            base = os.path.basename(filepath).lower()
            if not base:
                continue
            if date_taken and size_bytes is not None:
                sk = (base, size_bytes, date_taken)
                strong_drives.setdefault(sk, set()).add(drive)
            if size_bytes is not None:
                wk = (base, size_bytes)
                weak_drives.setdefault(wk, set()).add(drive)
                if content_hash and current_inv_cfg is not None:
                    sizes_with_hashes.add(size_bytes)
                    hk = (current_inv_cfg, size_bytes, content_hash)
                    hash_drives.setdefault(hk, set()).add(drive)

        if current_inv_cfg is not None:
            inv_hash_configs.add(current_inv_cfg)

        return (
            hash_drives,
            strong_drives,
            weak_drives,
            inv_hash_configs,
            sizes_with_hashes,
        )

    def test_same_config_verified(self):
        """Inventory with blake2b sample hash — target computed with same config — verified."""
        inv = self._build_inventory(
            "drive1_inv.tsv",
            [
                [
                    "/inv/photo.jpg",
                    "2024:01:01 12:00:00",
                    5000,
                    1700000000000000000,
                    "",
                    "",
                    "",
                    "aabbccdd",
                ],
            ],
            algo="blake2b",
        )

        hd, _sd, _wd, cfgs, _ = self._load_inventory_into_dicts(inv)

        # Simulate target hash computed with the same config
        self.assertEqual(len(cfgs), 1)
        cfg = next(iter(cfgs))
        self.assertEqual(cfg.algo, "blake2b")

        # Target hash matches
        hk = (cfg, 5000, "aabbccdd")
        self.assertIn(hk, hd, "Same-config hash should be in hash_drives")

    def test_cross_config_not_verified(self):
        """Inventory with blake2b — lookup with sha256 config — must NOT match."""
        inv = self._build_inventory(
            "drive1_inv.tsv",
            [
                [
                    "/inv/photo.jpg",
                    "2024:01:01 12:00:00",
                    5000,
                    1700000000000000000,
                    "",
                    "",
                    "",
                    "aabbccdd",
                ],
            ],
            algo="blake2b",
        )

        hd, _, _, _, _ = self._load_inventory_into_dicts(inv)

        # A different config with same digest should NOT match
        wrong_cfg = InvHashConfig("sample", "sha256", 3, 65536)
        hk_wrong = (wrong_cfg, 5000, "aabbccdd")
        self.assertNotIn(
            hk_wrong,
            hd,
            "Cross-config lookup must NOT find a match even with same digest",
        )

    def test_mixed_inventories_both_configs_loaded(self):
        """Two inventories with different configs — both configs should be available."""
        inv_a = self._build_inventory(
            "a_inv.tsv",
            [
                ["/inv/photo.jpg", "", 5000, 170000, "", "", "", "aaaa"],
            ],
            algo="blake2b",
        )
        inv_b = self._build_inventory(
            "b_inv.tsv",
            [
                ["/inv/photo.jpg", "", 5000, 170000, "", "", "", "bbbb"],
            ],
            algo="sha256",
        )

        hd_a, _, _, cfgs_a, _ = self._load_inventory_into_dicts(inv_a)
        hd_b, _, _, cfgs_b, _ = self._load_inventory_into_dicts(inv_b)

        # Merge (as main() does across inventories)
        all_cfgs = cfgs_a | cfgs_b
        all_hd = {**hd_a, **hd_b}

        self.assertEqual(len(all_cfgs), 2, "Should have two distinct configs")
        algos = {c.algo for c in all_cfgs}
        self.assertEqual(algos, {"blake2b", "sha256"})

        # Each config's entry is keyed correctly
        cfg_b2 = next(c for c in all_cfgs if c.algo == "blake2b")
        cfg_s2 = next(c for c in all_cfgs if c.algo == "sha256")
        self.assertIn((cfg_b2, 5000, "aaaa"), all_hd)
        self.assertIn((cfg_s2, 5000, "bbbb"), all_hd)
        # Cross-config lookups fail
        self.assertNotIn((cfg_s2, 5000, "aaaa"), all_hd)
        self.assertNotIn((cfg_b2, 5000, "bbbb"), all_hd)


# ===========================================================================
# CLI-level integration: runs main() with real files and real inventories
# ===========================================================================


class TestCLIEndToEnd(unittest.TestCase):
    """Run the production main() flow end-to-end.

    Creates real files on disk, computes their actual hashes using production
    hash functions, builds inventory TSVs, invokes main() via sys.argv, and
    checks that the output files contain the expected entries.
    """

    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="cli_e2e_")
        self.target_dir = os.path.join(self.tmp, "target")
        os.makedirs(self.target_dir)
        self.out_dir = os.path.join(self.tmp, "out")
        os.makedirs(self.out_dir)

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _create_file(self, name, content):
        """Create a file in target_dir with given content, return its Path and stat."""
        p = Path(self.target_dir) / name
        p.write_bytes(content)
        st = p.stat()
        return p, st.st_size, st.st_mtime_ns

    def _build_inventory(
        self,
        name,
        rows,
        hash_mode="sample",
        algo="blake2b",
        chunks=3,
        chunk_mib=0.0625,
        inventory_root=None,
    ):
        """Write a complete inventory TSV."""
        if inventory_root is None:
            inventory_root = self.target_dir
        lines = [f"# inventory_root={inventory_root}"]
        lines.append(f"# hash_mode={hash_mode}")
        if hash_mode == "sample":
            lines.append("# content_hash_format=samplehash_v1")
            lines.append(
                f"# samplehash_v1 algo={algo} chunks={chunks} chunk_mib={chunk_mib}"
            )
        elif hash_mode == "full":
            lines.append("# content_hash_format=fullhash_v1")
            lines.append(f"# fullhash algo={algo}")
        lines.append("# Generated by findphotodates.py")
        lines.append(
            "\t".join(
                [
                    "filepath",
                    "date_taken",
                    "size_bytes",
                    "mtime_ns",
                    "gps_lat",
                    "gps_lon",
                    "location",
                    "content_hash",
                ]
            )
        )
        for row in rows:
            lines.append("\t".join(str(x) for x in row))
        p = Path(self.tmp) / name
        p.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return p

    def _run_main(self, extra_args=None):
        """Invoke check_photo_backups.main() with sys.argv and return exit code."""
        import check_photo_backups

        old_argv = sys.argv
        try:
            sys.argv = ["check_photo_backups.py"] + (extra_args or [])
            return check_photo_backups.main()
        finally:
            sys.argv = old_argv

    def _read_lines(self, filename):
        """Read non-empty lines from an output file."""
        p = Path(self.out_dir) / filename
        if not p.exists():
            return []
        return [
            line for line in p.read_text(encoding="utf-8").splitlines() if line.strip()
        ]

    def test_verified_hash_match_produces_safe(self):
        """File whose sample hash matches same-config inventory -> safe_to_delete=yes."""
        from check_photo_backups import compute_samplehash_v1

        # Create a real file with enough content for sample hashing
        content = b"A" * 300_000  # 300KB — enough for 3x64KB sample chunks
        fpath, fsize, fmtime = self._create_file("photo.jpg", content)

        # Compute its actual hash using the production function
        chunk_bytes = int(0.0625 * 1024 * 1024)  # 65536
        real_hash = compute_samplehash_v1(fpath, chunk_bytes, 3, "blake2b")
        self.assertTrue(real_hash, "Should compute a non-empty hash")

        # Build an inventory with this hash
        inv = self._build_inventory(
            "backup_inv.tsv",
            [
                [
                    str(fpath),
                    "2024:01:01 12:00:00",
                    fsize,
                    fmtime,
                    "",
                    "",
                    "",
                    real_hash,
                ],
            ],
            algo="blake2b",
        )

        safe_list = os.path.join(self.out_dir, "safe.txt")
        missing_list = os.path.join(self.out_dir, "missing.txt")
        csv_report = os.path.join(self.out_dir, "report.csv")

        self._run_main(
            [
                "--target",
                self.target_dir,
                "--inventories",
                str(inv),
                "--safe-list",
                safe_list,
                "--missing-list",
                missing_list,
                "--out-csv",
                csv_report,
                "--needs-hash-list",
                os.path.join(self.out_dir, "needs.txt"),
                "--no-verified-match-list",
                os.path.join(self.out_dir, "no_match.txt"),
                "--hash-config-mismatch-list",
                os.path.join(self.out_dir, "mismatch.txt"),
                "--no-fingerprint-cache",
                "-q",
            ]
        )

        # The file should appear in safe_to_delete
        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(len(safe_lines), 1)
        self.assertIn("photo.jpg", safe_lines[0])

        # CSV should show verified_hash / safe_to_delete=yes
        csv_lines = Path(csv_report).read_text(encoding="utf-8").splitlines()
        self.assertTrue(len(csv_lines) >= 2, "CSV should have header + data row")
        import csv as csv_mod

        reader = csv_mod.DictReader(csv_lines)
        rows = list(reader)
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["safety"], "verified_hash")
        self.assertEqual(rows[0]["safe_to_delete"], "yes")

    def test_cross_config_hash_not_verified(self):
        """File hashed with blake2b but inventory uses sha256 -> NOT safe (falls to metadata)."""
        from check_photo_backups import compute_samplehash_v1

        content = b"B" * 300_000
        fpath, fsize, fmtime = self._create_file("cross.jpg", content)

        # Compute hash with sha256 and put it in a blake2b-labeled inventory
        # This simulates a real mismatch — the inventory claims blake2b but
        # the hash was actually computed with sha256
        sha256_hash = compute_samplehash_v1(fpath, 65536, 3, "sha256")
        self.assertTrue(sha256_hash)

        # Inventory says blake2b but contains a sha256 hash — this shouldn't
        # verify because the target will re-hash with blake2b and get a
        # different digest
        inv = self._build_inventory(
            "mismatched_inv.tsv",
            [
                [str(fpath), "", fsize, fmtime, "", "", "", sha256_hash],
            ],
            algo="blake2b",
        )

        safe_list = os.path.join(self.out_dir, "safe.txt")
        csv_report = os.path.join(self.out_dir, "report.csv")

        self._run_main(
            [
                "--target",
                self.target_dir,
                "--inventories",
                str(inv),
                "--safe-list",
                safe_list,
                "--out-csv",
                csv_report,
                "--missing-list",
                os.path.join(self.out_dir, "missing.txt"),
                "--needs-hash-list",
                os.path.join(self.out_dir, "needs.txt"),
                "--no-verified-match-list",
                os.path.join(self.out_dir, "no_match.txt"),
                "--hash-config-mismatch-list",
                os.path.join(self.out_dir, "mismatch.txt"),
                "--no-fingerprint-cache",
                "-q",
            ]
        )

        # Should NOT be in safe list (hash mismatch, no --allow-strong flag)
        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(len(safe_lines), 0, "Cross-config hash should not be safe")

        # CSV should show it fell through to metadata match (strong or weak), not verified_hash
        import csv as csv_mod

        rows = list(
            csv_mod.DictReader(
                Path(csv_report).read_text(encoding="utf-8").splitlines()
            )
        )
        self.assertEqual(len(rows), 1)
        self.assertNotEqual(
            rows[0]["safety"],
            "verified_hash",
            "Cross-config should never produce verified_hash",
        )

    def test_mixed_config_inventories(self):
        """Two inventories with different hash configs — only same-config match is safe."""
        from check_photo_backups import compute_samplehash_v1

        content_a = b"C" * 300_000
        content_b = b"D" * 300_000
        fpath_a, fsize_a, fmtime_a = self._create_file("matched.jpg", content_a)
        fpath_b, fsize_b, fmtime_b = self._create_file("unmatched.jpg", content_b)

        # Compute correct hashes
        hash_a_b2 = compute_samplehash_v1(fpath_a, 65536, 3, "blake2b")
        hash_b_s256 = compute_samplehash_v1(fpath_b, 65536, 3, "sha256")

        # Inventory 1: blake2b, has file A with correct hash
        inv1 = self._build_inventory(
            "inv_blake2b.tsv",
            [
                [str(fpath_a), "2024:01:01", fsize_a, fmtime_a, "", "", "", hash_a_b2],
            ],
            algo="blake2b",
        )

        # Inventory 2: sha256, has file B with correct hash BUT stored under
        # sha256 config. File A is NOT in this inventory.
        inv2 = self._build_inventory(
            "inv_sha256.tsv",
            [
                [
                    str(fpath_b),
                    "2024:02:02",
                    fsize_b,
                    fmtime_b,
                    "",
                    "",
                    "",
                    hash_b_s256,
                ],
            ],
            algo="sha256",
        )

        safe_list = os.path.join(self.out_dir, "safe.txt")
        csv_report = os.path.join(self.out_dir, "report.csv")

        self._run_main(
            [
                "--target",
                self.target_dir,
                "--inventories",
                f"{inv1},{inv2}",
                "--safe-list",
                safe_list,
                "--out-csv",
                csv_report,
                "--missing-list",
                os.path.join(self.out_dir, "missing.txt"),
                "--needs-hash-list",
                os.path.join(self.out_dir, "needs.txt"),
                "--no-verified-match-list",
                os.path.join(self.out_dir, "no_match.txt"),
                "--hash-config-mismatch-list",
                os.path.join(self.out_dir, "mismatch.txt"),
                "--no-fingerprint-cache",
                "-q",
            ]
        )

        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(
            len(safe_lines),
            2,
            "Both files should be safe (each matches its own inventory)",
        )

        # CSV should show both as verified_hash
        import csv as csv_mod

        rows = list(
            csv_mod.DictReader(
                Path(csv_report).read_text(encoding="utf-8").splitlines()
            )
        )
        rows_by_name = {os.path.basename(r["target_path"]): r for r in rows}
        self.assertEqual(rows_by_name["matched.jpg"]["safety"], "verified_hash")
        self.assertEqual(rows_by_name["unmatched.jpg"]["safety"], "verified_hash")

    def test_metadata_fallback_with_allow_weak(self):
        """File without hash in inventory, matched by name+size with --allow-weak -> safe.

        Uses weak match because synthetic test files have no EXIF date, so
        the target's date_taken is "" and the strong-match branch is skipped.
        This is the realistic path for non-JPEG or EXIF-less files.
        """
        content = b"E" * 5000
        fpath, fsize, fmtime = self._create_file("meta.jpg", content)

        # Inventory with no hash (hash_mode=off — no samplehash header)
        lines = [
            f"# inventory_root={self.target_dir}",
            "# hash_mode=off",
            "# Generated by findphotodates.py",
            "\t".join(
                [
                    "filepath",
                    "date_taken",
                    "size_bytes",
                    "mtime_ns",
                    "gps_lat",
                    "gps_lon",
                    "location",
                    "content_hash",
                ]
            ),
            f"{fpath}\t2024:06:15 10:30:00\t{fsize}\t{fmtime}\t\t\t\t",
        ]
        inv_path = Path(self.tmp) / "nohash_inv.tsv"
        inv_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

        safe_list = os.path.join(self.out_dir, "safe.txt")
        csv_report = os.path.join(self.out_dir, "report.csv")
        common_args = [
            "--target",
            self.target_dir,
            "--inventories",
            str(inv_path),
            "--safe-list",
            safe_list,
            "--out-csv",
            csv_report,
            "--missing-list",
            os.path.join(self.out_dir, "missing.txt"),
            "--needs-hash-list",
            os.path.join(self.out_dir, "needs.txt"),
            "--no-verified-match-list",
            os.path.join(self.out_dir, "no_match.txt"),
            "--hash-config-mismatch-list",
            os.path.join(self.out_dir, "mismatch.txt"),
            "--no-fingerprint-cache",
            "--exts",
            "jpg",
            "-q",
        ]

        # Without --allow-weak: not safe
        self._run_main(common_args)

        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(
            len(safe_lines), 0, "Without --allow-weak, metadata match is not safe"
        )

        import csv as csv_mod

        rows = list(
            csv_mod.DictReader(
                Path(csv_report).read_text(encoding="utf-8").splitlines()
            )
        )
        self.assertEqual(
            rows[0]["safety"], "weak", "Should be weak match (no EXIF date on target)"
        )

        # With --allow-weak: safe
        self._run_main(common_args + ["--allow-weak-without-hash"])

        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(
            len(safe_lines), 1, "With --allow-weak, metadata match should be safe"
        )

        rows = list(
            csv_mod.DictReader(
                Path(csv_report).read_text(encoding="utf-8").splitlines()
            )
        )
        self.assertEqual(rows[0]["safety"], "weak_nohash_allowed")

    def test_output_files_populated(self):
        """Verify that missing files appear in the missing list and delete script works."""
        # Create a file with no inventory match at all
        content = b"Z" * 1000
        self._create_file("orphan.jpg", content)

        # Empty inventory (valid format but no matching entries)
        inv = self._build_inventory("empty_inv.tsv", [], algo="blake2b")

        safe_list = os.path.join(self.out_dir, "safe.txt")
        missing_list = os.path.join(self.out_dir, "missing.txt")
        delete_script = os.path.join(self.out_dir, "delete.sh")

        self._run_main(
            [
                "--target",
                self.target_dir,
                "--inventories",
                str(inv),
                "--safe-list",
                safe_list,
                "--missing-list",
                missing_list,
                "--out-csv",
                os.path.join(self.out_dir, "report.csv"),
                "--needs-hash-list",
                os.path.join(self.out_dir, "needs.txt"),
                "--no-verified-match-list",
                os.path.join(self.out_dir, "no_match.txt"),
                "--hash-config-mismatch-list",
                os.path.join(self.out_dir, "mismatch.txt"),
                "--delete-script",
                delete_script,
                "--no-fingerprint-cache",
                "-q",
            ]
        )

        missing_lines = [
            line
            for line in Path(missing_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(len(missing_lines), 1)
        self.assertIn("orphan.jpg", missing_lines[0])

        safe_lines = [
            line
            for line in Path(safe_list).read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        self.assertEqual(len(safe_lines), 0, "No matches means nothing is safe")

        # Delete script should be empty (no safe files to delete)
        ds_text = Path(delete_script).read_text(encoding="utf-8")
        self.assertIn("#!/bin/bash", ds_text)
        self.assertNotIn("orphan.jpg", ds_text)


if __name__ == "__main__":
    unittest.main()
