import json
import subprocess

import findphotodates as fpd


def test_normalize_exif_date_accepts_canonical_date():
    assert (
        fpd._normalize_exif_date("2022:03:03 05:35:44")
        == "2022:03:03 05:35:44"
    )


def test_normalize_exif_date_strips_timezone_offsets():
    assert (
        fpd._normalize_exif_date("2022:03:03 05:35:44+01:00")
        == "2022:03:03 05:35:44"
    )
    assert (
        fpd._normalize_exif_date("2015:09:10 16:32:52-07:00")
        == "2015:09:10 16:32:52"
    )
    assert (
        fpd._normalize_exif_date("2017:12:14 01:59:10+09:00")
        == "2017:12:14 01:59:10"
    )
    assert (
        fpd._normalize_exif_date("2024:01:01 00:00:00Z")
        == "2024:01:01 00:00:00"
    )


def test_normalize_exif_date_rejects_placeholder_dates():
    assert fpd._normalize_exif_date("0000:00:00 00:00:00") is None
    assert fpd._normalize_exif_date("0001:01:01 00:00:00") is None


def test_normalize_exif_date_rejects_junk_values():
    assert fpd._normalize_exif_date("") is None
    assert fpd._normalize_exif_date(None) is None
    assert fpd._normalize_exif_date("-") is None
    assert fpd._normalize_exif_date("not a date") is None
    assert fpd._normalize_exif_date("2022:03:03") is None


def test_normalize_exif_date_uses_1900_cutoff():
    assert (
        fpd._normalize_exif_date("1900:01:01 00:00:00")
        == "1900:01:01 00:00:00"
    )
    assert fpd._normalize_exif_date("1899:12:31 23:59:59") is None


def test_batch_query_normalizes_dates_from_json(monkeypatch):
    requested = ["tz.jpg", "zero.jpg", "utc.jpg"]
    records = [
        {
            "SourceFile": "tz.jpg",
            "DateTimeOriginal": "2022:03:03 05:35:44+01:00",
        },
        {
            "SourceFile": "zero.jpg",
            "DateTimeOriginal": "0000:00:00 00:00:00",
        },
        {
            "SourceFile": "utc.jpg",
            "CreateDate": "2024:01:01 00:00:00Z",
        },
    ]

    exiftool = fpd.ExifToolPersistent()
    monkeypatch.setattr(
        exiftool,
        "_send_and_read",
        lambda args: json.dumps(records).splitlines(),
    )

    assert exiftool.batch_query(requested) == {
        "tz.jpg": ("2022:03:03 05:35:44", None, None),
        "zero.jpg": (None, None, None),
        "utc.jpg": ("2024:01:01 00:00:00", None, None),
    }


def test_parse_lines_normalizes_single_file_query_dates():
    exiftool = fpd.ExifToolPersistent()

    assert exiftool._parse_lines(
        ["2022:03:03 05:35:44+01:00", "-", "-", "-", "-"]
    ) == ("2022:03:03 05:35:44", None, None)
    assert exiftool._parse_lines(["0000:00:00 00:00:00", "-", "-", "-", "-"]) == (
        None,
        None,
        None,
    )


def test_get_photo_data_legacy_fallback_normalizes_dates(monkeypatch):
    completed = subprocess.CompletedProcess(
        args=["exiftool"],
        returncode=0,
        stdout="2022:03:03 05:35:44+01:00\n-\n-\n-\n-\n",
        stderr="",
    )
    monkeypatch.setattr(subprocess, "run", lambda *args, **kwargs: completed)

    assert fpd.get_photo_data("photo.jpg") == ("2022:03:03 05:35:44", None, None)


def test_load_cache_heals_legacy_malformed_dates(tmp_path):
    inventory = tmp_path / "inventory.tsv"
    tz_path = str(tmp_path / "tz.jpg")
    zero_path = str(tmp_path / "zero.jpg")
    inventory.write_text(
        "\n".join(
            [
                "# Generated by findphotodates.py",
                "\t".join(fpd.TSV_COLUMNS),
                "\t".join(
                    [
                        tz_path,
                        "2022:03:03 05:35:44+01:00",
                        "100",
                        "1000",
                        "",
                        "",
                        "",
                        "",
                    ]
                ),
                "\t".join(
                    [
                        zero_path,
                        "0000:00:00 00:00:00",
                        "200",
                        "2000",
                        "",
                        "",
                        "",
                        "",
                    ]
                ),
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    cache = fpd.load_cache(str(inventory))

    assert cache[fpd._normalize_cache_key(tz_path)]["date_taken"] == (
        "2022:03:03 05:35:44"
    )
    assert cache[fpd._normalize_cache_key(zero_path)]["date_taken"] is None
