"""Tests for auto path-style detection, resolution, and write consistency."""

import csv
import os
import platform
import tempfile

import findphotodates as fpd

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_tsv(lines, path=None):
    """Write *lines* (list of str) to a temp file and return the path."""
    fd, p = tempfile.mkstemp(suffix=".tsv", dir=path)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    return p


def _read_tsv(path):
    """Return (comment_lines, header, data_rows) from a TSV file."""
    comments = []
    header = None
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n\r")
            if not line:
                continue
            if line.startswith("#"):
                comments.append(line)
                continue
            if header is None:
                header = line.split("\t")
                continue
            rows.append(next(csv.reader([line], delimiter="\t")))
    return comments, header, rows


class DummyHashOpts:
    hash_mode = "off"
    hash_exts = None
    use_hash_cache = False
    hash_cache_path = None
    sample_chunk_mib = 0
    sample_chunks = 0
    sample_algo = "blake2b"
    full_algo = "sha256"


# ---------------------------------------------------------------------------
# detect_inventory_path_style
# ---------------------------------------------------------------------------


class TestDetectInventoryPathStyle:
    def test_detects_windows_from_inventory_root(self, tmp_path):
        p = _make_tsv(
            [
                "# inventory_root=C:\\Photos\\Vacation",
                "# Generated by findphotodates.py",
                "\t".join(fpd.TSV_COLUMNS),
                "C:\\Photos\\Vacation\\img.jpg\t\t1024\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.detect_inventory_path_style(p) == "windows"

    def test_detects_linux_from_inventory_root(self, tmp_path):
        p = _make_tsv(
            [
                "# inventory_root=/mnt/c/Photos/Vacation",
                "# Generated by findphotodates.py",
                "\t".join(fpd.TSV_COLUMNS),
                "/mnt/c/Photos/Vacation/img.jpg\t\t1024\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.detect_inventory_path_style(p) == "linux"

    def test_detects_windows_from_first_data_row(self, tmp_path):
        p = _make_tsv(
            [
                "# Generated by findphotodates.py",
                "\t".join(fpd.TSV_COLUMNS),
                "D:\\Data\\file.txt\t\t512\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.detect_inventory_path_style(p) == "windows"

    def test_detects_linux_from_first_data_row(self, tmp_path):
        p = _make_tsv(
            [
                "# Generated by findphotodates.py",
                "\t".join(fpd.TSV_COLUMNS),
                "/home/user/file.txt\t\t512\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.detect_inventory_path_style(p) == "linux"

    def test_returns_none_for_empty_file(self, tmp_path):
        p = _make_tsv([], path=str(tmp_path))
        assert fpd.detect_inventory_path_style(p) is None

    def test_returns_none_for_nonexistent_file(self):
        assert fpd.detect_inventory_path_style("/nonexistent/path.tsv") is None


# ---------------------------------------------------------------------------
# resolve_output_path_style
# ---------------------------------------------------------------------------


class TestResolveOutputPathStyle:
    def test_explicit_linux(self):
        assert fpd.resolve_output_path_style("linux", None, None) == "linux"

    def test_explicit_windows(self):
        assert fpd.resolve_output_path_style("windows", None, None) == "windows"

    def test_auto_preserves_existing_windows(self, tmp_path):
        p = _make_tsv(
            [
                "# inventory_root=C:\\Photos",
                "\t".join(fpd.TSV_COLUMNS),
                "C:\\Photos\\a.jpg\t\t100\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.resolve_output_path_style("auto", p, "/mnt/c/Photos") == "windows"

    def test_auto_preserves_existing_linux(self, tmp_path):
        p = _make_tsv(
            [
                "# inventory_root=/mnt/c/Photos",
                "\t".join(fpd.TSV_COLUMNS),
                "/mnt/c/Photos/a.jpg\t\t100\t0\t\t\t\t",
            ],
            path=str(tmp_path),
        )
        assert fpd.resolve_output_path_style("auto", p, "C:\\Photos") == "linux"

    def test_auto_infers_windows_from_directory(self):
        assert (
            fpd.resolve_output_path_style("auto", "/nonexistent.tsv", "C:\\Photos")
            == "windows"
        )

    def test_auto_infers_linux_from_wsl_directory(self):
        assert (
            fpd.resolve_output_path_style("auto", "/nonexistent.tsv", "/mnt/c/Photos")
            == "linux"
        )

    def test_auto_falls_back_to_platform(self):
        expected = "windows" if platform.system() == "Windows" else "linux"
        assert (
            fpd.resolve_output_path_style(
                "auto", "/nonexistent.tsv", "/home/user/photos"
            )
            == expected
        )


# ---------------------------------------------------------------------------
# write_dates_to_file_atomic: inventory_root correctness
# ---------------------------------------------------------------------------


class TestWriteInventoryRoot:
    def test_windows_style_inventory_root_not_mangled_on_linux(self, tmp_path):
        """On Linux/WSL, writing with path_style='windows' must not produce
        a bogus inventory_root like /current/dir/C:\\Photos."""
        out = str(tmp_path / "out.tsv")
        data = [("/mnt/c/Photos/a.jpg", "2023:01:01", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            hash_options=DummyHashOpts(),
            path_style="windows",
        )
        comments, _, rows = _read_tsv(out)
        root_lines = [c for c in comments if c.startswith("# inventory_root=")]
        assert len(root_lines) == 1
        root_val = root_lines[0].split("=", 1)[1]
        # Must be a clean Windows-style path
        assert (
            root_val.startswith("C:\\")
            or root_val.startswith("c:\\")
            or "\\" in root_val
        )
        assert not root_val.startswith("/")  # no bogus POSIX prefix

    def test_linux_style_inventory_root_correct(self, tmp_path):
        out = str(tmp_path / "out.tsv")
        data = [("/mnt/c/Photos/a.jpg", "2023:01:01", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            hash_options=DummyHashOpts(),
            path_style="linux",
        )
        comments, _, rows = _read_tsv(out)
        root_lines = [c for c in comments if c.startswith("# inventory_root=")]
        assert len(root_lines) == 1
        root_val = root_lines[0].split("=", 1)[1]
        assert root_val == "/mnt/c/Photos"

    def test_windows_inventory_root_and_rows_consistent(self, tmp_path):
        out = str(tmp_path / "out.tsv")
        data = [("/mnt/c/Photos/a.jpg", "", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            hash_options=DummyHashOpts(),
            path_style="windows",
        )
        comments, _, rows = _read_tsv(out)
        root_val = [c for c in comments if c.startswith("# inventory_root=")][0].split(
            "=", 1
        )[1]
        filepath = rows[0][0]
        # Both must be Windows-style
        assert "\\" in root_val
        assert "\\" in filepath

    def test_windows_drive_root_inventory_root_and_rows_consistent(self, tmp_path):
        out = str(tmp_path / "out.tsv")
        data = [("/mnt/c/a.jpg", "", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c",
            hash_options=DummyHashOpts(),
            path_style="windows",
        )
        comments, _, rows = _read_tsv(out)
        root_val = [c for c in comments if c.startswith("# inventory_root=")][0].split(
            "=", 1
        )[1]
        filepath = rows[0][0]
        assert root_val == "C:\\"
        assert filepath == "C:\\a.jpg"


# ---------------------------------------------------------------------------
# add_hashes_to_inventory preserves existing style
# ---------------------------------------------------------------------------


class TestAddHashesPreservesStyle:
    def test_windows_style_preserved_with_auto(self, tmp_path):
        tsv = str(tmp_path / "inv.tsv")
        lines = [
            "# inventory_root=C:\\Photos",
            "# Generated by findphotodates.py",
            "\t".join(fpd.TSV_COLUMNS),
            "C:\\Photos\\a.jpg\t2023:01:01\t100\t0\t\t\t\t",
        ]
        with open(tsv, "w", encoding="utf-8") as f:
            for line in lines:
                f.write(line + "\n")
        # Resolve auto -> should detect windows
        resolved = fpd.resolve_output_path_style("auto", tsv, None)
        assert resolved == "windows"

    def test_linux_style_preserved_with_auto(self, tmp_path):
        tsv = str(tmp_path / "inv.tsv")
        lines = [
            "# inventory_root=/mnt/c/Photos",
            "# Generated by findphotodates.py",
            "\t".join(fpd.TSV_COLUMNS),
            "/mnt/c/Photos/a.jpg\t2023:01:01\t100\t0\t\t\t\t",
        ]
        with open(tsv, "w", encoding="utf-8") as f:
            for line in lines:
                f.write(line + "\n")
        resolved = fpd.resolve_output_path_style("auto", tsv, None)
        assert resolved == "linux"

    def test_add_hashes_resolves_opposite_style_paths_locally(self, tmp_path):
        photo = tmp_path / "photo.jpg"
        photo.write_bytes(b"findphotodates path-style regression test")
        stat_info = photo.stat()

        native_path = str(photo)
        native_root = str(tmp_path)
        opposite_style = (
            "linux" if platform.system() == "Windows" else "windows"
        )
        stored_path = fpd.format_path_style(native_path, opposite_style)
        stored_root = fpd.format_path_style(native_root, opposite_style)

        tsv = str(tmp_path / "inventory.tsv")
        lines = [
            f"# inventory_root={stored_root}",
            "# Generated by findphotodates.py",
            "\t".join(fpd.TSV_COLUMNS),
            f"{stored_path}\t\t{stat_info.st_size}\t{stat_info.st_mtime_ns}\t\t\t\t",
        ]
        with open(tsv, "w", encoding="utf-8") as f:
            for line in lines:
                f.write(line + "\n")

        hash_opts = fpd.parse_hash_args(
            hash_mode="sample",
            sample_chunks=1,
            sample_chunk_mib=0.001,
            no_hash_cache=True,
            quiet=True,
        )
        resolved = fpd.resolve_output_path_style("auto", tsv, None)
        assert resolved == opposite_style

        assert fpd.add_hashes_to_inventory(
            tsv, hash_opts, quiet=True, path_style=resolved
        )

        comments, _, rows = _read_tsv(tsv)
        root_val = [c for c in comments if c.startswith("# inventory_root=")][0].split(
            "=", 1
        )[1]
        assert root_val == stored_root
        assert rows[0][0] == stored_path
        assert rows[0][7]


# ---------------------------------------------------------------------------
# Explicit --linux and --windows still force conversion
# ---------------------------------------------------------------------------


class TestExplicitOverride:
    def test_linux_forces_conversion(self, tmp_path):
        out = str(tmp_path / "out.tsv")
        # Data uses Windows-style internally but we force linux output
        data = [("C:\\Photos\\a.jpg", "", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="C:\\Photos",
            hash_options=DummyHashOpts(),
            path_style="linux",
        )
        _, _, rows = _read_tsv(out)
        assert rows[0][0].startswith("/mnt/")
        assert "\\" not in rows[0][0]

    def test_windows_forces_conversion(self, tmp_path):
        out = str(tmp_path / "out.tsv")
        data = [("/mnt/c/Photos/a.jpg", "", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            hash_options=DummyHashOpts(),
            path_style="windows",
        )
        _, _, rows = _read_tsv(out)
        assert "\\" in rows[0][0]
        assert not rows[0][0].startswith("/mnt/")


# ---------------------------------------------------------------------------
# Old-format output
# ---------------------------------------------------------------------------


class TestOldFormat:
    def test_old_format_windows_relative_paths_correct(self, tmp_path):
        out = str(tmp_path / "out.txt")
        data = [("/mnt/c/Photos/a.jpg", "2023:01:01 12:00:00", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            old_format=True,
            path_style="windows",
        )
        with open(out, encoding="utf-8") as f:
            content = f.read()
        # Should produce a relative path, not a bogus absolute one
        assert content.strip().startswith("./") or content.strip().startswith("C:\\")
        # Must not contain the bogus double-prefix from os.path.abspath on formatted path
        assert "/home/" not in content
        assert "/tmp/" not in content

    def test_old_format_linux_relative_paths_correct(self, tmp_path):
        out = str(tmp_path / "out.txt")
        data = [("/mnt/c/Photos/a.jpg", "2023:01:01 12:00:00", 100, 0, "", "", "", "")]
        fpd.write_dates_to_file_atomic(
            out,
            data,
            inventory_root="/mnt/c/Photos",
            old_format=True,
            path_style="linux",
        )
        with open(out, encoding="utf-8") as f:
            content = f.read()
        assert content.strip().startswith("./a.jpg:")


# ---------------------------------------------------------------------------
# Batch checkpoint gating
# ---------------------------------------------------------------------------


class TestHashBatchCheckpointGate:
    def test_disabled_when_hashing_off_even_if_cache_default_is_on(self):
        hash_opts = fpd.parse_hash_args(hash_mode="off", quiet=True)
        assert hash_opts.use_hash_cache is True
        assert not fpd._should_write_hash_batch_checkpoint(
            fpd.HASH_CACHE_BATCH_COMMIT_EVERY, hash_opts, object()
        )

    def test_enabled_when_hashing_and_cache_commit_boundary_are_active(self):
        hash_opts = fpd.parse_hash_args(hash_mode="sample", quiet=True)
        assert fpd._should_write_hash_batch_checkpoint(
            fpd.HASH_CACHE_BATCH_COMMIT_EVERY, hash_opts, object()
        )


# ---------------------------------------------------------------------------
# Checkpoint / interrupt consistency (unit-level: verifying path_style flows)
# ---------------------------------------------------------------------------


class TestCheckpointConsistency:
    def test_checkpoint_uses_resolved_style(self, tmp_path):
        """Verify that write_dates_to_file_atomic produces consistent output
        when called with the same resolved style (simulating checkpoint vs final)."""
        out_ckpt = str(tmp_path / "ckpt.tsv")
        out_final = str(tmp_path / "final.tsv")
        data = [("/mnt/c/Photos/a.jpg", "", 100, 0, "", "", "", "")]
        kwargs = dict(
            inventory_root="/mnt/c/Photos",
            hash_options=DummyHashOpts(),
            path_style="windows",
        )
        fpd.write_dates_to_file_atomic(out_ckpt, data, **kwargs)
        fpd.write_dates_to_file_atomic(out_final, data, **kwargs)

        ckpt_comments, _, ckpt_rows = _read_tsv(out_ckpt)
        final_comments, _, final_rows = _read_tsv(out_final)

        # inventory_root must match
        ckpt_root = [c for c in ckpt_comments if c.startswith("# inventory_root=")]
        final_root = [c for c in final_comments if c.startswith("# inventory_root=")]
        assert ckpt_root == final_root

        # filepath rows must match
        assert ckpt_rows == final_rows

    def test_interrupt_save_same_as_final(self, tmp_path):
        """Same as checkpoint test but named to cover the Ctrl-C save path."""
        out1 = str(tmp_path / "interrupt.tsv")
        out2 = str(tmp_path / "final.tsv")
        data = [("/mnt/c/Data/file.txt", "2024:06:15", 2048, 99999, "", "", "", "")]
        kwargs = dict(
            inventory_root="/mnt/c/Data",
            hash_options=DummyHashOpts(),
            path_style="linux",
        )
        fpd.write_dates_to_file_atomic(out1, data, **kwargs)
        fpd.write_dates_to_file_atomic(out2, data, **kwargs)
        with open(out1, encoding="utf-8") as f1, open(out2, encoding="utf-8") as f2:
            assert f1.read() == f2.read()


# ---------------------------------------------------------------------------
# Fallback behavior when style cannot be detected
# ---------------------------------------------------------------------------


class TestFallbackBehavior:
    def test_auto_with_undetectable_file_falls_back_to_directory(self, tmp_path):
        # Empty TSV with just a header, no inventory_root or data rows
        tsv = _make_tsv(["\t".join(fpd.TSV_COLUMNS)], path=str(tmp_path))
        result = fpd.resolve_output_path_style("auto", tsv, "C:\\Users\\Me\\Photos")
        assert result == "windows"

    def test_auto_with_undetectable_everything_falls_back_to_platform(self, tmp_path):
        tsv = _make_tsv(["\t".join(fpd.TSV_COLUMNS)], path=str(tmp_path))
        result = fpd.resolve_output_path_style("auto", tsv, "/home/user/photos")
        expected = "windows" if platform.system() == "Windows" else "linux"
        assert result == expected
